// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/777.proto

/*
Package protomsg is a generated protocol buffer package.

It is generated from these files:
	protobuf/777.proto
	protobuf/data.proto
	protobuf/dfdc.proto
	protobuf/fruitmary.proto
	protobuf/hall.proto
	protobuf/hongbao.proto
	protobuf/jpm.proto
	protobuf/lhd.proto
	protobuf/luckfruit.proto
	protobuf/red2black.proto

It has these top-level messages:
	ENTER_GAME_S777_REQ
	ENTER_GAME_S777_RES
	LEAVE_GAME_S777_REQ
	LEAVE_GAME_S777_RES
	START_S777_REQ
	START_S777_RES
	S777Position
	UPDATE_S777_BONUS
	PLAYERS_S777_LIST_RES
	AccountStorageData
	AccountGameData
	Email
	RoomInfo
	GameInfo
	Card
	ENTER_GAME_DFDC_REQ
	ENTER_GAME_DFDC_RES
	LEAVE_GAME_DFDC_REQ
	LEAVE_GAME_DFDC_RES
	START_DFDC_REQ
	START_DFDC_RES
	DFDCPosition
	UPDATE_DFDC_BONUS
	PLAYERS_DFDC_LIST_RES
	ENTER_GAME_FRUITMARY_REQ
	ENTER_GAME_FRUITMARY_RES
	LEAVE_GAME_FRUITMARY_REQ
	LEAVE_GAME_FRUITMARY_RES
	START_MARY_REQ
	START_MARY_RES
	FRUITMARYPosition
	FRUITMARY_Result
	UPDATE_MARY_BONUS
	START_MARY2_REQ
	START_MARY2_RES
	Mary2_Result
	NEXT_MARY_RESULT
	PLAYERS_LIST_RES
	SYNC_SERVER_TIME
	KICK_OUT_HALL
	LOGIN_HALL_REQ
	LOGIN_HALL_RES
	SAFEMONEY_OPERATE_REQ
	SAFEMONEY_OPERATE_RES
	BIND_PHONE_REQ
	BIND_PHONE_RES
	ENTER_ROOM_REQ
	ENTER_ROOM_RES
	EMAILS_REQ
	EMAILS_RES
	EMAIL_READ_REQ
	EMAIL_READ_RES
	EMAIL_REWARD_REQ
	EMAIL_REWARD_RES
	EMAIL_DEL_REQ
	EMAIL_DEL_RES
	UPDATE_MONEY
	EMAIL_NEW
	BROADCAST_MSG
	UPDATE_ROOMLIST
	ENTER_GAME_HB_REQ
	HONGBAO
	ENTER_GAME_HB_RES
	LEAVE_GAME_HB_REQ
	LEAVE_GAME_HB_RES
	ASSIGN_HB_REQ
	ASSIGN_HB_RES
	BROADCAST_NEW_HB
	GRAB_HB_REQ
	GRAB_HB_RES
	BROADCAST_UPDATE_HB
	PLAYERS_HB_LIST_RES
	ENTER_GAME_JPM_REQ
	ENTER_GAME_JPM_RES
	LEAVE_GAME_JPM_REQ
	LEAVE_GAME_JPM_RES
	START_JPM_REQ
	START_JPM_RES
	JPMPosition
	JPM_Result
	UPDATE_JPM_BONUS
	PLAYERS_JPM_LIST_RES
	ENTER_GAME_LHD_REQ
	ENTER_GAME_LHD_RES
	LEAVE_GAME_LHD_REQ
	LEAVE_GAME_LHD_RES
	SWITCH_GAME_STATUS_BROADCAST_LHD
	StatusMsgLHD
	Status_Wait_LHD
	Status_Bet_LHD
	Status_Stop_LHD
	Status_Settle_LHD
	BET_LHD_REQ
	BET_LHD_RES
	CLEAN_BET_LHD_REQ
	CLEAN_BET_LHD_RES
	PLAYERS_LHD_LIST_RES
	ENTER_GAME_LUCKFRUIT_REQ
	ENTER_GAME_LUCKFRUIT_RES
	LEAVE_GAME_LUCKFRUIT_REQ
	LEAVE_GAME_LUCKFRUIT_RES
	START_LUCKFRUIT_REQ
	START_LUCKFRUIT_RES
	LUCKFRUITPosition
	LUCKFRUIT_Result
	UPDATE_LUCKFRUIT_BONUS
	PLAYERS_LUCKFRUIT_LIST_RES
	ENTER_GAME_RED2BLACK_REQ
	ENTER_GAME_RED2BLACK_RES
	LEAVE_GAME_RED2BLACK_REQ
	LEAVE_GAME_RED2BLACK_RES
	SWITCH_GAME_STATUS_BROADCAST
	StatusMsg
	Status_Wait
	Status_Bet
	Status_Stop
	Status_Settle
	BET_RED2BLACK_REQ
	BET_RED2BLACK_RES
	CLEAN_BET_RED2BLACK_REQ
	CLEAN_BET_RED2BLACK_RES
	PLAYERS_RED2BLACK_LIST_RES
*/
package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 网络消息
type S777MSG int32

const (
	S777MSG_UNKNOW_S777              S777MSG = 0
	S777MSG_CS_ENTER_GAME_S777_REQ   S777MSG = 18001
	S777MSG_SC_ENTER_GAME_S777_RES   S777MSG = 18002
	S777MSG_CS_LEAVE_GAME_S777_REQ   S777MSG = 18003
	S777MSG_SC_LEAVE_GAME_S777_RES   S777MSG = 18004
	S777MSG_CS_START_S777_REQ        S777MSG = 18008
	S777MSG_SC_START_S777_RES        S777MSG = 18009
	S777MSG_SC_UPDATE_S777_BONUS     S777MSG = 18010
	S777MSG_CS_PLAYERS_S777_LIST_REQ S777MSG = 18015
	S777MSG_SC_PLAYERS_S777_LIST_RES S777MSG = 18016
)

var S777MSG_name = map[int32]string{
	0:     "UNKNOW_S777",
	18001: "CS_ENTER_GAME_S777_REQ",
	18002: "SC_ENTER_GAME_S777_RES",
	18003: "CS_LEAVE_GAME_S777_REQ",
	18004: "SC_LEAVE_GAME_S777_RES",
	18008: "CS_START_S777_REQ",
	18009: "SC_START_S777_RES",
	18010: "SC_UPDATE_S777_BONUS",
	18015: "CS_PLAYERS_S777_LIST_REQ",
	18016: "SC_PLAYERS_S777_LIST_RES",
}
var S777MSG_value = map[string]int32{
	"UNKNOW_S777":              0,
	"CS_ENTER_GAME_S777_REQ":   18001,
	"SC_ENTER_GAME_S777_RES":   18002,
	"CS_LEAVE_GAME_S777_REQ":   18003,
	"SC_LEAVE_GAME_S777_RES":   18004,
	"CS_START_S777_REQ":        18008,
	"SC_START_S777_RES":        18009,
	"SC_UPDATE_S777_BONUS":     18010,
	"CS_PLAYERS_S777_LIST_REQ": 18015,
	"SC_PLAYERS_S777_LIST_RES": 18016,
}

func (x S777MSG) String() string {
	return proto.EnumName(S777MSG_name, int32(x))
}
func (S777MSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 1-3槽 图案枚举
type S777ID int32

const (
	S777ID_S777Unknow S777ID = 0
	S777ID_S7771      S777ID = 1
	S777ID_S7772      S777ID = 2
	S777ID_S7773      S777ID = 3
	S777ID_S7774      S777ID = 4
	S777ID_S7775      S777ID = 5
	S777ID_S7776      S777ID = 6
	S777ID_S7777      S777ID = 7
)

var S777ID_name = map[int32]string{
	0: "S777Unknow",
	1: "S7771",
	2: "S7772",
	3: "S7773",
	4: "S7774",
	5: "S7775",
	6: "S7776",
	7: "S7777",
}
var S777ID_value = map[string]int32{
	"S777Unknow": 0,
	"S7771":      1,
	"S7772":      2,
	"S7773":      3,
	"S7774":      4,
	"S7775":      5,
	"S7776":      6,
	"S7777":      7,
}

func (x S777ID) String() string {
	return proto.EnumName(S777ID_name, int32(x))
}
func (S777ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 4槽 图案枚举
type JackPotID int32

const (
	JackPotID_JackPotUnknow JackPotID = 0
	JackPotID_JackPot1      JackPotID = 1
	JackPotID_JackPot2      JackPotID = 2
	JackPotID_JackPot3      JackPotID = 3
	JackPotID_JackPot4      JackPotID = 4
	JackPotID_JackPot5      JackPotID = 5
	JackPotID_JackPot6      JackPotID = 6
)

var JackPotID_name = map[int32]string{
	0: "JackPotUnknow",
	1: "JackPot1",
	2: "JackPot2",
	3: "JackPot3",
	4: "JackPot4",
	5: "JackPot5",
	6: "JackPot6",
}
var JackPotID_value = map[string]int32{
	"JackPotUnknow": 0,
	"JackPot1":      1,
	"JackPot2":      2,
	"JackPot3":      3,
	"JackPot4":      4,
	"JackPot5":      5,
	"JackPot6":      6,
}

func (x JackPotID) String() string {
	return proto.EnumName(JackPotID_name, int32(x))
}
func (JackPotID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 请求进入房间
type ENTER_GAME_S777_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *ENTER_GAME_S777_REQ) Reset()                    { *m = ENTER_GAME_S777_REQ{} }
func (m *ENTER_GAME_S777_REQ) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_S777_REQ) ProtoMessage()               {}
func (*ENTER_GAME_S777_REQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ENTER_GAME_S777_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *ENTER_GAME_S777_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type ENTER_GAME_S777_RES struct {
	RoomID  uint32          `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	Basics  map[int32]int64 `protobuf:"bytes,2,rep,name=Basics" json:"Basics,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Bonus   map[int32]int64 `protobuf:"bytes,3,rep,name=Bonus" json:"Bonus,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastBet int64           `protobuf:"varint,4,opt,name=LastBet" json:"LastBet,omitempty"`
	Bets    []uint64        `protobuf:"varint,5,rep,packed,name=Bets" json:"Bets,omitempty"`
}

func (m *ENTER_GAME_S777_RES) Reset()                    { *m = ENTER_GAME_S777_RES{} }
func (m *ENTER_GAME_S777_RES) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_S777_RES) ProtoMessage()               {}
func (*ENTER_GAME_S777_RES) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ENTER_GAME_S777_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ENTER_GAME_S777_RES) GetBasics() map[int32]int64 {
	if m != nil {
		return m.Basics
	}
	return nil
}

func (m *ENTER_GAME_S777_RES) GetBonus() map[int32]int64 {
	if m != nil {
		return m.Bonus
	}
	return nil
}

func (m *ENTER_GAME_S777_RES) GetLastBet() int64 {
	if m != nil {
		return m.LastBet
	}
	return 0
}

func (m *ENTER_GAME_S777_RES) GetBets() []uint64 {
	if m != nil {
		return m.Bets
	}
	return nil
}

// 请求退出房间
type LEAVE_GAME_S777_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *LEAVE_GAME_S777_REQ) Reset()                    { *m = LEAVE_GAME_S777_REQ{} }
func (m *LEAVE_GAME_S777_REQ) String() string            { return proto.CompactTextString(m) }
func (*LEAVE_GAME_S777_REQ) ProtoMessage()               {}
func (*LEAVE_GAME_S777_REQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LEAVE_GAME_S777_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *LEAVE_GAME_S777_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type LEAVE_GAME_S777_RES struct {
	Ret    uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	RoomID uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *LEAVE_GAME_S777_RES) Reset()                    { *m = LEAVE_GAME_S777_RES{} }
func (m *LEAVE_GAME_S777_RES) String() string            { return proto.CompactTextString(m) }
func (*LEAVE_GAME_S777_RES) ProtoMessage()               {}
func (*LEAVE_GAME_S777_RES) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LEAVE_GAME_S777_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LEAVE_GAME_S777_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// //////////////////////////////////////////// 游戏 /////////////////////////////////////////////
// 请求开始游戏1
type START_S777_REQ struct {
	Bet uint64 `protobuf:"varint,1,opt,name=Bet" json:"Bet,omitempty"`
}

func (m *START_S777_REQ) Reset()                    { *m = START_S777_REQ{} }
func (m *START_S777_REQ) String() string            { return proto.CompactTextString(m) }
func (*START_S777_REQ) ProtoMessage()               {}
func (*START_S777_REQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *START_S777_REQ) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

type START_S777_RES struct {
	Ret         uint64          `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	PictureList []int32         `protobuf:"varint,2,rep,packed,name=PictureList" json:"PictureList,omitempty"`
	Bonus       map[int32]int64 `protobuf:"bytes,3,rep,name=Bonus" json:"Bonus,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Money       int64           `protobuf:"varint,4,opt,name=Money" json:"Money,omitempty"`
	TotalOdds   int64           `protobuf:"varint,5,opt,name=TotalOdds" json:"TotalOdds,omitempty"`
	Id          JackPotID       `protobuf:"varint,7,opt,name=id,enum=protomsg.JackPotID" json:"id,omitempty"`
}

func (m *START_S777_RES) Reset()                    { *m = START_S777_RES{} }
func (m *START_S777_RES) String() string            { return proto.CompactTextString(m) }
func (*START_S777_RES) ProtoMessage()               {}
func (*START_S777_RES) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *START_S777_RES) GetRet() uint64 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *START_S777_RES) GetPictureList() []int32 {
	if m != nil {
		return m.PictureList
	}
	return nil
}

func (m *START_S777_RES) GetBonus() map[int32]int64 {
	if m != nil {
		return m.Bonus
	}
	return nil
}

func (m *START_S777_RES) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *START_S777_RES) GetTotalOdds() int64 {
	if m != nil {
		return m.TotalOdds
	}
	return 0
}

func (m *START_S777_RES) GetId() JackPotID {
	if m != nil {
		return m.Id
	}
	return JackPotID_JackPotUnknow
}

type S777Position struct {
	Px int32 `protobuf:"varint,1,opt,name=px" json:"px,omitempty"`
	Py int32 `protobuf:"varint,2,opt,name=py" json:"py,omitempty"`
}

func (m *S777Position) Reset()                    { *m = S777Position{} }
func (m *S777Position) String() string            { return proto.CompactTextString(m) }
func (*S777Position) ProtoMessage()               {}
func (*S777Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *S777Position) GetPx() int32 {
	if m != nil {
		return m.Px
	}
	return 0
}

func (m *S777Position) GetPy() int32 {
	if m != nil {
		return m.Py
	}
	return 0
}

// 通知更新奖金池
type UPDATE_S777_BONUS struct {
	Bonus map[int32]int64 `protobuf:"bytes,1,rep,name=Bonus" json:"Bonus,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *UPDATE_S777_BONUS) Reset()                    { *m = UPDATE_S777_BONUS{} }
func (m *UPDATE_S777_BONUS) String() string            { return proto.CompactTextString(m) }
func (*UPDATE_S777_BONUS) ProtoMessage()               {}
func (*UPDATE_S777_BONUS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UPDATE_S777_BONUS) GetBonus() map[int32]int64 {
	if m != nil {
		return m.Bonus
	}
	return nil
}

// 请求S777玩家列表
type PLAYERS_S777_LIST_RES struct {
	Players []*AccountStorageData `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
}

func (m *PLAYERS_S777_LIST_RES) Reset()                    { *m = PLAYERS_S777_LIST_RES{} }
func (m *PLAYERS_S777_LIST_RES) String() string            { return proto.CompactTextString(m) }
func (*PLAYERS_S777_LIST_RES) ProtoMessage()               {}
func (*PLAYERS_S777_LIST_RES) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PLAYERS_S777_LIST_RES) GetPlayers() []*AccountStorageData {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterType((*ENTER_GAME_S777_REQ)(nil), "protomsg.ENTER_GAME_S777_REQ")
	proto.RegisterType((*ENTER_GAME_S777_RES)(nil), "protomsg.ENTER_GAME_S777_RES")
	proto.RegisterType((*LEAVE_GAME_S777_REQ)(nil), "protomsg.LEAVE_GAME_S777_REQ")
	proto.RegisterType((*LEAVE_GAME_S777_RES)(nil), "protomsg.LEAVE_GAME_S777_RES")
	proto.RegisterType((*START_S777_REQ)(nil), "protomsg.START_S777_REQ")
	proto.RegisterType((*START_S777_RES)(nil), "protomsg.START_S777_RES")
	proto.RegisterType((*S777Position)(nil), "protomsg.S777_position")
	proto.RegisterType((*UPDATE_S777_BONUS)(nil), "protomsg.UPDATE_S777_BONUS")
	proto.RegisterType((*PLAYERS_S777_LIST_RES)(nil), "protomsg.PLAYERS_S777_LIST_RES")
	proto.RegisterEnum("protomsg.S777MSG", S777MSG_name, S777MSG_value)
	proto.RegisterEnum("protomsg.S777ID", S777ID_name, S777ID_value)
	proto.RegisterEnum("protomsg.JackPotID", JackPotID_name, JackPotID_value)
}

func init() { proto.RegisterFile("protobuf/777.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x61, 0x6f, 0xd2, 0x5c,
	0x14, 0x5e, 0x5b, 0x0a, 0xdb, 0xe1, 0x85, 0xdd, 0xdd, 0xed, 0xdd, 0xdb, 0x90, 0xe5, 0x0d, 0x61,
	0x89, 0xc1, 0x7d, 0x60, 0x71, 0xd3, 0xb1, 0x19, 0xa3, 0x81, 0xd2, 0x2c, 0x38, 0x06, 0xec, 0x5e,
	0xd0, 0xe8, 0x97, 0xa6, 0x83, 0xba, 0x90, 0x6d, 0x94, 0xd0, 0x8b, 0x8e, 0xdf, 0x20, 0x9f, 0xfc,
	0x05, 0xfe, 0x25, 0x9d, 0x1f, 0xd4, 0x2f, 0xfa, 0x53, 0xcc, 0xbd, 0x6d, 0x29, 0xb8, 0x1a, 0x63,
	0xe6, 0xa7, 0x3d, 0xcf, 0x3d, 0xe7, 0x3c, 0xcf, 0xd9, 0x39, 0xa7, 0x00, 0x1e, 0x0c, 0x1d, 0xe6,
	0x9c, 0x8e, 0x5e, 0x6d, 0x17, 0x8b, 0xc5, 0x82, 0x20, 0x78, 0x51, 0xfc, 0xb9, 0x74, 0xcf, 0x32,
	0xab, 0xd3, 0x68, 0xd7, 0x62, 0x96, 0x17, 0xce, 0x1d, 0xc1, 0xaa, 0x51, 0x6f, 0x19, 0xc4, 0x3c,
	0x2c, 0x1d, 0x1b, 0x26, 0x2d, 0x16, 0x8b, 0x26, 0x31, 0x4e, 0xf0, 0x06, 0x2c, 0x95, 0x3a, 0x1d,
	0x67, 0xd4, 0x67, 0xd5, 0x8a, 0x26, 0x65, 0xa5, 0x7c, 0x8a, 0x84, 0x0f, 0x78, 0x1d, 0xe2, 0xc4,
	0x71, 0x2e, 0xab, 0x15, 0x4d, 0x16, 0x21, 0x9f, 0xe5, 0xae, 0xe5, 0x28, 0x35, 0x3a, 0x93, 0x2f,
	0xcd, 0xe6, 0xe3, 0x12, 0xc4, 0xcb, 0x96, 0xdb, 0xeb, 0xb8, 0x9a, 0x9c, 0x55, 0xf2, 0xc9, 0x9d,
	0xbb, 0x85, 0xa0, 0xd9, 0x42, 0x84, 0x4c, 0xc1, 0xcb, 0x35, 0xfa, 0x6c, 0x38, 0x26, 0x7e, 0x21,
	0x7e, 0x0c, 0x6a, 0xd9, 0xe9, 0x8f, 0x5c, 0x4d, 0x11, 0x0a, 0xf9, 0xdf, 0x28, 0xf0, 0x54, 0x4f,
	0xc0, 0x2b, 0xc3, 0x1a, 0x24, 0x6a, 0x96, 0xcb, 0xca, 0x36, 0xd3, 0x62, 0x59, 0x29, 0xaf, 0x90,
	0x80, 0x62, 0x0c, 0xb1, 0xb2, 0xcd, 0x5c, 0x4d, 0xcd, 0x2a, 0xf9, 0x18, 0x11, 0x38, 0x73, 0x00,
	0xc9, 0x99, 0x26, 0x30, 0x02, 0xe5, 0xdc, 0x1e, 0x8b, 0x7f, 0x4a, 0x25, 0x1c, 0xe2, 0x35, 0x50,
	0x5f, 0x5b, 0x17, 0x23, 0x5b, 0x0c, 0x46, 0x21, 0x1e, 0x79, 0x28, 0xef, 0x4b, 0x99, 0x7d, 0x80,
	0xd0, 0xfd, 0x4f, 0x2a, 0xf9, 0x8a, 0x6a, 0x46, 0xe9, 0x99, 0xf1, 0x57, 0x56, 0xf4, 0x24, 0x4a,
	0x8c, 0xf2, 0x7e, 0x88, 0xcd, 0x7c, 0x19, 0x0e, 0x7f, 0x29, 0x90, 0x83, 0x34, 0x6d, 0x95, 0x48,
	0x2b, 0x6c, 0x04, 0x81, 0x52, 0xf6, 0x6b, 0x63, 0x84, 0xc3, 0xdc, 0x3b, 0xf9, 0xa7, 0xa4, 0x39,
	0x83, 0x98, 0x67, 0x90, 0x85, 0x64, 0xb3, 0xd7, 0x61, 0xa3, 0xa1, 0x5d, 0xeb, 0xb9, 0x4c, 0x5c,
	0x80, 0x4a, 0x66, 0x9f, 0xf0, 0xc1, 0xfc, 0x6e, 0x37, 0xc3, 0xdd, 0xce, 0x8b, 0x47, 0xac, 0x75,
	0x0d, 0xd4, 0x63, 0xa7, 0x6f, 0x8f, 0xfd, 0xa5, 0x7a, 0x84, 0x8f, 0xac, 0xe5, 0x30, 0xeb, 0xa2,
	0xd1, 0xed, 0xf2, 0xbd, 0xf2, 0x48, 0xf8, 0x80, 0x37, 0x41, 0xee, 0x75, 0xb5, 0x44, 0x56, 0xca,
	0xa7, 0x77, 0x56, 0x43, 0xaf, 0xa7, 0x56, 0xe7, 0xbc, 0xe9, 0xb0, 0x6a, 0x85, 0xc8, 0xbd, 0xee,
	0x2d, 0xd6, 0xb8, 0x0d, 0x29, 0xd1, 0xf0, 0xc0, 0x71, 0x7b, 0xac, 0xe7, 0xf4, 0x71, 0x1a, 0xe4,
	0xc1, 0x95, 0x5f, 0x2b, 0x0f, 0xae, 0x04, 0x1f, 0x8b, 0x3a, 0xce, 0xc7, 0xb9, 0xb7, 0x12, 0xac,
	0xb4, 0x9b, 0x95, 0x52, 0xcb, 0xdf, 0x53, 0xb9, 0x51, 0x6f, 0x53, 0xfc, 0x28, 0x18, 0x8a, 0x24,
	0x86, 0x72, 0x27, 0x6c, 0xf4, 0x46, 0xee, 0xcd, 0xb9, 0xdc, 0xa2, 0xfd, 0x06, 0xfc, 0xdb, 0xac,
	0x95, 0x5e, 0x18, 0x84, 0x7a, 0x0e, 0xb5, 0x2a, 0x6d, 0x89, 0xcd, 0xee, 0x41, 0x62, 0x70, 0x61,
	0x8d, 0xed, 0x61, 0xd0, 0xd2, 0x46, 0xd8, 0x92, 0x7f, 0x8f, 0x94, 0x39, 0x43, 0xeb, 0xcc, 0xae,
	0x58, 0xcc, 0x22, 0x41, 0xf2, 0xd6, 0x7b, 0x19, 0x12, 0x5c, 0xe9, 0x98, 0x1e, 0xe2, 0x65, 0x48,
	0xb6, 0xeb, 0x47, 0xf5, 0xc6, 0x73, 0xa1, 0x8d, 0x16, 0xf0, 0x06, 0xac, 0xeb, 0xd4, 0x8c, 0xf8,
	0x65, 0x42, 0x1f, 0x26, 0x12, 0x8f, 0x52, 0x3d, 0x22, 0x4a, 0xd1, 0x47, 0x2f, 0xaa, 0x53, 0x33,
	0xe2, 0x93, 0x41, 0xd7, 0xd3, 0xda, 0x88, 0x6f, 0x00, 0x7d, 0x9a, 0x48, 0xf8, 0x3f, 0x58, 0xd1,
	0xa9, 0x39, 0x7f, 0xe0, 0xe8, 0xb3, 0x17, 0xa0, 0xfa, 0x7c, 0x80, 0xa2, 0x2f, 0x13, 0x09, 0x67,
	0x60, 0x8d, 0xea, 0xe6, 0x8d, 0xd9, 0xa3, 0xaf, 0x13, 0x09, 0xff, 0x0f, 0x9a, 0x4e, 0xcd, 0xa8,
	0xb1, 0x9d, 0xa0, 0x6f, 0x5e, 0x9c, 0xea, 0x91, 0x71, 0x8a, 0xbe, 0x4f, 0xa4, 0x2d, 0x1b, 0xe2,
	0xfc, 0xb1, 0x5a, 0xc1, 0x69, 0x00, 0x8e, 0xda, 0xfd, 0xf3, 0xbe, 0xf3, 0x06, 0x2d, 0xe0, 0x25,
	0x50, 0x39, 0xbf, 0x87, 0xa4, 0x00, 0xee, 0x20, 0x39, 0x80, 0xbb, 0x48, 0x09, 0xe0, 0x7d, 0x14,
	0x0b, 0xe0, 0x03, 0xa4, 0x06, 0x70, 0x0f, 0xc5, 0x03, 0x58, 0x44, 0x89, 0xad, 0x21, 0x2c, 0x4d,
	0x8f, 0x1c, 0xaf, 0x40, 0xca, 0x27, 0x53, 0xb3, 0x7f, 0x60, 0xd1, 0x7f, 0xe2, 0x7e, 0x21, 0xe3,
	0x96, 0x21, 0xe3, 0xae, 0x21, 0xe3, 0xc6, 0x21, 0xe3, 0xde, 0x21, 0xdb, 0x43, 0xf1, 0xf2, 0xf2,
	0xcb, 0xd4, 0xd0, 0x71, 0xd8, 0x76, 0x70, 0x2a, 0xa7, 0x71, 0x81, 0x76, 0x7f, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x80, 0xaa, 0x68, 0xc4, 0x06, 0x00, 0x00,
}
