// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protobuf/777.proto

package protomsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 网络消息
type S777MSG int32

const (
	S777MSG_UNKNOW_S777              S777MSG = 0
	S777MSG_CS_ENTER_GAME_S777_REQ   S777MSG = 18001 // 玩家请求进入房间
	S777MSG_SC_ENTER_GAME_S777_RES   S777MSG = 18002
	S777MSG_CS_LEAVE_GAME_S777_REQ   S777MSG = 18003 // 玩家请求退出房间
	S777MSG_SC_LEAVE_GAME_S777_RES   S777MSG = 18004
	S777MSG_CS_START_S777_REQ        S777MSG = 18008 // 请求开始游戏1
	S777MSG_SC_START_S777_RES        S777MSG = 18009
	S777MSG_SC_UPDATE_S777_BONUS     S777MSG = 18010 // 通知更新奖金池
	S777MSG_CS_PLAYERS_S777_LIST_REQ S777MSG = 18015 // 请求在线玩家列表
	S777MSG_SC_PLAYERS_S777_LIST_RES S777MSG = 18016
)

// Enum value maps for S777MSG.
var (
	S777MSG_name = map[int32]string{
		0:     "UNKNOW_S777",
		18001: "CS_ENTER_GAME_S777_REQ",
		18002: "SC_ENTER_GAME_S777_RES",
		18003: "CS_LEAVE_GAME_S777_REQ",
		18004: "SC_LEAVE_GAME_S777_RES",
		18008: "CS_START_S777_REQ",
		18009: "SC_START_S777_RES",
		18010: "SC_UPDATE_S777_BONUS",
		18015: "CS_PLAYERS_S777_LIST_REQ",
		18016: "SC_PLAYERS_S777_LIST_RES",
	}
	S777MSG_value = map[string]int32{
		"UNKNOW_S777":              0,
		"CS_ENTER_GAME_S777_REQ":   18001,
		"SC_ENTER_GAME_S777_RES":   18002,
		"CS_LEAVE_GAME_S777_REQ":   18003,
		"SC_LEAVE_GAME_S777_RES":   18004,
		"CS_START_S777_REQ":        18008,
		"SC_START_S777_RES":        18009,
		"SC_UPDATE_S777_BONUS":     18010,
		"CS_PLAYERS_S777_LIST_REQ": 18015,
		"SC_PLAYERS_S777_LIST_RES": 18016,
	}
)

func (x S777MSG) Enum() *S777MSG {
	p := new(S777MSG)
	*p = x
	return p
}

func (x S777MSG) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S777MSG) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_777_proto_enumTypes[0].Descriptor()
}

func (S777MSG) Type() protoreflect.EnumType {
	return &file_protobuf_777_proto_enumTypes[0]
}

func (x S777MSG) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S777MSG.Descriptor instead.
func (S777MSG) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{0}
}

// 1-3槽 图案枚举
type S777ID int32

const (
	S777ID_S777Unknow S777ID = 0
	S777ID_S7771      S777ID = 1 // 大Bar
	S777ID_S7772      S777ID = 2 // 小Bar
	S777ID_S7773      S777ID = 3 // 77
	S777ID_S7774      S777ID = 4 // 西瓜
	S777ID_S7775      S777ID = 5 // 芒果
	S777ID_S7776      S777ID = 6 // 橘子
	S777ID_S7777      S777ID = 7 // 苹果
)

// Enum value maps for S777ID.
var (
	S777ID_name = map[int32]string{
		0: "S777Unknow",
		1: "S7771",
		2: "S7772",
		3: "S7773",
		4: "S7774",
		5: "S7775",
		6: "S7776",
		7: "S7777",
	}
	S777ID_value = map[string]int32{
		"S777Unknow": 0,
		"S7771":      1,
		"S7772":      2,
		"S7773":      3,
		"S7774":      4,
		"S7775":      5,
		"S7776":      6,
		"S7777":      7,
	}
)

func (x S777ID) Enum() *S777ID {
	p := new(S777ID)
	*p = x
	return p
}

func (x S777ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S777ID) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_777_proto_enumTypes[1].Descriptor()
}

func (S777ID) Type() protoreflect.EnumType {
	return &file_protobuf_777_proto_enumTypes[1]
}

func (x S777ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S777ID.Descriptor instead.
func (S777ID) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{1}
}

// 4槽 图案枚举
type JackPotID int32

const (
	JackPotID_JackPotUnknow JackPotID = 0
	JackPotID_JackPot1      JackPotID = 1 //Jackpot
	JackPotID_JackPot2      JackPotID = 2 //X1
	JackPotID_JackPot3      JackPotID = 3 //X2
	JackPotID_JackPot4      JackPotID = 4 //X4
	JackPotID_JackPot5      JackPotID = 5 //X10
	JackPotID_JackPot6      JackPotID = 6 //X25
)

// Enum value maps for JackPotID.
var (
	JackPotID_name = map[int32]string{
		0: "JackPotUnknow",
		1: "JackPot1",
		2: "JackPot2",
		3: "JackPot3",
		4: "JackPot4",
		5: "JackPot5",
		6: "JackPot6",
	}
	JackPotID_value = map[string]int32{
		"JackPotUnknow": 0,
		"JackPot1":      1,
		"JackPot2":      2,
		"JackPot3":      3,
		"JackPot4":      4,
		"JackPot5":      5,
		"JackPot6":      6,
	}
)

func (x JackPotID) Enum() *JackPotID {
	p := new(JackPotID)
	*p = x
	return p
}

func (x JackPotID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JackPotID) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_777_proto_enumTypes[2].Descriptor()
}

func (JackPotID) Type() protoreflect.EnumType {
	return &file_protobuf_777_proto_enumTypes[2]
}

func (x JackPotID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JackPotID.Descriptor instead.
func (JackPotID) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{2}
}

// 请求进入房间
type ENTER_GAME_S777_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"` //
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`       // 房间ID
}

func (x *ENTER_GAME_S777_REQ) Reset() {
	*x = ENTER_GAME_S777_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ENTER_GAME_S777_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ENTER_GAME_S777_REQ) ProtoMessage() {}

func (x *ENTER_GAME_S777_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ENTER_GAME_S777_REQ.ProtoReflect.Descriptor instead.
func (*ENTER_GAME_S777_REQ) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{0}
}

func (x *ENTER_GAME_S777_REQ) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *ENTER_GAME_S777_REQ) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ENTER_GAME_S777_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID  uint32          `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`                                                                                          // 房间ID
	Basics  map[int32]int64 `protobuf:"bytes,2,rep,name=Basics,proto3" json:"Basics,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 基础金额
	Bonus   map[int32]int64 `protobuf:"bytes,3,rep,name=Bonus,proto3" json:"Bonus,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`   // key 等级  val 奖池
	LastBet int64           `protobuf:"varint,4,opt,name=LastBet,proto3" json:"LastBet,omitempty"`                                                                                        // 最后一次压住
	Bets    []uint64        `protobuf:"varint,5,rep,packed,name=Bets,proto3" json:"Bets,omitempty"`                                                                                       // 可以选择的押注金额
}

func (x *ENTER_GAME_S777_RES) Reset() {
	*x = ENTER_GAME_S777_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ENTER_GAME_S777_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ENTER_GAME_S777_RES) ProtoMessage() {}

func (x *ENTER_GAME_S777_RES) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ENTER_GAME_S777_RES.ProtoReflect.Descriptor instead.
func (*ENTER_GAME_S777_RES) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{1}
}

func (x *ENTER_GAME_S777_RES) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *ENTER_GAME_S777_RES) GetBasics() map[int32]int64 {
	if x != nil {
		return x.Basics
	}
	return nil
}

func (x *ENTER_GAME_S777_RES) GetBonus() map[int32]int64 {
	if x != nil {
		return x.Bonus
	}
	return nil
}

func (x *ENTER_GAME_S777_RES) GetLastBet() int64 {
	if x != nil {
		return x.LastBet
	}
	return 0
}

func (x *ENTER_GAME_S777_RES) GetBets() []uint64 {
	if x != nil {
		return x.Bets
	}
	return nil
}

// 请求退出房间
type LEAVE_GAME_S777_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"` //
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`       // 房间ID
}

func (x *LEAVE_GAME_S777_REQ) Reset() {
	*x = LEAVE_GAME_S777_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LEAVE_GAME_S777_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEAVE_GAME_S777_REQ) ProtoMessage() {}

func (x *LEAVE_GAME_S777_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEAVE_GAME_S777_REQ.ProtoReflect.Descriptor instead.
func (*LEAVE_GAME_S777_REQ) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{2}
}

func (x *LEAVE_GAME_S777_REQ) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *LEAVE_GAME_S777_REQ) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type LEAVE_GAME_S777_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    uint32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`       // 0.可以退出  1.不能退出房间
	RoomID uint32 `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"` // 房间ID
}

func (x *LEAVE_GAME_S777_RES) Reset() {
	*x = LEAVE_GAME_S777_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LEAVE_GAME_S777_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LEAVE_GAME_S777_RES) ProtoMessage() {}

func (x *LEAVE_GAME_S777_RES) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LEAVE_GAME_S777_RES.ProtoReflect.Descriptor instead.
func (*LEAVE_GAME_S777_RES) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{3}
}

func (x *LEAVE_GAME_S777_RES) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *LEAVE_GAME_S777_RES) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

////////////////////////////////////////////// 游戏 /////////////////////////////////////////////
// 请求开始游戏1
type START_S777_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bet uint64 `protobuf:"varint,1,opt,name=Bet,proto3" json:"Bet,omitempty"`
}

func (x *START_S777_REQ) Reset() {
	*x = START_S777_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *START_S777_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*START_S777_REQ) ProtoMessage() {}

func (x *START_S777_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use START_S777_REQ.ProtoReflect.Descriptor instead.
func (*START_S777_REQ) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{4}
}

func (x *START_S777_REQ) GetBet() uint64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

type START_S777_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret         uint64          `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`                                                                                              // 0成功
	PictureList []int32         `protobuf:"varint,2,rep,packed,name=PictureList,proto3" json:"PictureList,omitempty"`                                                                       // 图形列表( [0-9] 即9个图形)
	Bonus       map[int32]int64 `protobuf:"bytes,3,rep,name=Bonus,proto3" json:"Bonus,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 水池盈利 (key级别 vale盈利)
	Money       int64           `protobuf:"varint,4,opt,name=Money,proto3" json:"Money,omitempty"`                                                                                          // 身上的钱
	TotalOdds   int64           `protobuf:"varint,5,opt,name=TotalOdds,proto3" json:"TotalOdds,omitempty"`                                                                                  // 总赔率
	Id          JackPotID       `protobuf:"varint,7,opt,name=id,proto3,enum=protomsg.JackPotID" json:"id,omitempty"`                                                                        // 第四个槽的id
	Reward      int32           `protobuf:"varint,8,opt,name=reward,proto3" json:"reward,omitempty"`                                                                                        // 连中数量2 或 3
}

func (x *START_S777_RES) Reset() {
	*x = START_S777_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *START_S777_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*START_S777_RES) ProtoMessage() {}

func (x *START_S777_RES) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use START_S777_RES.ProtoReflect.Descriptor instead.
func (*START_S777_RES) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{5}
}

func (x *START_S777_RES) GetRet() uint64 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *START_S777_RES) GetPictureList() []int32 {
	if x != nil {
		return x.PictureList
	}
	return nil
}

func (x *START_S777_RES) GetBonus() map[int32]int64 {
	if x != nil {
		return x.Bonus
	}
	return nil
}

func (x *START_S777_RES) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *START_S777_RES) GetTotalOdds() int64 {
	if x != nil {
		return x.TotalOdds
	}
	return 0
}

func (x *START_S777_RES) GetId() JackPotID {
	if x != nil {
		return x.Id
	}
	return JackPotID_JackPotUnknow
}

func (x *START_S777_RES) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

type S777Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Px int32 `protobuf:"varint,1,opt,name=px,proto3" json:"px,omitempty"`
	Py int32 `protobuf:"varint,2,opt,name=py,proto3" json:"py,omitempty"`
}

func (x *S777Position) Reset() {
	*x = S777Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S777Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S777Position) ProtoMessage() {}

func (x *S777Position) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S777Position.ProtoReflect.Descriptor instead.
func (*S777Position) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{6}
}

func (x *S777Position) GetPx() int32 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *S777Position) GetPy() int32 {
	if x != nil {
		return x.Py
	}
	return 0
}

// 通知更新奖金池
type UPDATE_S777_BONUS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bonus map[int32]int64 `protobuf:"bytes,1,rep,name=Bonus,proto3" json:"Bonus,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // key 等级  val 奖池
}

func (x *UPDATE_S777_BONUS) Reset() {
	*x = UPDATE_S777_BONUS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UPDATE_S777_BONUS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPDATE_S777_BONUS) ProtoMessage() {}

func (x *UPDATE_S777_BONUS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPDATE_S777_BONUS.ProtoReflect.Descriptor instead.
func (*UPDATE_S777_BONUS) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{7}
}

func (x *UPDATE_S777_BONUS) GetBonus() map[int32]int64 {
	if x != nil {
		return x.Bonus
	}
	return nil
}

// 请求S777玩家列表
type PLAYERS_S777_LIST_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*AccountStorageData `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"` // 房间所有的玩家
}

func (x *PLAYERS_S777_LIST_RES) Reset() {
	*x = PLAYERS_S777_LIST_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_777_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLAYERS_S777_LIST_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLAYERS_S777_LIST_RES) ProtoMessage() {}

func (x *PLAYERS_S777_LIST_RES) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_777_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLAYERS_S777_LIST_RES.ProtoReflect.Descriptor instead.
func (*PLAYERS_S777_LIST_RES) Descriptor() ([]byte, []int) {
	return file_protobuf_777_proto_rawDescGZIP(), []int{8}
}

func (x *PLAYERS_S777_LIST_RES) GetPlayers() []*AccountStorageData {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_protobuf_777_proto protoreflect.FileDescriptor

var file_protobuf_777_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x37, 0x37, 0x37, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x1a, 0x13,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x13, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x41, 0x4d,
	0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x22, 0xd3, 0x02, 0x0a, 0x13, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f,
	0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x12, 0x41, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x4e, 0x54, 0x45,
	0x52, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x73, 0x12, 0x3e, 0x0a, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x4e,
	0x54, 0x45, 0x52, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45,
	0x53, 0x2e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x42, 0x6f,
	0x6e, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x42, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x04, 0x52, 0x04, 0x42, 0x65, 0x74,
	0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x38, 0x0a, 0x0a,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4b, 0x0a, 0x13, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x22, 0x3f, 0x0a, 0x13, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x47, 0x41, 0x4d,
	0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x22, 0x22, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x53, 0x37,
	0x37, 0x37, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x42, 0x65, 0x74, 0x22, 0xaa, 0x02, 0x0a, 0x0e, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x39, 0x0a, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f,
	0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x2e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x64, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x23,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x4a, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74, 0x49, 0x44, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x1a, 0x38, 0x0a, 0x0a, 0x42,
	0x6f, 0x6e, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2f, 0x0a, 0x0d, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x70, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x70, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x12, 0x3c, 0x0a, 0x05,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x37,
	0x37, 0x37, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x2e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x42, 0x6f,
	0x6e, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x4f, 0x0a, 0x15, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x53, 0x5f,
	0x53, 0x37, 0x37, 0x37, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x36, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x2a, 0xa0, 0x02, 0x0a, 0x07, 0x53, 0x37, 0x37, 0x37, 0x4d, 0x53,
	0x47, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x5f, 0x53, 0x37, 0x37, 0x37,
	0x10, 0x00, 0x12, 0x1c, 0x0a, 0x16, 0x43, 0x53, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x51, 0x10, 0xd1, 0x8c, 0x01,
	0x12, 0x1c, 0x0a, 0x16, 0x53, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x47, 0x41, 0x4d,
	0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x10, 0xd2, 0x8c, 0x01, 0x12, 0x1c,
	0x0a, 0x16, 0x43, 0x53, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f,
	0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x51, 0x10, 0xd3, 0x8c, 0x01, 0x12, 0x1c, 0x0a, 0x16,
	0x53, 0x43, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x37,
	0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x10, 0xd4, 0x8c, 0x01, 0x12, 0x17, 0x0a, 0x11, 0x43, 0x53,
	0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x51, 0x10,
	0xd8, 0x8c, 0x01, 0x12, 0x17, 0x0a, 0x11, 0x53, 0x43, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f,
	0x53, 0x37, 0x37, 0x37, 0x5f, 0x52, 0x45, 0x53, 0x10, 0xd9, 0x8c, 0x01, 0x12, 0x1a, 0x0a, 0x14,
	0x53, 0x43, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x42,
	0x4f, 0x4e, 0x55, 0x53, 0x10, 0xda, 0x8c, 0x01, 0x12, 0x1e, 0x0a, 0x18, 0x43, 0x53, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x53, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x5f, 0x52, 0x45, 0x51, 0x10, 0xdf, 0x8c, 0x01, 0x12, 0x1e, 0x0a, 0x18, 0x53, 0x43, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x53, 0x5f, 0x53, 0x37, 0x37, 0x37, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x5f, 0x52, 0x45, 0x53, 0x10, 0xe0, 0x8c, 0x01, 0x2a, 0x65, 0x0a, 0x06, 0x53, 0x37, 0x37, 0x37,
	0x49, 0x44, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x37, 0x37, 0x37, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x37, 0x37, 0x37, 0x31, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x53, 0x37, 0x37, 0x37, 0x32, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x37, 0x37, 0x37,
	0x33, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x37, 0x37, 0x37, 0x34, 0x10, 0x04, 0x12, 0x09,
	0x0a, 0x05, 0x53, 0x37, 0x37, 0x37, 0x35, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x37, 0x37,
	0x37, 0x36, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x37, 0x37, 0x37, 0x37, 0x10, 0x07, 0x2a,
	0x72, 0x0a, 0x09, 0x4a, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d,
	0x4a, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x4a, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74, 0x31, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x4a, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74, 0x32, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4a,
	0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74, 0x33, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x61, 0x63,
	0x6b, 0x50, 0x6f, 0x74, 0x34, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x61, 0x63, 0x6b, 0x50,
	0x6f, 0x74, 0x35, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x74,
	0x36, 0x10, 0x06, 0x42, 0x0f, 0x5a, 0x0d, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_777_proto_rawDescOnce sync.Once
	file_protobuf_777_proto_rawDescData = file_protobuf_777_proto_rawDesc
)

func file_protobuf_777_proto_rawDescGZIP() []byte {
	file_protobuf_777_proto_rawDescOnce.Do(func() {
		file_protobuf_777_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_777_proto_rawDescData)
	})
	return file_protobuf_777_proto_rawDescData
}

var file_protobuf_777_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuf_777_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protobuf_777_proto_goTypes = []interface{}{
	(S777MSG)(0),                  // 0: protomsg.S777MSG
	(S777ID)(0),                   // 1: protomsg.S777ID
	(JackPotID)(0),                // 2: protomsg.JackPotID
	(*ENTER_GAME_S777_REQ)(nil),   // 3: protomsg.ENTER_GAME_S777_REQ
	(*ENTER_GAME_S777_RES)(nil),   // 4: protomsg.ENTER_GAME_S777_RES
	(*LEAVE_GAME_S777_REQ)(nil),   // 5: protomsg.LEAVE_GAME_S777_REQ
	(*LEAVE_GAME_S777_RES)(nil),   // 6: protomsg.LEAVE_GAME_S777_RES
	(*START_S777_REQ)(nil),        // 7: protomsg.START_S777_REQ
	(*START_S777_RES)(nil),        // 8: protomsg.START_S777_RES
	(*S777Position)(nil),          // 9: protomsg.S777_position
	(*UPDATE_S777_BONUS)(nil),     // 10: protomsg.UPDATE_S777_BONUS
	(*PLAYERS_S777_LIST_RES)(nil), // 11: protomsg.PLAYERS_S777_LIST_RES
	nil,                           // 12: protomsg.ENTER_GAME_S777_RES.BasicsEntry
	nil,                           // 13: protomsg.ENTER_GAME_S777_RES.BonusEntry
	nil,                           // 14: protomsg.START_S777_RES.BonusEntry
	nil,                           // 15: protomsg.UPDATE_S777_BONUS.BonusEntry
	(*AccountStorageData)(nil),    // 16: protomsg.AccountStorageData
}
var file_protobuf_777_proto_depIdxs = []int32{
	12, // 0: protomsg.ENTER_GAME_S777_RES.Basics:type_name -> protomsg.ENTER_GAME_S777_RES.BasicsEntry
	13, // 1: protomsg.ENTER_GAME_S777_RES.Bonus:type_name -> protomsg.ENTER_GAME_S777_RES.BonusEntry
	14, // 2: protomsg.START_S777_RES.Bonus:type_name -> protomsg.START_S777_RES.BonusEntry
	2,  // 3: protomsg.START_S777_RES.id:type_name -> protomsg.JackPotID
	15, // 4: protomsg.UPDATE_S777_BONUS.Bonus:type_name -> protomsg.UPDATE_S777_BONUS.BonusEntry
	16, // 5: protomsg.PLAYERS_S777_LIST_RES.players:type_name -> protomsg.AccountStorageData
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_777_proto_init() }
func file_protobuf_777_proto_init() {
	if File_protobuf_777_proto != nil {
		return
	}
	file_protobuf_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protobuf_777_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ENTER_GAME_S777_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ENTER_GAME_S777_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LEAVE_GAME_S777_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LEAVE_GAME_S777_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*START_S777_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*START_S777_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S777Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UPDATE_S777_BONUS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_777_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLAYERS_S777_LIST_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_777_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_777_proto_goTypes,
		DependencyIndexes: file_protobuf_777_proto_depIdxs,
		EnumInfos:         file_protobuf_777_proto_enumTypes,
		MessageInfos:      file_protobuf_777_proto_msgTypes,
	}.Build()
	File_protobuf_777_proto = out.File
	file_protobuf_777_proto_rawDesc = nil
	file_protobuf_777_proto_goTypes = nil
	file_protobuf_777_proto_depIdxs = nil
}
