// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protobuf/data.proto

package protomsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 花色
type Card_CARDCOLOR int32

const (
	Card_CARDCOLOR_Unknow Card_CARDCOLOR = 0 // 无用的
	Card_CARDCOLOR_1      Card_CARDCOLOR = 1 // 方块
	Card_CARDCOLOR_2      Card_CARDCOLOR = 2 // 梅花
	Card_CARDCOLOR_3      Card_CARDCOLOR = 3 // 红桃
	Card_CARDCOLOR_4      Card_CARDCOLOR = 4 // 黑桃
	Card_CARDCOLOR_5      Card_CARDCOLOR = 5 // 王
)

// Enum value maps for Card_CARDCOLOR.
var (
	Card_CARDCOLOR_name = map[int32]string{
		0: "CARDCOLOR_Unknow",
		1: "CARDCOLOR_1",
		2: "CARDCOLOR_2",
		3: "CARDCOLOR_3",
		4: "CARDCOLOR_4",
		5: "CARDCOLOR_5",
	}
	Card_CARDCOLOR_value = map[string]int32{
		"CARDCOLOR_Unknow": 0,
		"CARDCOLOR_1":      1,
		"CARDCOLOR_2":      2,
		"CARDCOLOR_3":      3,
		"CARDCOLOR_4":      4,
		"CARDCOLOR_5":      5,
	}
)

func (x Card_CARDCOLOR) Enum() *Card_CARDCOLOR {
	p := new(Card_CARDCOLOR)
	*p = x
	return p
}

func (x Card_CARDCOLOR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Card_CARDCOLOR) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_data_proto_enumTypes[0].Descriptor()
}

func (Card_CARDCOLOR) Type() protoreflect.EnumType {
	return &file_protobuf_data_proto_enumTypes[0]
}

func (x Card_CARDCOLOR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Card_CARDCOLOR.Descriptor instead.
func (Card_CARDCOLOR) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{5, 0}
}

// 玩家基础信息
type AccountStorageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  uint32 `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`    // 账号ID
	UnDevice   string `protobuf:"bytes,2,opt,name=UnDevice,proto3" json:"UnDevice,omitempty"`       // 设备ID
	Phone      string `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`             // 电话
	WeiXin     string `protobuf:"bytes,4,opt,name=WeiXin,proto3" json:"WeiXin,omitempty"`           // 微信
	Name       string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`               // 昵称
	HeadURL    string `protobuf:"bytes,6,opt,name=HeadURL,proto3" json:"HeadURL,omitempty"`         // 头像
	Money      uint64 `protobuf:"varint,7,opt,name=Money,proto3" json:"Money,omitempty"`            // 金币
	SafeMoney  uint64 `protobuf:"varint,8,opt,name=SafeMoney,proto3" json:"SafeMoney,omitempty"`    // 保险箱金币
	ActiveTime string `protobuf:"bytes,9,opt,name=ActiveTime,proto3" json:"ActiveTime,omitempty"`   // 激活时间
	ActiveIP   string `protobuf:"bytes,10,opt,name=ActiveIP,proto3" json:"ActiveIP,omitempty"`      // 激活IP
	FrozenTime uint64 `protobuf:"varint,11,opt,name=FrozenTime,proto3" json:"FrozenTime,omitempty"` // 冻结时间
	Salesman   int32  `protobuf:"varint,12,opt,name=Salesman,proto3" json:"Salesman,omitempty"`     // 代理身份 0非代理 1级代理 2级代理
	SalesTime  string `protobuf:"bytes,13,opt,name=SalesTime,proto3" json:"SalesTime,omitempty"`    // 成为代理的时间
	Special    uint32 `protobuf:"varint,14,opt,name=Special,proto3" json:"Special,omitempty"`       // 特殊账号
	OSType     uint32 `protobuf:"varint,15,opt,name=OSType,proto3" json:"OSType,omitempty"`         // 系统类型 1Windows, 2安卓, 3苹果
	LoginTime  int64  `protobuf:"varint,16,opt,name=LoginTime,proto3" json:"LoginTime,omitempty"`   // 登录时间
	LogoutTime int64  `protobuf:"varint,17,opt,name=LogoutTime,proto3" json:"LogoutTime,omitempty"` // 登出时间
	Robot      uint32 `protobuf:"varint,18,opt,name=Robot,proto3" json:"Robot,omitempty"`           // 是否是机器人
	Kill       int32  `protobuf:"varint,19,opt,name=Kill,proto3" json:"Kill,omitempty"`             // 玩家杀数
}

func (x *AccountStorageData) Reset() {
	*x = AccountStorageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountStorageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountStorageData) ProtoMessage() {}

func (x *AccountStorageData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountStorageData.ProtoReflect.Descriptor instead.
func (*AccountStorageData) Descriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{0}
}

func (x *AccountStorageData) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountStorageData) GetUnDevice() string {
	if x != nil {
		return x.UnDevice
	}
	return ""
}

func (x *AccountStorageData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AccountStorageData) GetWeiXin() string {
	if x != nil {
		return x.WeiXin
	}
	return ""
}

func (x *AccountStorageData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountStorageData) GetHeadURL() string {
	if x != nil {
		return x.HeadURL
	}
	return ""
}

func (x *AccountStorageData) GetMoney() uint64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *AccountStorageData) GetSafeMoney() uint64 {
	if x != nil {
		return x.SafeMoney
	}
	return 0
}

func (x *AccountStorageData) GetActiveTime() string {
	if x != nil {
		return x.ActiveTime
	}
	return ""
}

func (x *AccountStorageData) GetActiveIP() string {
	if x != nil {
		return x.ActiveIP
	}
	return ""
}

func (x *AccountStorageData) GetFrozenTime() uint64 {
	if x != nil {
		return x.FrozenTime
	}
	return 0
}

func (x *AccountStorageData) GetSalesman() int32 {
	if x != nil {
		return x.Salesman
	}
	return 0
}

func (x *AccountStorageData) GetSalesTime() string {
	if x != nil {
		return x.SalesTime
	}
	return ""
}

func (x *AccountStorageData) GetSpecial() uint32 {
	if x != nil {
		return x.Special
	}
	return 0
}

func (x *AccountStorageData) GetOSType() uint32 {
	if x != nil {
		return x.OSType
	}
	return 0
}

func (x *AccountStorageData) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *AccountStorageData) GetLogoutTime() int64 {
	if x != nil {
		return x.LogoutTime
	}
	return 0
}

func (x *AccountStorageData) GetRobot() uint32 {
	if x != nil {
		return x.Robot
	}
	return 0
}

func (x *AccountStorageData) GetKill() int32 {
	if x != nil {
		return x.Kill
	}
	return 0
}

// 玩家游戏信息
type AccountGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint32 `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"` // 玩家所在房间ID
}

func (x *AccountGameData) Reset() {
	*x = AccountGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountGameData) ProtoMessage() {}

func (x *AccountGameData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountGameData.ProtoReflect.Descriptor instead.
func (*AccountGameData) Descriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{1}
}

func (x *AccountGameData) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailID   uint32 `protobuf:"varint,1,opt,name=EmailID,proto3" json:"EmailID,omitempty"`     // ID
	EmailType uint32 `protobuf:"varint,2,opt,name=EmailType,proto3" json:"EmailType,omitempty"` // 邮件类型
	Content   string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`      // 邮件内容
	Money     uint64 `protobuf:"varint,4,opt,name=Money,proto3" json:"Money,omitempty"`         // 附带金币
	SendTime  int64  `protobuf:"varint,5,opt,name=SendTime,proto3" json:"SendTime,omitempty"`   // 发送时间
	IsRead    uint32 `protobuf:"varint,6,opt,name=IsRead,proto3" json:"IsRead,omitempty"`       // 0 未读，1 已读取
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{2}
}

func (x *Email) GetEmailID() uint32 {
	if x != nil {
		return x.EmailID
	}
	return 0
}

func (x *Email) GetEmailType() uint32 {
	if x != nil {
		return x.EmailType
	}
	return 0
}

func (x *Email) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Email) GetMoney() uint64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Email) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Email) GetIsRead() uint32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID   uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	MinMoney uint64   `protobuf:"varint,2,opt,name=MinMoney,proto3" json:"MinMoney,omitempty"` // 最低金币
	Bets     []uint64 `protobuf:"varint,3,rep,packed,name=Bets,proto3" json:"Bets,omitempty"`  // 可选押注值
	Type     uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`         // 房间游戏类型(1.初级 2.中级 3.高级)
	Order    uint32   `protobuf:"varint,5,opt,name=Order,proto3" json:"Order,omitempty"`       // 房间序列123
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{3}
}

func (x *RoomInfo) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *RoomInfo) GetMinMoney() uint64 {
	if x != nil {
		return x.MinMoney
	}
	return 0
}

func (x *RoomInfo) GetBets() []uint64 {
	if x != nil {
		return x.Bets
	}
	return nil
}

func (x *RoomInfo) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RoomInfo) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType uint32      `protobuf:"varint,1,opt,name=GameType,proto3" json:"GameType,omitempty"`
	Rooms    []*RoomInfo `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{4}
}

func (x *GameInfo) GetGameType() uint32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *GameInfo) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 牌信息
type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32          `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`                            // 点数  1-13
	Color  Card_CARDCOLOR `protobuf:"varint,2,opt,name=Color,proto3,enum=protomsg.Card_CARDCOLOR" json:"Color,omitempty"` // 花色
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_protobuf_data_proto_rawDescGZIP(), []int{5}
}

func (x *Card) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Card) GetColor() Card_CARDCOLOR {
	if x != nil {
		return x.Color
	}
	return Card_CARDCOLOR_Unknow
}

var File_protobuf_data_proto protoreflect.FileDescriptor

var file_protobuf_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x22,
	0x8e, 0x04, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x58, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x65, 0x69, 0x58, 0x69, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x61, 0x66, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x61, 0x66, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x50, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x50, 0x12, 0x1e, 0x0a, 0x0a,
	0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x61, 0x6c, 0x65, 0x73, 0x6d, 0x61, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x53, 0x61, 0x6c, 0x65, 0x73, 0x6d, 0x61, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x61, 0x6c, 0x65,
	0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x61, 0x6c,
	0x65, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61,
	0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x4f, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4b, 0x69, 0x6c, 0x6c, 0x18, 0x13, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4b, 0x69, 0x6c, 0x6c,
	0x22, 0x29, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0xa3, 0x01, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x52,
	0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61,
	0x64, 0x22, 0x7c, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4d, 0x69, 0x6e, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x04, 0x42, 0x65, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0x50, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x47,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x47,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73,
	0x67, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d,
	0x73, 0x22, 0xc6, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x2e, 0x43, 0x41, 0x52, 0x44, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x52, 0x05, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x22, 0x76, 0x0a, 0x09, 0x43, 0x41, 0x52, 0x44, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x12,
	0x14, 0x0a, 0x10, 0x43, 0x41, 0x52, 0x44, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x52, 0x44, 0x43, 0x4f, 0x4c,
	0x4f, 0x52, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x52, 0x44, 0x43, 0x4f,
	0x4c, 0x4f, 0x52, 0x5f, 0x32, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x52, 0x44, 0x43,
	0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x33, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x52, 0x44,
	0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x34, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x52,
	0x44, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x35, 0x10, 0x05, 0x42, 0x0f, 0x5a, 0x0d, 0x72, 0x6f,
	0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_data_proto_rawDescOnce sync.Once
	file_protobuf_data_proto_rawDescData = file_protobuf_data_proto_rawDesc
)

func file_protobuf_data_proto_rawDescGZIP() []byte {
	file_protobuf_data_proto_rawDescOnce.Do(func() {
		file_protobuf_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_data_proto_rawDescData)
	})
	return file_protobuf_data_proto_rawDescData
}

var file_protobuf_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_data_proto_goTypes = []interface{}{
	(Card_CARDCOLOR)(0),        // 0: protomsg.Card.CARDCOLOR
	(*AccountStorageData)(nil), // 1: protomsg.AccountStorageData
	(*AccountGameData)(nil),    // 2: protomsg.AccountGameData
	(*Email)(nil),              // 3: protomsg.Email
	(*RoomInfo)(nil),           // 4: protomsg.RoomInfo
	(*GameInfo)(nil),           // 5: protomsg.GameInfo
	(*Card)(nil),               // 6: protomsg.Card
}
var file_protobuf_data_proto_depIdxs = []int32{
	4, // 0: protomsg.GameInfo.rooms:type_name -> protomsg.RoomInfo
	0, // 1: protomsg.Card.Color:type_name -> protomsg.Card.CARDCOLOR
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_data_proto_init() }
func file_protobuf_data_proto_init() {
	if File_protobuf_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountStorageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_data_proto_goTypes,
		DependencyIndexes: file_protobuf_data_proto_depIdxs,
		EnumInfos:         file_protobuf_data_proto_enumTypes,
		MessageInfos:      file_protobuf_data_proto_msgTypes,
	}.Build()
	File_protobuf_data_proto = out.File
	file_protobuf_data_proto_rawDesc = nil
	file_protobuf_data_proto_goTypes = nil
	file_protobuf_data_proto_depIdxs = nil
}
