// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/hall.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MSG int32

const (
	MSG_UNKNOW              MSG = 0
	MSG_CS_SYNC_SERVER_TIME MSG = 10001
	MSG_SC_SYNC_SERVER_TIME MSG = 10002
	MSG_CLIENT_KEEPALIVE    MSG = 10003
	MSG_SC_KICK_OUT_HALL    MSG = 10004
	// ///////////////////// 客户端请求的消息 /////////////////////////////////////////////
	MSG_CS_LOGIN_HALL_REQ        MSG = 10010
	MSG_SC_LOGIN_HALL_RES        MSG = 10011
	MSG_CS_SAFEMONEY_OPERATE_REQ MSG = 10014
	MSG_SC_SAFEMONEY_OPERATE_RES MSG = 10015
	MSG_CS_BIND_PHONE_REQ        MSG = 10016
	MSG_SC_BIND_PHONE_RES        MSG = 10017
	MSG_CS_ENTER_ROOM_REQ        MSG = 10018
	MSG_SC_ENTER_ROOM_RES        MSG = 10019
	MSG_CS_EMAILS_REQ            MSG = 10020
	MSG_SC_EMAILS_RES            MSG = 10021
	MSG_CS_EMAIL_READ_REQ        MSG = 10022
	MSG_SC_EMAIL_READ_RES        MSG = 10023
	MSG_CS_EMAIL_REWARD_REQ      MSG = 10024
	MSG_SC_EMAIL_REWARD_RES      MSG = 10025
	MSG_CS_EMAIL_DEL_REQ         MSG = 10026
	MSG_SC_EMAIL_DEL_RES         MSG = 10027
	// ////////////////////// 服务器主动推送的消息 ///////////////////////////////////////
	MSG_SC_UPDATE_MONEY  MSG = 10055
	MSG_SC_EMAIL_NEW     MSG = 10056
	MSG_SC_BROADCAST_MSG MSG = 10057
)

var MSG_name = map[int32]string{
	0:     "UNKNOW",
	10001: "CS_SYNC_SERVER_TIME",
	10002: "SC_SYNC_SERVER_TIME",
	10003: "CLIENT_KEEPALIVE",
	10004: "SC_KICK_OUT_HALL",
	10010: "CS_LOGIN_HALL_REQ",
	10011: "SC_LOGIN_HALL_RES",
	10014: "CS_SAFEMONEY_OPERATE_REQ",
	10015: "SC_SAFEMONEY_OPERATE_RES",
	10016: "CS_BIND_PHONE_REQ",
	10017: "SC_BIND_PHONE_RES",
	10018: "CS_ENTER_ROOM_REQ",
	10019: "SC_ENTER_ROOM_RES",
	10020: "CS_EMAILS_REQ",
	10021: "SC_EMAILS_RES",
	10022: "CS_EMAIL_READ_REQ",
	10023: "SC_EMAIL_READ_RES",
	10024: "CS_EMAIL_REWARD_REQ",
	10025: "SC_EMAIL_REWARD_RES",
	10026: "CS_EMAIL_DEL_REQ",
	10027: "SC_EMAIL_DEL_RES",
	10055: "SC_UPDATE_MONEY",
	10056: "SC_EMAIL_NEW",
	10057: "SC_BROADCAST_MSG",
}
var MSG_value = map[string]int32{
	"UNKNOW":                   0,
	"CS_SYNC_SERVER_TIME":      10001,
	"SC_SYNC_SERVER_TIME":      10002,
	"CLIENT_KEEPALIVE":         10003,
	"SC_KICK_OUT_HALL":         10004,
	"CS_LOGIN_HALL_REQ":        10010,
	"SC_LOGIN_HALL_RES":        10011,
	"CS_SAFEMONEY_OPERATE_REQ": 10014,
	"SC_SAFEMONEY_OPERATE_RES": 10015,
	"CS_BIND_PHONE_REQ":        10016,
	"SC_BIND_PHONE_RES":        10017,
	"CS_ENTER_ROOM_REQ":        10018,
	"SC_ENTER_ROOM_RES":        10019,
	"CS_EMAILS_REQ":            10020,
	"SC_EMAILS_RES":            10021,
	"CS_EMAIL_READ_REQ":        10022,
	"SC_EMAIL_READ_RES":        10023,
	"CS_EMAIL_REWARD_REQ":      10024,
	"SC_EMAIL_REWARD_RES":      10025,
	"CS_EMAIL_DEL_REQ":         10026,
	"SC_EMAIL_DEL_RES":         10027,
	"SC_UPDATE_MONEY":          10055,
	"SC_EMAIL_NEW":             10056,
	"SC_BROADCAST_MSG":         10057,
}

func (x MSG) String() string {
	return proto.EnumName(MSG_name, int32(x))
}
func (MSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

// 请求同步服务器时间 10002
type SYNC_SERVER_TIME struct {
	ServerTimeStamp uint64 `protobuf:"varint,1,opt,name=ServerTimeStamp" json:"ServerTimeStamp,omitempty"`
}

func (m *SYNC_SERVER_TIME) Reset()                    { *m = SYNC_SERVER_TIME{} }
func (m *SYNC_SERVER_TIME) String() string            { return proto.CompactTextString(m) }
func (*SYNC_SERVER_TIME) ProtoMessage()               {}
func (*SYNC_SERVER_TIME) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *SYNC_SERVER_TIME) GetServerTimeStamp() uint64 {
	if m != nil {
		return m.ServerTimeStamp
	}
	return 0
}

// 服务器踢下线 10011
type KICK_OUT_HALL struct {
	Ret uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
}

func (m *KICK_OUT_HALL) Reset()                    { *m = KICK_OUT_HALL{} }
func (m *KICK_OUT_HALL) String() string            { return proto.CompactTextString(m) }
func (*KICK_OUT_HALL) ProtoMessage()               {}
func (*KICK_OUT_HALL) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *KICK_OUT_HALL) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

// 客户端请求登陆 10010
type LOGIN_HALL_REQ struct {
	LoginType uint32 `protobuf:"varint,1,opt,name=LoginType" json:"LoginType,omitempty"`
	OSType    uint32 `protobuf:"varint,2,opt,name=OSType" json:"OSType,omitempty"`
	Unique    string `protobuf:"bytes,3,opt,name=Unique" json:"Unique,omitempty"`
	Sign      string `protobuf:"bytes,4,opt,name=Sign" json:"Sign,omitempty"`
}

func (m *LOGIN_HALL_REQ) Reset()                    { *m = LOGIN_HALL_REQ{} }
func (m *LOGIN_HALL_REQ) String() string            { return proto.CompactTextString(m) }
func (*LOGIN_HALL_REQ) ProtoMessage()               {}
func (*LOGIN_HALL_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *LOGIN_HALL_REQ) GetLoginType() uint32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LOGIN_HALL_REQ) GetOSType() uint32 {
	if m != nil {
		return m.OSType
	}
	return 0
}

func (m *LOGIN_HALL_REQ) GetUnique() string {
	if m != nil {
		return m.Unique
	}
	return ""
}

func (m *LOGIN_HALL_REQ) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

// 客户端请求登陆 10011
type LOGIN_HALL_RES struct {
	Ret         uint32              `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	Account     *AccountStorageData `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
	AccountData *AccountGameData    `protobuf:"bytes,3,opt,name=AccountData" json:"AccountData,omitempty"`
}

func (m *LOGIN_HALL_RES) Reset()                    { *m = LOGIN_HALL_RES{} }
func (m *LOGIN_HALL_RES) String() string            { return proto.CompactTextString(m) }
func (*LOGIN_HALL_RES) ProtoMessage()               {}
func (*LOGIN_HALL_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *LOGIN_HALL_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LOGIN_HALL_RES) GetAccount() *AccountStorageData {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *LOGIN_HALL_RES) GetAccountData() *AccountGameData {
	if m != nil {
		return m.AccountData
	}
	return nil
}

// 客户端请求操作保险箱 10014
type SAFEMONEY_OPERATE_REQ struct {
	Operate      uint32 `protobuf:"varint,1,opt,name=Operate" json:"Operate,omitempty"`
	OperateMoney uint64 `protobuf:"varint,2,opt,name=OperateMoney" json:"OperateMoney,omitempty"`
}

func (m *SAFEMONEY_OPERATE_REQ) Reset()                    { *m = SAFEMONEY_OPERATE_REQ{} }
func (m *SAFEMONEY_OPERATE_REQ) String() string            { return proto.CompactTextString(m) }
func (*SAFEMONEY_OPERATE_REQ) ProtoMessage()               {}
func (*SAFEMONEY_OPERATE_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *SAFEMONEY_OPERATE_REQ) GetOperate() uint32 {
	if m != nil {
		return m.Operate
	}
	return 0
}

func (m *SAFEMONEY_OPERATE_REQ) GetOperateMoney() uint64 {
	if m != nil {
		return m.OperateMoney
	}
	return 0
}

// 客户端请求操作保险箱 10015
type SAFEMONEY_OPERATE_RES struct {
	Ret uint32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
}

func (m *SAFEMONEY_OPERATE_RES) Reset()                    { *m = SAFEMONEY_OPERATE_RES{} }
func (m *SAFEMONEY_OPERATE_RES) String() string            { return proto.CompactTextString(m) }
func (*SAFEMONEY_OPERATE_RES) ProtoMessage()               {}
func (*SAFEMONEY_OPERATE_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *SAFEMONEY_OPERATE_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

// 客户端请求登陆 10016
type BIND_PHONE_REQ struct {
	Phone string `protobuf:"bytes,1,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *BIND_PHONE_REQ) Reset()                    { *m = BIND_PHONE_REQ{} }
func (m *BIND_PHONE_REQ) String() string            { return proto.CompactTextString(m) }
func (*BIND_PHONE_REQ) ProtoMessage()               {}
func (*BIND_PHONE_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *BIND_PHONE_REQ) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// 客户端请求登陆 10017
type BIND_PHONE_RES struct {
	Ret uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
}

func (m *BIND_PHONE_RES) Reset()                    { *m = BIND_PHONE_RES{} }
func (m *BIND_PHONE_RES) String() string            { return proto.CompactTextString(m) }
func (*BIND_PHONE_RES) ProtoMessage()               {}
func (*BIND_PHONE_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *BIND_PHONE_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

// 玩家请求进入房间 10018
type ENTER_ROOM_REQ struct {
	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *ENTER_ROOM_REQ) Reset()                    { *m = ENTER_ROOM_REQ{} }
func (m *ENTER_ROOM_REQ) String() string            { return proto.CompactTextString(m) }
func (*ENTER_ROOM_REQ) ProtoMessage()               {}
func (*ENTER_ROOM_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *ENTER_ROOM_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 玩家请求进入房间 10019
type ENTER_ROOM_RES struct {
	Ret      uint32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	RoomID   uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
	GameType uint32 `protobuf:"varint,3,opt,name=GameType" json:"GameType,omitempty"`
}

func (m *ENTER_ROOM_RES) Reset()                    { *m = ENTER_ROOM_RES{} }
func (m *ENTER_ROOM_RES) String() string            { return proto.CompactTextString(m) }
func (*ENTER_ROOM_RES) ProtoMessage()               {}
func (*ENTER_ROOM_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *ENTER_ROOM_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *ENTER_ROOM_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ENTER_ROOM_RES) GetGameType() uint32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

// /////////////////////// 邮件相关 ///////////////////////////////////////
// 客户端请求邮件列表 10020
type EMAILS_REQ struct {
}

func (m *EMAILS_REQ) Reset()                    { *m = EMAILS_REQ{} }
func (m *EMAILS_REQ) String() string            { return proto.CompactTextString(m) }
func (*EMAILS_REQ) ProtoMessage()               {}
func (*EMAILS_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

// 客户端请求邮件列表 10021
type EMAILS_RES struct {
	Emails []*Email `protobuf:"bytes,1,rep,name=Emails" json:"Emails,omitempty"`
}

func (m *EMAILS_RES) Reset()                    { *m = EMAILS_RES{} }
func (m *EMAILS_RES) String() string            { return proto.CompactTextString(m) }
func (*EMAILS_RES) ProtoMessage()               {}
func (*EMAILS_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *EMAILS_RES) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

// 客户端请求阅读未读过的邮件 10022
type EMAIL_READ_REQ struct {
	EmailID uint32 `protobuf:"varint,1,opt,name=EmailID" json:"EmailID,omitempty"`
}

func (m *EMAIL_READ_REQ) Reset()                    { *m = EMAIL_READ_REQ{} }
func (m *EMAIL_READ_REQ) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_READ_REQ) ProtoMessage()               {}
func (*EMAIL_READ_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *EMAIL_READ_REQ) GetEmailID() uint32 {
	if m != nil {
		return m.EmailID
	}
	return 0
}

// 客户端请求阅读未读过的邮件 10023
type EMAIL_READ_RES struct {
	EmailID uint32 `protobuf:"varint,1,opt,name=EmailID" json:"EmailID,omitempty"`
}

func (m *EMAIL_READ_RES) Reset()                    { *m = EMAIL_READ_RES{} }
func (m *EMAIL_READ_RES) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_READ_RES) ProtoMessage()               {}
func (*EMAIL_READ_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *EMAIL_READ_RES) GetEmailID() uint32 {
	if m != nil {
		return m.EmailID
	}
	return 0
}

// 客户端请求领取邮件奖励 10024
type EMAIL_REWARD_REQ struct {
	EmailID uint32 `protobuf:"varint,1,opt,name=EmailID" json:"EmailID,omitempty"`
}

func (m *EMAIL_REWARD_REQ) Reset()                    { *m = EMAIL_REWARD_REQ{} }
func (m *EMAIL_REWARD_REQ) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_REWARD_REQ) ProtoMessage()               {}
func (*EMAIL_REWARD_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *EMAIL_REWARD_REQ) GetEmailID() uint32 {
	if m != nil {
		return m.EmailID
	}
	return 0
}

// 客户端请求阅读未读过的邮件 10025
type EMAIL_REWARD_RES struct {
	Ret     int32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	EmailID uint32 `protobuf:"varint,2,opt,name=EmailID" json:"EmailID,omitempty"`
}

func (m *EMAIL_REWARD_RES) Reset()                    { *m = EMAIL_REWARD_RES{} }
func (m *EMAIL_REWARD_RES) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_REWARD_RES) ProtoMessage()               {}
func (*EMAIL_REWARD_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *EMAIL_REWARD_RES) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *EMAIL_REWARD_RES) GetEmailID() uint32 {
	if m != nil {
		return m.EmailID
	}
	return 0
}

// 客户端请求删除一封邮件 10026
type EMAIL_DEL_REQ struct {
	EmailID uint32 `protobuf:"varint,1,opt,name=EmailID" json:"EmailID,omitempty"`
}

func (m *EMAIL_DEL_REQ) Reset()                    { *m = EMAIL_DEL_REQ{} }
func (m *EMAIL_DEL_REQ) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_DEL_REQ) ProtoMessage()               {}
func (*EMAIL_DEL_REQ) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *EMAIL_DEL_REQ) GetEmailID() uint32 {
	if m != nil {
		return m.EmailID
	}
	return 0
}

// 客户端请求阅读未读过的邮件 10027
type EMAIL_DEL_RES struct {
	EmailID uint32 `protobuf:"varint,1,opt,name=EmailID" json:"EmailID,omitempty"`
}

func (m *EMAIL_DEL_RES) Reset()                    { *m = EMAIL_DEL_RES{} }
func (m *EMAIL_DEL_RES) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_DEL_RES) ProtoMessage()               {}
func (*EMAIL_DEL_RES) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *EMAIL_DEL_RES) GetEmailID() uint32 {
	if m != nil {
		return m.EmailID
	}
	return 0
}

// ////////////////////// 服务器主动推送的消息 ///////////////////////////////////////
// 通知客户端更新金币 10055
type UPDATE_MONEY struct {
	Operate int32  `protobuf:"varint,1,opt,name=Operate" json:"Operate,omitempty"`
	Money   uint64 `protobuf:"varint,2,opt,name=Money" json:"Money,omitempty"`
}

func (m *UPDATE_MONEY) Reset()                    { *m = UPDATE_MONEY{} }
func (m *UPDATE_MONEY) String() string            { return proto.CompactTextString(m) }
func (*UPDATE_MONEY) ProtoMessage()               {}
func (*UPDATE_MONEY) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *UPDATE_MONEY) GetOperate() int32 {
	if m != nil {
		return m.Operate
	}
	return 0
}

func (m *UPDATE_MONEY) GetMoney() uint64 {
	if m != nil {
		return m.Money
	}
	return 0
}

// 通知客户端获得新邮件 10056
type EMAIL_NEW struct {
	New *Email `protobuf:"bytes,1,opt,name=New" json:"New,omitempty"`
}

func (m *EMAIL_NEW) Reset()                    { *m = EMAIL_NEW{} }
func (m *EMAIL_NEW) String() string            { return proto.CompactTextString(m) }
func (*EMAIL_NEW) ProtoMessage()               {}
func (*EMAIL_NEW) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *EMAIL_NEW) GetNew() *Email {
	if m != nil {
		return m.New
	}
	return nil
}

// 通知客户端跑马灯 10057
type BROADCAST_MSG struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *BROADCAST_MSG) Reset()                    { *m = BROADCAST_MSG{} }
func (m *BROADCAST_MSG) String() string            { return proto.CompactTextString(m) }
func (*BROADCAST_MSG) ProtoMessage()               {}
func (*BROADCAST_MSG) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *BROADCAST_MSG) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*SYNC_SERVER_TIME)(nil), "protomsg.SYNC_SERVER_TIME")
	proto.RegisterType((*KICK_OUT_HALL)(nil), "protomsg.KICK_OUT_HALL")
	proto.RegisterType((*LOGIN_HALL_REQ)(nil), "protomsg.LOGIN_HALL_REQ")
	proto.RegisterType((*LOGIN_HALL_RES)(nil), "protomsg.LOGIN_HALL_RES")
	proto.RegisterType((*SAFEMONEY_OPERATE_REQ)(nil), "protomsg.SAFEMONEY_OPERATE_REQ")
	proto.RegisterType((*SAFEMONEY_OPERATE_RES)(nil), "protomsg.SAFEMONEY_OPERATE_RES")
	proto.RegisterType((*BIND_PHONE_REQ)(nil), "protomsg.BIND_PHONE_REQ")
	proto.RegisterType((*BIND_PHONE_RES)(nil), "protomsg.BIND_PHONE_RES")
	proto.RegisterType((*ENTER_ROOM_REQ)(nil), "protomsg.ENTER_ROOM_REQ")
	proto.RegisterType((*ENTER_ROOM_RES)(nil), "protomsg.ENTER_ROOM_RES")
	proto.RegisterType((*EMAILS_REQ)(nil), "protomsg.EMAILS_REQ")
	proto.RegisterType((*EMAILS_RES)(nil), "protomsg.EMAILS_RES")
	proto.RegisterType((*EMAIL_READ_REQ)(nil), "protomsg.EMAIL_READ_REQ")
	proto.RegisterType((*EMAIL_READ_RES)(nil), "protomsg.EMAIL_READ_RES")
	proto.RegisterType((*EMAIL_REWARD_REQ)(nil), "protomsg.EMAIL_REWARD_REQ")
	proto.RegisterType((*EMAIL_REWARD_RES)(nil), "protomsg.EMAIL_REWARD_RES")
	proto.RegisterType((*EMAIL_DEL_REQ)(nil), "protomsg.EMAIL_DEL_REQ")
	proto.RegisterType((*EMAIL_DEL_RES)(nil), "protomsg.EMAIL_DEL_RES")
	proto.RegisterType((*UPDATE_MONEY)(nil), "protomsg.UPDATE_MONEY")
	proto.RegisterType((*EMAIL_NEW)(nil), "protomsg.EMAIL_NEW")
	proto.RegisterType((*BROADCAST_MSG)(nil), "protomsg.BROADCAST_MSG")
	proto.RegisterEnum("protomsg.MSG", MSG_name, MSG_value)
}

func init() { proto.RegisterFile("protobuf/hall.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 801 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xeb, 0x6e, 0xeb, 0x44,
	0x10, 0x26, 0xcd, 0xe5, 0x9c, 0x4c, 0x6e, 0x7b, 0xf6, 0xf4, 0x54, 0xe1, 0xe8, 0x20, 0xb5, 0xfb,
	0x03, 0xd2, 0x0a, 0xa5, 0x52, 0x11, 0xfc, 0x01, 0x21, 0xb9, 0xce, 0xd2, 0x5a, 0x71, 0xd6, 0x61,
	0xd7, 0x69, 0x54, 0xfe, 0x58, 0x6e, 0x31, 0x69, 0xa4, 0xc6, 0x0e, 0xae, 0x0b, 0xea, 0x63, 0x70,
	0x91, 0x90, 0x40, 0xe2, 0x7e, 0xe7, 0x11, 0x78, 0x00, 0xe0, 0xad, 0x90, 0xd7, 0xde, 0x24, 0x76,
	0xa2, 0xf6, 0x97, 0x77, 0xe6, 0xfb, 0x66, 0x67, 0x3c, 0xf3, 0xcd, 0xc2, 0xd3, 0x79, 0x18, 0x44,
	0xc1, 0xc5, 0xed, 0x47, 0x87, 0x57, 0xee, 0xf5, 0x75, 0x57, 0x5a, 0xf8, 0xb1, 0xfc, 0xcc, 0x6e,
	0x26, 0xcf, 0x97, 0xf0, 0x87, 0x6e, 0xe4, 0x26, 0x30, 0x79, 0x07, 0x90, 0x38, 0x67, 0xba, 0x23,
	0x28, 0x3f, 0xa3, 0xdc, 0xb1, 0x8d, 0x01, 0xc5, 0x1d, 0x68, 0x09, 0x2f, 0xfc, 0xc4, 0x0b, 0xed,
	0xe9, 0xcc, 0x13, 0x91, 0x3b, 0x9b, 0xb7, 0x0b, 0xbb, 0x85, 0x4e, 0x89, 0xe7, 0xdd, 0x64, 0x0f,
	0x1a, 0x7d, 0x43, 0xef, 0x3b, 0xd6, 0xc8, 0x76, 0x4e, 0x35, 0xd3, 0xc4, 0x08, 0x8a, 0xdc, 0x8b,
	0x24, 0xbd, 0xc1, 0xe3, 0x23, 0x09, 0xa1, 0x69, 0x5a, 0x27, 0x06, 0x93, 0xb8, 0xc3, 0xe9, 0xfb,
	0xf8, 0x05, 0x54, 0xcd, 0x60, 0x32, 0xf5, 0xed, 0xbb, 0xb9, 0x97, 0x32, 0x97, 0x0e, 0xbc, 0x03,
	0x15, 0x4b, 0x48, 0x68, 0x4b, 0x42, 0xa9, 0x15, 0xfb, 0x47, 0xfe, 0xf4, 0xe3, 0x5b, 0xaf, 0x5d,
	0xdc, 0x2d, 0x74, 0xaa, 0x3c, 0xb5, 0x30, 0x86, 0x92, 0x98, 0x4e, 0xfc, 0x76, 0x49, 0x7a, 0xe5,
	0x99, 0x7c, 0x55, 0xc8, 0x25, 0x15, 0xeb, 0x85, 0xe1, 0xb7, 0xe0, 0x91, 0x76, 0x79, 0x19, 0xdc,
	0xfa, 0x91, 0xcc, 0x54, 0x3b, 0x7a, 0xd1, 0x55, 0xad, 0xea, 0xa6, 0x80, 0x88, 0x82, 0xd0, 0x9d,
	0x78, 0x3d, 0x37, 0x72, 0xb9, 0x22, 0xe3, 0xb7, 0xa1, 0x96, 0x1e, 0x63, 0xbf, 0xac, 0xa6, 0x76,
	0xf4, 0xf2, 0x5a, 0xec, 0x89, 0x3b, 0x4b, 0x02, 0x57, 0xd9, 0x64, 0x04, 0xcf, 0x84, 0xf6, 0x1e,
	0x1d, 0x58, 0x8c, 0x9e, 0x3b, 0xd6, 0x90, 0x72, 0xcd, 0xa6, 0xb2, 0x29, 0x6d, 0x78, 0x64, 0xcd,
	0xbd, 0xd0, 0x8d, 0x54, 0x4b, 0x94, 0x89, 0x09, 0xd4, 0xd3, 0xe3, 0x20, 0xf0, 0xbd, 0x3b, 0x59,
	0x6c, 0x89, 0x67, 0x7c, 0x64, 0x7f, 0xf3, 0xb5, 0xf2, 0xb7, 0xc3, 0xe5, 0x6f, 0x87, 0x5e, 0x44,
	0x5e, 0x85, 0xe6, 0xb1, 0xc1, 0x7a, 0xce, 0xf0, 0xd4, 0x62, 0x49, 0xea, 0x6d, 0x28, 0x0f, 0xaf,
	0x02, 0x3f, 0x49, 0x5c, 0xe5, 0x89, 0x41, 0x48, 0x8e, 0xb7, 0xa1, 0x85, 0xa4, 0x03, 0x4d, 0xca,
	0x6c, 0xca, 0x1d, 0x6e, 0x59, 0x03, 0x79, 0xd7, 0x0e, 0x54, 0x78, 0x10, 0xcc, 0x8c, 0x5e, 0x4a,
	0x4b, 0x2d, 0x72, 0x96, 0x63, 0x6e, 0xa8, 0x6c, 0x25, 0x76, 0x6b, 0x35, 0x16, 0x3f, 0x87, 0xc7,
	0x71, 0x33, 0xa5, 0x26, 0x8a, 0x12, 0x59, 0xd8, 0xa4, 0x0e, 0x40, 0x07, 0x9a, 0x61, 0x8a, 0x38,
	0x3b, 0x79, 0x73, 0xc5, 0x12, 0xf8, 0x35, 0xa8, 0xd0, 0x99, 0x3b, 0xbd, 0xbe, 0x69, 0x17, 0x76,
	0x8b, 0x9d, 0xda, 0x51, 0x6b, 0x39, 0x23, 0xe9, 0xe7, 0x29, 0x4c, 0x0e, 0xa0, 0x29, 0xc3, 0x1c,
	0x4e, 0xb5, 0x9e, 0x9a, 0x86, 0xc4, 0x16, 0xff, 0xa1, 0xcc, 0x35, 0xae, 0xb8, 0x87, 0xfb, 0x3a,
	0x20, 0xc5, 0x1d, 0x6b, 0xfc, 0xa1, 0x9b, 0xdf, 0x5d, 0x63, 0x67, 0x9a, 0x54, 0x4e, 0x9a, 0xb4,
	0x12, 0xbf, 0x95, 0x8d, 0xdf, 0x87, 0x46, 0x12, 0xdf, 0xa3, 0xe6, 0x03, 0xa9, 0x72, 0x54, 0x71,
	0x6f, 0x55, 0xf5, 0xd1, 0xb0, 0x17, 0xcb, 0x49, 0x8a, 0x2b, 0xaf, 0xd3, 0xf2, 0x52, 0xa7, 0xdb,
	0x50, 0x5e, 0x15, 0x68, 0x62, 0x90, 0x2e, 0x54, 0x93, 0x54, 0x8c, 0x8e, 0xf1, 0x1e, 0x14, 0x99,
	0xf7, 0xa9, 0x0c, 0xdc, 0x30, 0x8e, 0x18, 0x8b, 0x4b, 0x3b, 0xe6, 0x96, 0xd6, 0xd3, 0x35, 0x61,
	0x3b, 0x03, 0x71, 0x12, 0x27, 0xbc, 0x0c, 0xfc, 0xc8, 0xf3, 0xa3, 0x54, 0x9f, 0xca, 0x3c, 0xf8,
	0xbb, 0x04, 0xc5, 0x98, 0x01, 0x50, 0x19, 0xb1, 0x3e, 0xb3, 0xc6, 0xe8, 0x25, 0xdc, 0x86, 0xa7,
	0xba, 0x70, 0xf2, 0x2f, 0x1a, 0xfa, 0x8c, 0xc5, 0x88, 0xd0, 0xd7, 0x91, 0xcf, 0x19, 0x7e, 0x06,
	0x48, 0x37, 0x0d, 0xca, 0x6c, 0xa7, 0x4f, 0xe9, 0x50, 0x33, 0x8d, 0x33, 0x8a, 0xbe, 0x90, 0x6e,
	0xa1, 0x3b, 0x99, 0xe7, 0x0d, 0x7d, 0xc9, 0xf0, 0x0e, 0x3c, 0xd1, 0x85, 0x93, 0x7d, 0xd2, 0xd0,
	0xd7, 0xd2, 0x2f, 0xf4, 0xac, 0x5f, 0xa0, 0x6f, 0x18, 0x7e, 0x05, 0xda, 0x71, 0x45, 0x9b, 0x96,
	0x1e, 0x7d, 0x2b, 0xe1, 0xb8, 0xac, 0x4d, 0xcb, 0x8b, 0xbe, 0x53, 0xd9, 0xb2, 0x0b, 0x8b, 0xbe,
	0x57, 0xd9, 0xb2, 0x0b, 0x8a, 0x7e, 0x50, 0xfc, 0xec, 0x52, 0xa2, 0x1f, 0x15, 0x3f, 0xbb, 0x82,
	0xe8, 0x27, 0x86, 0x31, 0x34, 0x62, 0xfe, 0x62, 0x85, 0xd0, 0xcf, 0xd2, 0x17, 0x73, 0x17, 0x8b,
	0x84, 0x7e, 0x59, 0xdc, 0x9b, 0xd9, 0x12, 0xf4, 0xeb, 0xe2, 0xde, 0xcc, 0x46, 0xa0, 0xdf, 0x58,
	0x3a, 0x87, 0xbc, 0xfa, 0xd1, 0xef, 0x6a, 0x0e, 0x79, 0xa5, 0xa3, 0x3f, 0x92, 0x39, 0xa8, 0x98,
	0x54, 0xc3, 0xe8, 0x4f, 0x35, 0x87, 0x8c, 0x5e, 0xd1, 0x5f, 0x0c, 0x6f, 0x43, 0x4b, 0xe8, 0xce,
	0xaa, 0x36, 0xd1, 0x3f, 0x0c, 0x3f, 0x81, 0xfa, 0x82, 0xcc, 0xe8, 0x18, 0xfd, 0xab, 0xe2, 0x33,
	0xa2, 0x42, 0xff, 0xb1, 0xe3, 0xd6, 0x07, 0x8d, 0x30, 0x08, 0xa2, 0x43, 0x25, 0xc2, 0x8b, 0x8a,
	0x3c, 0xbd, 0xf1, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0xca, 0x83, 0x02, 0x46, 0x07, 0x00,
	0x00,
}
