// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/hongbao.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 网络消息
type HBMSG int32

const (
	HBMSG_UNKNOW_HB              HBMSG = 0
	HBMSG_CS_ENTER_GAME_HB_REQ   HBMSG = 19001
	HBMSG_SC_ENTER_GAME_HB_RES   HBMSG = 19002
	HBMSG_CS_LEAVE_GAME_HB_REQ   HBMSG = 19003
	HBMSG_SC_LEAVE_GAME_HB_RES   HBMSG = 19004
	HBMSG_CS_ASSIGN_HB_REQ       HBMSG = 19008
	HBMSG_SC_ASSIGN_HB_RES       HBMSG = 19009
	HBMSG_CS_GRAB_HB_REQ         HBMSG = 19010
	HBMSG_SC_GRAB_HB_RES         HBMSG = 19011
	HBMSG_CS_HB_INFO_REQ         HBMSG = 19012
	HBMSG_SC_HB_INFO_RES         HBMSG = 19013
	HBMSG_CS_PLAYERS_HB_LIST_REQ HBMSG = 19015
	HBMSG_SC_PLAYERS_HB_LIST_RES HBMSG = 19016
)

var HBMSG_name = map[int32]string{
	0:     "UNKNOW_HB",
	19001: "CS_ENTER_GAME_HB_REQ",
	19002: "SC_ENTER_GAME_HB_RES",
	19003: "CS_LEAVE_GAME_HB_REQ",
	19004: "SC_LEAVE_GAME_HB_RES",
	19008: "CS_ASSIGN_HB_REQ",
	19009: "SC_ASSIGN_HB_RES",
	19010: "CS_GRAB_HB_REQ",
	19011: "SC_GRAB_HB_RES",
	19012: "CS_HB_INFO_REQ",
	19013: "SC_HB_INFO_RES",
	19015: "CS_PLAYERS_HB_LIST_REQ",
	19016: "SC_PLAYERS_HB_LIST_RES",
}
var HBMSG_value = map[string]int32{
	"UNKNOW_HB":              0,
	"CS_ENTER_GAME_HB_REQ":   19001,
	"SC_ENTER_GAME_HB_RES":   19002,
	"CS_LEAVE_GAME_HB_REQ":   19003,
	"SC_LEAVE_GAME_HB_RES":   19004,
	"CS_ASSIGN_HB_REQ":       19008,
	"SC_ASSIGN_HB_RES":       19009,
	"CS_GRAB_HB_REQ":         19010,
	"SC_GRAB_HB_RES":         19011,
	"CS_HB_INFO_REQ":         19012,
	"SC_HB_INFO_RES":         19013,
	"CS_PLAYERS_HB_LIST_REQ": 19015,
	"SC_PLAYERS_HB_LIST_RES": 19016,
}

func (x HBMSG) String() string {
	return proto.EnumName(HBMSG_name, int32(x))
}
func (HBMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

// 请求进入房间
type ENTER_GAME_HB_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *ENTER_GAME_HB_REQ) Reset()                    { *m = ENTER_GAME_HB_REQ{} }
func (m *ENTER_GAME_HB_REQ) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_HB_REQ) ProtoMessage()               {}
func (*ENTER_GAME_HB_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ENTER_GAME_HB_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *ENTER_GAME_HB_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type ENTER_GAME_HB_RES struct {
	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *ENTER_GAME_HB_RES) Reset()                    { *m = ENTER_GAME_HB_RES{} }
func (m *ENTER_GAME_HB_RES) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_HB_RES) ProtoMessage()               {}
func (*ENTER_GAME_HB_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *ENTER_GAME_HB_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 请求退出房间
type LEAVE_GAME_HB_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *LEAVE_GAME_HB_REQ) Reset()                    { *m = LEAVE_GAME_HB_REQ{} }
func (m *LEAVE_GAME_HB_REQ) String() string            { return proto.CompactTextString(m) }
func (*LEAVE_GAME_HB_REQ) ProtoMessage()               {}
func (*LEAVE_GAME_HB_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *LEAVE_GAME_HB_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *LEAVE_GAME_HB_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type LEAVE_GAME_HB_RES struct {
	Ret    uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	RoomID uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *LEAVE_GAME_HB_RES) Reset()                    { *m = LEAVE_GAME_HB_RES{} }
func (m *LEAVE_GAME_HB_RES) String() string            { return proto.CompactTextString(m) }
func (*LEAVE_GAME_HB_RES) ProtoMessage()               {}
func (*LEAVE_GAME_HB_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *LEAVE_GAME_HB_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LEAVE_GAME_HB_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 发红包
type ASSIGN_HB_REQ struct {
	Bet uint64 `protobuf:"varint,1,opt,name=Bet" json:"Bet,omitempty"`
}

func (m *ASSIGN_HB_REQ) Reset()                    { *m = ASSIGN_HB_REQ{} }
func (m *ASSIGN_HB_REQ) String() string            { return proto.CompactTextString(m) }
func (*ASSIGN_HB_REQ) ProtoMessage()               {}
func (*ASSIGN_HB_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *ASSIGN_HB_REQ) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

// 广播所有玩家
type ASSIGN_HB_RES struct {
	Ret uint64 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
}

func (m *ASSIGN_HB_RES) Reset()                    { *m = ASSIGN_HB_RES{} }
func (m *ASSIGN_HB_RES) String() string            { return proto.CompactTextString(m) }
func (*ASSIGN_HB_RES) ProtoMessage()               {}
func (*ASSIGN_HB_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *ASSIGN_HB_RES) GetRet() uint64 {
	if m != nil {
		return m.Ret
	}
	return 0
}

// 抢红包
type GRAB_HB_REQ struct {
	Bet uint64 `protobuf:"varint,1,opt,name=Bet" json:"Bet,omitempty"`
}

func (m *GRAB_HB_REQ) Reset()                    { *m = GRAB_HB_REQ{} }
func (m *GRAB_HB_REQ) String() string            { return proto.CompactTextString(m) }
func (*GRAB_HB_REQ) ProtoMessage()               {}
func (*GRAB_HB_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *GRAB_HB_REQ) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

// 广播所有玩家
type GRAB_HB_RES struct {
	Bet uint64 `protobuf:"varint,1,opt,name=Bet" json:"Bet,omitempty"`
}

func (m *GRAB_HB_RES) Reset()                    { *m = GRAB_HB_RES{} }
func (m *GRAB_HB_RES) String() string            { return proto.CompactTextString(m) }
func (*GRAB_HB_RES) ProtoMessage()               {}
func (*GRAB_HB_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *GRAB_HB_RES) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

// 请求HB玩家列表
type PLAYERS_HB_LIST_RES struct {
	Players []*AccountStorageData `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
}

func (m *PLAYERS_HB_LIST_RES) Reset()                    { *m = PLAYERS_HB_LIST_RES{} }
func (m *PLAYERS_HB_LIST_RES) String() string            { return proto.CompactTextString(m) }
func (*PLAYERS_HB_LIST_RES) ProtoMessage()               {}
func (*PLAYERS_HB_LIST_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *PLAYERS_HB_LIST_RES) GetPlayers() []*AccountStorageData {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterType((*ENTER_GAME_HB_REQ)(nil), "protomsg.ENTER_GAME_HB_REQ")
	proto.RegisterType((*ENTER_GAME_HB_RES)(nil), "protomsg.ENTER_GAME_HB_RES")
	proto.RegisterType((*LEAVE_GAME_HB_REQ)(nil), "protomsg.LEAVE_GAME_HB_REQ")
	proto.RegisterType((*LEAVE_GAME_HB_RES)(nil), "protomsg.LEAVE_GAME_HB_RES")
	proto.RegisterType((*ASSIGN_HB_REQ)(nil), "protomsg.ASSIGN_HB_REQ")
	proto.RegisterType((*ASSIGN_HB_RES)(nil), "protomsg.ASSIGN_HB_RES")
	proto.RegisterType((*GRAB_HB_REQ)(nil), "protomsg.GRAB_HB_REQ")
	proto.RegisterType((*GRAB_HB_RES)(nil), "protomsg.GRAB_HB_RES")
	proto.RegisterType((*PLAYERS_HB_LIST_RES)(nil), "protomsg.PLAYERS_HB_LIST_RES")
	proto.RegisterEnum("protomsg.HBMSG", HBMSG_name, HBMSG_value)
}

func init() { proto.RegisterFile("protobuf/hongbao.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4f, 0x8f, 0xd2, 0x50,
	0x14, 0xc5, 0x7d, 0xc3, 0x38, 0x3a, 0x77, 0x52, 0x7d, 0xf3, 0x66, 0xd2, 0x90, 0x09, 0x89, 0x23,
	0x2b, 0xa2, 0x09, 0x24, 0x9a, 0xb8, 0x73, 0xd1, 0x3e, 0x6a, 0xdb, 0x08, 0x45, 0xde, 0x45, 0x8d,
	0x6e, 0x5e, 0x0a, 0x22, 0x2e, 0x84, 0x47, 0x4a, 0x59, 0xf8, 0x3d, 0xfa, 0x65, 0xfc, 0xb3, 0xf0,
	0x6f, 0x34, 0x7e, 0x2a, 0xd3, 0xbf, 0x50, 0x0b, 0xbb, 0x59, 0xf5, 0xf6, 0x9c, 0xdf, 0x3d, 0x6d,
	0xce, 0x05, 0x7d, 0x19, 0xa8, 0x50, 0x8d, 0xd7, 0x6f, 0x3b, 0xef, 0xd4, 0x62, 0x36, 0xf6, 0x55,
	0x3b, 0x11, 0xd8, 0xcd, 0xe4, 0x31, 0x5f, 0xcd, 0x2e, 0xce, 0x0a, 0xe2, 0x8d, 0x1f, 0xfa, 0xa9,
	0xdd, 0x74, 0xe1, 0xd4, 0xf2, 0x46, 0x96, 0x90, 0xb6, 0xd1, 0xb7, 0xa4, 0x63, 0x4a, 0x61, 0x0d,
	0x59, 0x03, 0x8e, 0x8d, 0xc9, 0x44, 0xad, 0x17, 0xa1, 0xdb, 0xad, 0x93, 0x4b, 0xd2, 0xd2, 0xc4,
	0x46, 0x60, 0x3a, 0x1c, 0x09, 0xa5, 0xe6, 0x6e, 0xb7, 0x7e, 0x90, 0x58, 0xd9, 0x5b, 0xf3, 0x7e,
	0x35, 0x0a, 0xb7, 0x60, 0x52, 0x82, 0x5d, 0x38, 0xed, 0x59, 0xc6, 0x0b, 0xeb, 0x0a, 0xbe, 0xfb,
	0xb8, 0x1a, 0x85, 0x8c, 0x42, 0x4d, 0x4c, 0xc3, 0x2c, 0x24, 0x1e, 0xf7, 0xae, 0xdf, 0x05, 0xcd,
	0x40, 0x74, 0x6d, 0x2f, 0xff, 0x0b, 0x0a, 0x35, 0x33, 0x5b, 0x3d, 0x14, 0xf1, 0xf8, 0x3f, 0x52,
	0x4a, 0x3f, 0x4c, 0xd2, 0x9b, 0x77, 0xe0, 0xc4, 0x16, 0x86, 0xb9, 0x3f, 0xa3, 0x04, 0xe0, 0x0e,
	0xa0, 0x0f, 0x67, 0xcf, 0x7a, 0xc6, 0x2b, 0x4b, 0x60, 0xcc, 0xf4, 0x5c, 0x1c, 0x25, 0xe0, 0x23,
	0xb8, 0xb1, 0x7c, 0xef, 0x7f, 0x98, 0x06, 0xab, 0x3a, 0xb9, 0xac, 0xb5, 0x4e, 0x1e, 0x34, 0xda,
	0xf9, 0x45, 0xdb, 0x59, 0x37, 0x18, 0xaa, 0xc0, 0x9f, 0x4d, 0xbb, 0x7e, 0xe8, 0x8b, 0x1c, 0xbe,
	0xf7, 0xf7, 0x00, 0xae, 0x3b, 0x66, 0x1f, 0x6d, 0xa6, 0xc1, 0xf1, 0x73, 0xef, 0xa9, 0x37, 0x78,
	0x29, 0x1d, 0x93, 0x5e, 0x63, 0x17, 0x70, 0xce, 0x51, 0x56, 0x8e, 0x4e, 0x3f, 0x46, 0x24, 0xf6,
	0x90, 0x57, 0x3c, 0xa4, 0x9f, 0x52, 0x8f, 0xa3, 0xac, 0x1c, 0x8d, 0x7e, 0x2e, 0xf6, 0x2a, 0x57,
	0xa0, 0x5f, 0x22, 0xc2, 0x74, 0xa0, 0x1c, 0x65, 0xa9, 0x62, 0xfa, 0x35, 0xd5, 0x91, 0x97, 0x74,
	0xa4, 0xdf, 0x22, 0xc2, 0xce, 0xe1, 0x16, 0x47, 0xb9, 0x55, 0x26, 0xfd, 0x9e, 0xaa, 0xc8, 0xb7,
	0x54, 0xa4, 0x3f, 0x0a, 0xd6, 0x31, 0xa5, 0xeb, 0x3d, 0x19, 0x24, 0xec, 0xcf, 0x82, 0xdd, 0xa8,
	0x48, 0x7f, 0x45, 0x84, 0x35, 0x40, 0xe7, 0x28, 0xab, 0x15, 0x0f, 0xe9, 0xef, 0xd4, 0x45, 0xbe,
	0xc3, 0x45, 0xfa, 0x27, 0x22, 0xe6, 0xed, 0xd7, 0x5a, 0xa0, 0x54, 0xd8, 0xc9, 0x9b, 0x1f, 0x1f,
	0x25, 0xd3, 0xc3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0xeb, 0x88, 0xb3, 0x76, 0x03, 0x00,
	0x00,
}
