// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/lhd.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// //////////////////////////////////////////////////// 网络消息 /////////////////////////////////////////////////////////////
type LHDMSG int32

const (
	LHDMSG_UNKNOW_LHD                          LHDMSG = 0
	LHDMSG_CS_ENTER_GAME_LHD_REQ               LHDMSG = 70001
	LHDMSG_SC_ENTER_GAME_LHD_RES               LHDMSG = 70002
	LHDMSG_CS_LEAVE_GAME_LHD_REQ               LHDMSG = 70003
	LHDMSG_SC_LEAVE_GAME_LHD_RES               LHDMSG = 70004
	LHDMSG_CS_BET_LHD_REQ                      LHDMSG = 70008
	LHDMSG_SC_BET_LHD_RES                      LHDMSG = 70009
	LHDMSG_CS_CLEAN_BET_LHD_REQ                LHDMSG = 70010
	LHDMSG_SC_CLEAN_BET_LHD_RES                LHDMSG = 70011
	LHDMSG_CS_PLAYERS_LHD_LIST_REQ             LHDMSG = 70015
	LHDMSG_SC_PLAYERS_LHD_LIST_RES             LHDMSG = 70016
	LHDMSG_SC_SWITCH_GAME_STATUS_BROADCAST_LHD LHDMSG = 70020
)

var LHDMSG_name = map[int32]string{
	0:     "UNKNOW_LHD",
	70001: "CS_ENTER_GAME_LHD_REQ",
	70002: "SC_ENTER_GAME_LHD_RES",
	70003: "CS_LEAVE_GAME_LHD_REQ",
	70004: "SC_LEAVE_GAME_LHD_RES",
	70008: "CS_BET_LHD_REQ",
	70009: "SC_BET_LHD_RES",
	70010: "CS_CLEAN_BET_LHD_REQ",
	70011: "SC_CLEAN_BET_LHD_RES",
	70015: "CS_PLAYERS_LHD_LIST_REQ",
	70016: "SC_PLAYERS_LHD_LIST_RES",
	70020: "SC_SWITCH_GAME_STATUS_BROADCAST_LHD",
}
var LHDMSG_value = map[string]int32{
	"UNKNOW_LHD":                          0,
	"CS_ENTER_GAME_LHD_REQ":               70001,
	"SC_ENTER_GAME_LHD_RES":               70002,
	"CS_LEAVE_GAME_LHD_REQ":               70003,
	"SC_LEAVE_GAME_LHD_RES":               70004,
	"CS_BET_LHD_REQ":                      70008,
	"SC_BET_LHD_RES":                      70009,
	"CS_CLEAN_BET_LHD_REQ":                70010,
	"SC_CLEAN_BET_LHD_RES":                70011,
	"CS_PLAYERS_LHD_LIST_REQ":             70015,
	"SC_PLAYERS_LHD_LIST_RES":             70016,
	"SC_SWITCH_GAME_STATUS_BROADCAST_LHD": 70020,
}

func (x LHDMSG) String() string {
	return proto.EnumName(LHDMSG_name, int32(x))
}
func (LHDMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

// //////////////////////////////////////////////////// 游戏枚举 /////////////////////////////////////////////////////////////
// 下注区域
type LHDAREA int32

const (
	LHDAREA_LHD_AREA_Unknow LHDAREA = 0
	LHDAREA_LHD_AREA_DRAGON LHDAREA = 1
	LHDAREA_LHD_AREA_TIGER  LHDAREA = 2
	LHDAREA_LHD_AREA_PEACE  LHDAREA = 3
)

var LHDAREA_name = map[int32]string{
	0: "LHD_AREA_Unknow",
	1: "LHD_AREA_DRAGON",
	2: "LHD_AREA_TIGER",
	3: "LHD_AREA_PEACE",
}
var LHDAREA_value = map[string]int32{
	"LHD_AREA_Unknow": 0,
	"LHD_AREA_DRAGON": 1,
	"LHD_AREA_TIGER":  2,
	"LHD_AREA_PEACE":  3,
}

func (x LHDAREA) String() string {
	return proto.EnumName(LHDAREA_name, int32(x))
}
func (LHDAREA) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

// 游戏状态
type LHDGAMESTATUS int32

const (
	LHDGAMESTATUS_LHD_GAMESTATUS_Unknow LHDGAMESTATUS = 0
	LHDGAMESTATUS_LHD_GAMESTATUS_WAIT   LHDGAMESTATUS = 1
	LHDGAMESTATUS_LHD_GAMESTATUS_BET    LHDGAMESTATUS = 2
	LHDGAMESTATUS_LHD_GAMESTATUS_STOP   LHDGAMESTATUS = 3
	LHDGAMESTATUS_LHD_GAMESTATUS_SETTLE LHDGAMESTATUS = 4
)

var LHDGAMESTATUS_name = map[int32]string{
	0: "LHD_GAMESTATUS_Unknow",
	1: "LHD_GAMESTATUS_WAIT",
	2: "LHD_GAMESTATUS_BET",
	3: "LHD_GAMESTATUS_STOP",
	4: "LHD_GAMESTATUS_SETTLE",
}
var LHDGAMESTATUS_value = map[string]int32{
	"LHD_GAMESTATUS_Unknow": 0,
	"LHD_GAMESTATUS_WAIT":   1,
	"LHD_GAMESTATUS_BET":    2,
	"LHD_GAMESTATUS_STOP":   3,
	"LHD_GAMESTATUS_SETTLE": 4,
}

func (x LHDGAMESTATUS) String() string {
	return proto.EnumName(LHDGAMESTATUS_name, int32(x))
}
func (LHDGAMESTATUS) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

// //////////////////////////////////////////////////// 消息数据结构 /////////////////////////////////////////////////////////////
// 请求进入房间
type ENTER_GAME_LHD_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *ENTER_GAME_LHD_REQ) Reset()                    { *m = ENTER_GAME_LHD_REQ{} }
func (m *ENTER_GAME_LHD_REQ) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_LHD_REQ) ProtoMessage()               {}
func (*ENTER_GAME_LHD_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ENTER_GAME_LHD_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *ENTER_GAME_LHD_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 进入房间，服务器返回房间、游戏状态相关数据
type ENTER_GAME_LHD_RES struct {
	RoomID         uint32                       `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	HistoryWinners []*ENTER_GAME_LHD_RES_Winner `protobuf:"bytes,2,rep,name=HistoryWinners" json:"HistoryWinners,omitempty"`
	Bets           []int64                      `protobuf:"varint,3,rep,packed,name=bets" json:"bets,omitempty"`
	ShowNum        uint32                       `protobuf:"varint,4,opt,name=ShowNum" json:"ShowNum,omitempty"`
	BetLimit       uint64                       `protobuf:"varint,5,opt,name=BetLimit" json:"BetLimit,omitempty"`
	Status         *StatusMsgLHD                `protobuf:"bytes,6,opt,name=Status" json:"Status,omitempty"`
}

func (m *ENTER_GAME_LHD_RES) Reset()                    { *m = ENTER_GAME_LHD_RES{} }
func (m *ENTER_GAME_LHD_RES) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_LHD_RES) ProtoMessage()               {}
func (*ENTER_GAME_LHD_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *ENTER_GAME_LHD_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ENTER_GAME_LHD_RES) GetHistoryWinners() []*ENTER_GAME_LHD_RES_Winner {
	if m != nil {
		return m.HistoryWinners
	}
	return nil
}

func (m *ENTER_GAME_LHD_RES) GetBets() []int64 {
	if m != nil {
		return m.Bets
	}
	return nil
}

func (m *ENTER_GAME_LHD_RES) GetShowNum() uint32 {
	if m != nil {
		return m.ShowNum
	}
	return 0
}

func (m *ENTER_GAME_LHD_RES) GetBetLimit() uint64 {
	if m != nil {
		return m.BetLimit
	}
	return 0
}

func (m *ENTER_GAME_LHD_RES) GetStatus() *StatusMsgLHD {
	if m != nil {
		return m.Status
	}
	return nil
}

type ENTER_GAME_LHD_RES_Winner struct {
	WinArea LHDAREA `protobuf:"varint,1,opt,name=WinArea,enum=protomsg.LHDAREA" json:"WinArea,omitempty"`
}

func (m *ENTER_GAME_LHD_RES_Winner) Reset()                    { *m = ENTER_GAME_LHD_RES_Winner{} }
func (m *ENTER_GAME_LHD_RES_Winner) String() string            { return proto.CompactTextString(m) }
func (*ENTER_GAME_LHD_RES_Winner) ProtoMessage()               {}
func (*ENTER_GAME_LHD_RES_Winner) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1, 0} }

func (m *ENTER_GAME_LHD_RES_Winner) GetWinArea() LHDAREA {
	if m != nil {
		return m.WinArea
	}
	return LHDAREA_LHD_AREA_Unknow
}

// 请求退出房间
type LEAVE_GAME_LHD_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *LEAVE_GAME_LHD_REQ) Reset()                    { *m = LEAVE_GAME_LHD_REQ{} }
func (m *LEAVE_GAME_LHD_REQ) String() string            { return proto.CompactTextString(m) }
func (*LEAVE_GAME_LHD_REQ) ProtoMessage()               {}
func (*LEAVE_GAME_LHD_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *LEAVE_GAME_LHD_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *LEAVE_GAME_LHD_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type LEAVE_GAME_LHD_RES struct {
	Ret    uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	RoomID uint32 `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *LEAVE_GAME_LHD_RES) Reset()                    { *m = LEAVE_GAME_LHD_RES{} }
func (m *LEAVE_GAME_LHD_RES) String() string            { return proto.CompactTextString(m) }
func (*LEAVE_GAME_LHD_RES) ProtoMessage()               {}
func (*LEAVE_GAME_LHD_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *LEAVE_GAME_LHD_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LEAVE_GAME_LHD_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// //////////////////////////////////////////// 游戏 /////////////////////////////////////////////
// 服务器广播切换状态
type SWITCH_GAME_STATUS_BROADCAST_LHD struct {
	NextStatus *StatusMsgLHD `protobuf:"bytes,1,opt,name=NextStatus" json:"NextStatus,omitempty"`
}

func (m *SWITCH_GAME_STATUS_BROADCAST_LHD) Reset()         { *m = SWITCH_GAME_STATUS_BROADCAST_LHD{} }
func (m *SWITCH_GAME_STATUS_BROADCAST_LHD) String() string { return proto.CompactTextString(m) }
func (*SWITCH_GAME_STATUS_BROADCAST_LHD) ProtoMessage()    {}
func (*SWITCH_GAME_STATUS_BROADCAST_LHD) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{4}
}

func (m *SWITCH_GAME_STATUS_BROADCAST_LHD) GetNextStatus() *StatusMsgLHD {
	if m != nil {
		return m.NextStatus
	}
	return nil
}

// 状态结构
type StatusMsgLHD struct {
	Status           LHDGAMESTATUS   `protobuf:"varint,1,opt,name=Status,enum=protomsg.LHDGAMESTATUS" json:"Status,omitempty"`
	Status_StartTime uint64          `protobuf:"varint,2,opt,name=Status_StartTime,json=StatusStartTime" json:"Status_StartTime,omitempty"`
	Status_EndTime   uint64          `protobuf:"varint,3,opt,name=Status_EndTime,json=StatusEndTime" json:"Status_EndTime,omitempty"`
	AreaBetVal       map[int32]int64 `protobuf:"bytes,4,rep,name=AreaBetVal" json:"AreaBetVal,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AreaBetVal_Own   map[int32]int64 `protobuf:"bytes,5,rep,name=AreaBetVal_Own,json=AreaBetValOwn" json:"AreaBetVal_Own,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Status_Data      []byte          `protobuf:"bytes,6,opt,name=Status_Data,json=StatusData,proto3" json:"Status_Data,omitempty"`
}

func (m *StatusMsgLHD) Reset()                    { *m = StatusMsgLHD{} }
func (m *StatusMsgLHD) String() string            { return proto.CompactTextString(m) }
func (*StatusMsgLHD) ProtoMessage()               {}
func (*StatusMsgLHD) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *StatusMsgLHD) GetStatus() LHDGAMESTATUS {
	if m != nil {
		return m.Status
	}
	return LHDGAMESTATUS_LHD_GAMESTATUS_Unknow
}

func (m *StatusMsgLHD) GetStatus_StartTime() uint64 {
	if m != nil {
		return m.Status_StartTime
	}
	return 0
}

func (m *StatusMsgLHD) GetStatus_EndTime() uint64 {
	if m != nil {
		return m.Status_EndTime
	}
	return 0
}

func (m *StatusMsgLHD) GetAreaBetVal() map[int32]int64 {
	if m != nil {
		return m.AreaBetVal
	}
	return nil
}

func (m *StatusMsgLHD) GetAreaBetVal_Own() map[int32]int64 {
	if m != nil {
		return m.AreaBetVal_Own
	}
	return nil
}

func (m *StatusMsgLHD) GetStatus_Data() []byte {
	if m != nil {
		return m.Status_Data
	}
	return nil
}

// 1.等待
type Status_Wait_LHD struct {
}

func (m *Status_Wait_LHD) Reset()                    { *m = Status_Wait_LHD{} }
func (m *Status_Wait_LHD) String() string            { return proto.CompactTextString(m) }
func (*Status_Wait_LHD) ProtoMessage()               {}
func (*Status_Wait_LHD) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

// 2.押注
type Status_Bet_LHD struct {
}

func (m *Status_Bet_LHD) Reset()                    { *m = Status_Bet_LHD{} }
func (m *Status_Bet_LHD) String() string            { return proto.CompactTextString(m) }
func (*Status_Bet_LHD) ProtoMessage()               {}
func (*Status_Bet_LHD) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

// 3.停止下注
type Status_Stop_LHD struct {
}

func (m *Status_Stop_LHD) Reset()                    { *m = Status_Stop_LHD{} }
func (m *Status_Stop_LHD) String() string            { return proto.CompactTextString(m) }
func (*Status_Stop_LHD) ProtoMessage()               {}
func (*Status_Stop_LHD) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

// 4.结算
type Status_Settle_LHD struct {
	WinArea     LHDAREA         `protobuf:"varint,1,opt,name=WinArea,enum=protomsg.LHDAREA" json:"WinArea,omitempty"`
	GragonCards *Card           `protobuf:"bytes,2,opt,name=GragonCards" json:"GragonCards,omitempty"`
	TigerCards  *Card           `protobuf:"bytes,3,opt,name=TigerCards" json:"TigerCards,omitempty"`
	Players     map[int32]int64 `protobuf:"bytes,4,rep,name=Players" json:"Players,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Status_Settle_LHD) Reset()                    { *m = Status_Settle_LHD{} }
func (m *Status_Settle_LHD) String() string            { return proto.CompactTextString(m) }
func (*Status_Settle_LHD) ProtoMessage()               {}
func (*Status_Settle_LHD) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *Status_Settle_LHD) GetWinArea() LHDAREA {
	if m != nil {
		return m.WinArea
	}
	return LHDAREA_LHD_AREA_Unknow
}

func (m *Status_Settle_LHD) GetGragonCards() *Card {
	if m != nil {
		return m.GragonCards
	}
	return nil
}

func (m *Status_Settle_LHD) GetTigerCards() *Card {
	if m != nil {
		return m.TigerCards
	}
	return nil
}

func (m *Status_Settle_LHD) GetPlayers() map[int32]int64 {
	if m != nil {
		return m.Players
	}
	return nil
}

// 请求下注
type BET_LHD_REQ struct {
	AccountID uint32  `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	Area      LHDAREA `protobuf:"varint,2,opt,name=Area,enum=protomsg.LHDAREA" json:"Area,omitempty"`
	Bet       uint64  `protobuf:"varint,3,opt,name=Bet" json:"Bet,omitempty"`
}

func (m *BET_LHD_REQ) Reset()                    { *m = BET_LHD_REQ{} }
func (m *BET_LHD_REQ) String() string            { return proto.CompactTextString(m) }
func (*BET_LHD_REQ) ProtoMessage()               {}
func (*BET_LHD_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *BET_LHD_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *BET_LHD_REQ) GetArea() LHDAREA {
	if m != nil {
		return m.Area
	}
	return LHDAREA_LHD_AREA_Unknow
}

func (m *BET_LHD_REQ) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

// 间隔 200 毫秒一次 广播玩家下注
type BET_LHD_RES struct {
	Players    []*BET_LHD_RES_BetPlayer `protobuf:"bytes,1,rep,name=Players" json:"Players,omitempty"`
	AreaBetVal map[int32]int64          `protobuf:"bytes,2,rep,name=AreaBetVal" json:"AreaBetVal,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *BET_LHD_RES) Reset()                    { *m = BET_LHD_RES{} }
func (m *BET_LHD_RES) String() string            { return proto.CompactTextString(m) }
func (*BET_LHD_RES) ProtoMessage()               {}
func (*BET_LHD_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *BET_LHD_RES) GetPlayers() []*BET_LHD_RES_BetPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *BET_LHD_RES) GetAreaBetVal() map[int32]int64 {
	if m != nil {
		return m.AreaBetVal
	}
	return nil
}

type BET_LHD_RES_BetPlayer struct {
	AccountID uint32  `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	Area      LHDAREA `protobuf:"varint,2,opt,name=Area,enum=protomsg.LHDAREA" json:"Area,omitempty"`
	Bet       uint64  `protobuf:"varint,3,opt,name=Bet" json:"Bet,omitempty"`
}

func (m *BET_LHD_RES_BetPlayer) Reset()                    { *m = BET_LHD_RES_BetPlayer{} }
func (m *BET_LHD_RES_BetPlayer) String() string            { return proto.CompactTextString(m) }
func (*BET_LHD_RES_BetPlayer) ProtoMessage()               {}
func (*BET_LHD_RES_BetPlayer) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11, 0} }

func (m *BET_LHD_RES_BetPlayer) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *BET_LHD_RES_BetPlayer) GetArea() LHDAREA {
	if m != nil {
		return m.Area
	}
	return LHDAREA_LHD_AREA_Unknow
}

func (m *BET_LHD_RES_BetPlayer) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

// 请求清除下注
type CLEAN_BET_LHD_REQ struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
}

func (m *CLEAN_BET_LHD_REQ) Reset()                    { *m = CLEAN_BET_LHD_REQ{} }
func (m *CLEAN_BET_LHD_REQ) String() string            { return proto.CompactTextString(m) }
func (*CLEAN_BET_LHD_REQ) ProtoMessage()               {}
func (*CLEAN_BET_LHD_REQ) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

func (m *CLEAN_BET_LHD_REQ) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

// 服务器广播清除下注
type CLEAN_BET_LHD_RES struct {
	AccountID        uint32          `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	PlayerAreaBetVal map[int32]int64 `protobuf:"bytes,2,rep,name=PlayerAreaBetVal" json:"PlayerAreaBetVal,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AreaBetVal       map[int32]int64 `protobuf:"bytes,3,rep,name=AreaBetVal" json:"AreaBetVal,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *CLEAN_BET_LHD_RES) Reset()                    { *m = CLEAN_BET_LHD_RES{} }
func (m *CLEAN_BET_LHD_RES) String() string            { return proto.CompactTextString(m) }
func (*CLEAN_BET_LHD_RES) ProtoMessage()               {}
func (*CLEAN_BET_LHD_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{13} }

func (m *CLEAN_BET_LHD_RES) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *CLEAN_BET_LHD_RES) GetPlayerAreaBetVal() map[int32]int64 {
	if m != nil {
		return m.PlayerAreaBetVal
	}
	return nil
}

func (m *CLEAN_BET_LHD_RES) GetAreaBetVal() map[int32]int64 {
	if m != nil {
		return m.AreaBetVal
	}
	return nil
}

// 请求LHD玩家列表
type PLAYERS_LHD_LIST_RES struct {
	Players []*AccountStorageData `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
}

func (m *PLAYERS_LHD_LIST_RES) Reset()                    { *m = PLAYERS_LHD_LIST_RES{} }
func (m *PLAYERS_LHD_LIST_RES) String() string            { return proto.CompactTextString(m) }
func (*PLAYERS_LHD_LIST_RES) ProtoMessage()               {}
func (*PLAYERS_LHD_LIST_RES) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{14} }

func (m *PLAYERS_LHD_LIST_RES) GetPlayers() []*AccountStorageData {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterType((*ENTER_GAME_LHD_REQ)(nil), "protomsg.ENTER_GAME_LHD_REQ")
	proto.RegisterType((*ENTER_GAME_LHD_RES)(nil), "protomsg.ENTER_GAME_LHD_RES")
	proto.RegisterType((*ENTER_GAME_LHD_RES_Winner)(nil), "protomsg.ENTER_GAME_LHD_RES.Winner")
	proto.RegisterType((*LEAVE_GAME_LHD_REQ)(nil), "protomsg.LEAVE_GAME_LHD_REQ")
	proto.RegisterType((*LEAVE_GAME_LHD_RES)(nil), "protomsg.LEAVE_GAME_LHD_RES")
	proto.RegisterType((*SWITCH_GAME_STATUS_BROADCAST_LHD)(nil), "protomsg.SWITCH_GAME_STATUS_BROADCAST_LHD")
	proto.RegisterType((*StatusMsgLHD)(nil), "protomsg.StatusMsgLHD")
	proto.RegisterType((*Status_Wait_LHD)(nil), "protomsg.Status_Wait_LHD")
	proto.RegisterType((*Status_Bet_LHD)(nil), "protomsg.Status_Bet_LHD")
	proto.RegisterType((*Status_Stop_LHD)(nil), "protomsg.Status_Stop_LHD")
	proto.RegisterType((*Status_Settle_LHD)(nil), "protomsg.Status_Settle_LHD")
	proto.RegisterType((*BET_LHD_REQ)(nil), "protomsg.BET_LHD_REQ")
	proto.RegisterType((*BET_LHD_RES)(nil), "protomsg.BET_LHD_RES")
	proto.RegisterType((*BET_LHD_RES_BetPlayer)(nil), "protomsg.BET_LHD_RES.BetPlayer")
	proto.RegisterType((*CLEAN_BET_LHD_REQ)(nil), "protomsg.CLEAN_BET_LHD_REQ")
	proto.RegisterType((*CLEAN_BET_LHD_RES)(nil), "protomsg.CLEAN_BET_LHD_RES")
	proto.RegisterType((*PLAYERS_LHD_LIST_RES)(nil), "protomsg.PLAYERS_LHD_LIST_RES")
	proto.RegisterEnum("protomsg.LHDMSG", LHDMSG_name, LHDMSG_value)
	proto.RegisterEnum("protomsg.LHDAREA", LHDAREA_name, LHDAREA_value)
	proto.RegisterEnum("protomsg.LHDGAMESTATUS", LHDGAMESTATUS_name, LHDGAMESTATUS_value)
}

func init() { proto.RegisterFile("protobuf/lhd.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 1058 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x0d, 0x1f, 0x96, 0x93, 0x2b, 0x5b, 0x1e, 0x8f, 0x5f, 0xaa, 0x9a, 0x22, 0x82, 0x02, 0x17,
	0xb2, 0x03, 0xc8, 0x8d, 0x8b, 0x06, 0x6d, 0x80, 0x16, 0x25, 0x29, 0xd6, 0x52, 0x4d, 0x4b, 0xce,
	0x0c, 0x1d, 0xa1, 0x29, 0x0a, 0x82, 0x8e, 0x59, 0x47, 0x88, 0x4d, 0x1a, 0xd4, 0xb8, 0xae, 0x77,
	0x5d, 0x74, 0xdf, 0x7f, 0x70, 0x76, 0x5d, 0xf6, 0x3f, 0xfa, 0x01, 0x5d, 0xf6, 0x13, 0xfa, 0x58,
	0xf4, 0xb1, 0x68, 0xc1, 0x19, 0x4a, 0xa4, 0x44, 0xc6, 0x8e, 0x91, 0x76, 0xa5, 0x99, 0x73, 0xcf,
	0x3d, 0x73, 0xe7, 0xcc, 0x9d, 0x11, 0x01, 0x9f, 0x84, 0x01, 0x0b, 0xf6, 0x4f, 0xbf, 0xdc, 0x38,
	0x7a, 0x76, 0xd0, 0xe0, 0x13, 0x7c, 0x93, 0xff, 0x1c, 0x0f, 0x0e, 0x2b, 0x0b, 0xa3, 0xe8, 0x81,
	0xcb, 0x5c, 0x11, 0xae, 0x7d, 0x0a, 0xd8, 0xec, 0xd8, 0x26, 0x71, 0xb6, 0xb4, 0x1d, 0xd3, 0xb1,
	0x5a, 0x4d, 0x87, 0x98, 0x8f, 0xf0, 0x6d, 0xb8, 0xa5, 0x3d, 0x7d, 0x1a, 0x9c, 0xfa, 0xac, 0xdd,
	0x2c, 0x4b, 0x55, 0xa9, 0x3e, 0x4b, 0x12, 0x00, 0x2f, 0x43, 0x81, 0x04, 0xc1, 0x71, 0xbb, 0x59,
	0x96, 0x79, 0x28, 0x9e, 0xd5, 0xbe, 0x97, 0x73, 0xc4, 0x68, 0x8a, 0x2e, 0xa5, 0xe9, 0x78, 0x1b,
	0x4a, 0xad, 0xfe, 0x80, 0x05, 0xe1, 0x79, 0xaf, 0xef, 0xfb, 0x5e, 0x38, 0x28, 0xcb, 0x55, 0xa5,
	0x5e, 0xdc, 0xbc, 0xdb, 0x18, 0x96, 0xdc, 0xc8, 0xaa, 0x35, 0x04, 0x97, 0x4c, 0xa4, 0x62, 0x0c,
	0xea, 0xbe, 0xc7, 0x06, 0x65, 0xa5, 0xaa, 0xd4, 0x15, 0xc2, 0xc7, 0xb8, 0x0c, 0xd3, 0xf4, 0x59,
	0x70, 0xd6, 0x39, 0x3d, 0x2e, 0xab, 0x7c, 0xe5, 0xe1, 0x14, 0x57, 0xe0, 0xa6, 0xee, 0x31, 0xab,
	0x7f, 0xdc, 0x67, 0xe5, 0xa9, 0xaa, 0x54, 0x57, 0xc9, 0x68, 0x8e, 0x1b, 0x50, 0xa0, 0xcc, 0x65,
	0xa7, 0x83, 0x72, 0xa1, 0x2a, 0xd5, 0x8b, 0x9b, 0xcb, 0x49, 0x39, 0x02, 0xdf, 0x19, 0x1c, 0x5a,
	0xad, 0x26, 0x89, 0x59, 0x95, 0xf7, 0xa0, 0x20, 0x8a, 0xc0, 0xf7, 0x60, 0xba, 0xd7, 0xf7, 0xb5,
	0xd0, 0x73, 0xf9, 0x4e, 0x4b, 0x9b, 0xf3, 0x49, 0xaa, 0xd5, 0x6a, 0x6a, 0xc4, 0xd4, 0xc8, 0x90,
	0x11, 0x19, 0x6f, 0x99, 0xda, 0x63, 0xf3, 0xbf, 0x30, 0xfe, 0xa3, 0x1c, 0x2d, 0x8a, 0x11, 0x28,
	0xc4, 0x63, 0xb1, 0x4a, 0x34, 0x7c, 0x69, 0xfe, 0x13, 0xa8, 0xd2, 0x5e, 0xdb, 0x36, 0x5a, 0x42,
	0x80, 0xda, 0x9a, 0xbd, 0x47, 0x1d, 0x9d, 0x74, 0xb5, 0xa6, 0xa1, 0x51, 0x3b, 0x52, 0xc4, 0x0f,
	0x00, 0x3a, 0xde, 0xd7, 0x2c, 0xb6, 0x46, 0xba, 0xd4, 0x9a, 0x14, 0xb3, 0xf6, 0xa3, 0x02, 0x33,
	0xe9, 0x20, 0xde, 0x18, 0xf9, 0x2b, 0x4c, 0x5a, 0x19, 0x33, 0x29, 0x2a, 0x40, 0xac, 0x3f, 0x34,
	0x18, 0xaf, 0x01, 0x12, 0x23, 0x87, 0x32, 0x37, 0x64, 0x76, 0xff, 0xd8, 0xe3, 0xf5, 0xab, 0x64,
	0x4e, 0xe0, 0x23, 0x18, 0xaf, 0x42, 0x29, 0xa6, 0x9a, 0xfe, 0x01, 0x27, 0x2a, 0x9c, 0x38, 0x2b,
	0xd0, 0x18, 0xc4, 0x9f, 0x00, 0x44, 0x67, 0xa0, 0x7b, 0xec, 0xb1, 0x7b, 0x54, 0x56, 0x79, 0xd7,
	0xbd, 0x9d, 0xbf, 0x97, 0x46, 0x42, 0x34, 0x7d, 0x16, 0x9e, 0x93, 0x54, 0x26, 0xde, 0x85, 0x52,
	0x32, 0x73, 0xba, 0x67, 0x7e, 0x79, 0x8a, 0x6b, 0xad, 0x5d, 0xa9, 0xd5, 0x3d, 0xf3, 0x85, 0xdc,
	0xec, 0x18, 0x86, 0xef, 0x40, 0x31, 0xde, 0x40, 0xd3, 0x65, 0x2e, 0xef, 0xc0, 0x19, 0x02, 0x02,
	0x8a, 0x90, 0xca, 0x87, 0x30, 0x37, 0x51, 0x51, 0x74, 0xce, 0xcf, 0xbd, 0x73, 0xee, 0xe6, 0x14,
	0x89, 0x86, 0x78, 0x11, 0xa6, 0xbe, 0x72, 0x8f, 0x4e, 0x85, 0x4d, 0x0a, 0x11, 0x93, 0x87, 0xf2,
	0xfb, 0x52, 0xe5, 0x63, 0xc0, 0xd9, 0x22, 0xae, 0xa3, 0x50, 0x9b, 0x87, 0xd8, 0x75, 0xa7, 0xe7,
	0xf6, 0x59, 0xd4, 0x1a, 0x35, 0x34, 0x72, 0x5d, 0xf7, 0x04, 0x92, 0x90, 0x28, 0x0b, 0x4e, 0x38,
	0x74, 0x21, 0xc3, 0xfc, 0x10, 0xf3, 0x18, 0x3b, 0xf2, 0x78, 0x57, 0x5d, 0xe7, 0xca, 0xe0, 0x77,
	0xa0, 0xb8, 0x15, 0xba, 0x87, 0x81, 0x6f, 0xb8, 0xe1, 0xc1, 0x80, 0x97, 0x56, 0xdc, 0x2c, 0x25,
	0x09, 0x11, 0x4c, 0xd2, 0x14, 0xdc, 0x00, 0xb0, 0xfb, 0x87, 0x5e, 0x28, 0x12, 0x94, 0xdc, 0x84,
	0x14, 0x03, 0xeb, 0x30, 0xbd, 0x7b, 0xe4, 0x9e, 0x47, 0x6f, 0x91, 0xe8, 0x8a, 0xfa, 0xe4, 0x49,
	0xa6, 0x8a, 0x6f, 0xc4, 0x54, 0x71, 0x90, 0xc3, 0xc4, 0xca, 0x43, 0x98, 0x49, 0x07, 0xae, 0x65,
	0xee, 0x01, 0x14, 0x75, 0xd3, 0x7e, 0xc5, 0xd7, 0x60, 0x15, 0x54, 0x6e, 0x9c, 0xfc, 0x32, 0xe3,
	0x78, 0x38, 0x5a, 0x5f, 0xf7, 0x58, 0x7c, 0x11, 0xa2, 0x61, 0xed, 0x07, 0x39, 0xbd, 0x0c, 0xc5,
	0x1f, 0x24, 0xbb, 0x96, 0xf8, 0xae, 0xef, 0x24, 0x5a, 0x29, 0x5e, 0x43, 0xf7, 0x98, 0xe0, 0x8d,
	0x36, 0x8b, 0xcd, 0xb1, 0x9b, 0x24, 0xde, 0xef, 0xd5, 0xfc, 0xec, 0x4b, 0x2e, 0x52, 0x65, 0x1f,
	0x6e, 0x8d, 0xc4, 0xff, 0xa7, 0x5d, 0xbf, 0xe6, 0xcd, 0xa9, 0xdd, 0x87, 0x79, 0xc3, 0x32, 0xb5,
	0x8e, 0xf3, 0xca, 0x07, 0x54, 0xfb, 0x59, 0xce, 0xe6, 0xd0, 0x2b, 0xb6, 0xf7, 0x05, 0x20, 0x61,
	0x43, 0xc6, 0xd6, 0xfb, 0xa9, 0xbe, 0x9d, 0x14, 0x6d, 0x4c, 0xe6, 0x08, 0x8b, 0x33, 0x52, 0x78,
	0x7b, 0xec, 0xbc, 0x14, 0x2e, 0x7c, 0xef, 0x32, 0xe1, 0xcb, 0x4e, 0xcd, 0x80, 0xa5, 0xdc, 0x75,
	0xaf, 0xf5, 0x22, 0xbd, 0xe6, 0xb1, 0x74, 0x60, 0x71, 0xd7, 0xd2, 0x3e, 0x33, 0x09, 0xe5, 0x25,
	0x5b, 0x6d, 0x6a, 0x73, 0x97, 0x1f, 0xc0, 0xf4, 0xc9, 0x58, 0x4f, 0xdf, 0x4e, 0x76, 0x19, 0xbb,
	0x4d, 0x59, 0x10, 0xba, 0x87, 0x5e, 0xf4, 0xac, 0x92, 0x21, 0x79, 0xfd, 0x27, 0x19, 0x0a, 0x56,
	0xab, 0xb9, 0x43, 0xb7, 0x70, 0x09, 0x60, 0xaf, 0xb3, 0xdd, 0xe9, 0xf6, 0x22, 0x65, 0x74, 0x03,
	0xbf, 0x09, 0x4b, 0x06, 0x75, 0xb2, 0x5f, 0x4b, 0xe8, 0x97, 0x0b, 0x35, 0x0a, 0x52, 0x23, 0x1b,
	0xa4, 0xe8, 0x57, 0x11, 0x34, 0xa8, 0x93, 0xfd, 0xbb, 0x47, 0xbf, 0x8d, 0x32, 0xb3, 0xff, 0xdf,
	0xe8, 0xf7, 0x0b, 0x15, 0x2f, 0x42, 0xc9, 0xa0, 0xe9, 0x96, 0x43, 0x7f, 0x08, 0x94, 0x1a, 0xe9,
	0x63, 0x42, 0x7f, 0x5e, 0xa8, 0xb8, 0x02, 0x8b, 0x06, 0x75, 0x32, 0x4d, 0x8a, 0xfe, 0x12, 0x31,
	0x6a, 0x64, 0x62, 0x14, 0xfd, 0x7d, 0xa1, 0xe2, 0xb7, 0x60, 0xc5, 0xa0, 0x4e, 0x8e, 0x8b, 0x8f,
	0xd0, 0x3f, 0x22, 0x4c, 0x8d, 0xbc, 0x30, 0x45, 0xdf, 0xbc, 0x50, 0xf1, 0x1a, 0xdc, 0xa5, 0x86,
	0x73, 0xd5, 0xe7, 0x03, 0xfa, 0xf6, 0x85, 0xba, 0xfe, 0x39, 0x4c, 0xc7, 0x97, 0x14, 0x2f, 0xc0,
	0x5c, 0xa4, 0x14, 0x8d, 0x9d, 0x3d, 0xff, 0xb9, 0x1f, 0x9c, 0xa1, 0x1b, 0x63, 0x60, 0x93, 0x68,
	0x5b, 0xdd, 0x0e, 0x92, 0x30, 0x86, 0xd2, 0x08, 0xb4, 0xdb, 0x5b, 0x26, 0x41, 0xf2, 0x18, 0xb6,
	0x6b, 0x6a, 0x86, 0x89, 0x94, 0xf5, 0xef, 0x24, 0x98, 0x1d, 0xfb, 0x7e, 0xc0, 0x6f, 0xc0, 0x52,
	0xc4, 0x4a, 0x90, 0x64, 0xa5, 0x15, 0x58, 0x98, 0x08, 0xf5, 0xb4, 0xb6, 0x8d, 0x24, 0xbc, 0x0c,
	0x78, 0x22, 0xa0, 0x9b, 0x36, 0x92, 0x73, 0x12, 0xa8, 0xdd, 0xdd, 0x45, 0x4a, 0xce, 0x22, 0xd4,
	0xb4, 0x6d, 0xcb, 0x44, 0xaa, 0x3e, 0xf7, 0x64, 0x36, 0x0c, 0x02, 0xb6, 0x31, 0xec, 0xbb, 0xfd,
	0x02, 0x1f, 0xbd, 0xfb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x40, 0x62, 0xb1, 0xa7, 0x0b,
	0x00, 0x00,
}
