// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/server/server_proto.proto

/*
Package inner is a generated protocol buffer package.

It is generated from these files:
	protobuf/server/server_proto.proto

It has these top-level messages:
	SQL_SYNTAX
	ALL_ACCOUNT_RESP
	ALL_WATER_LINE
	ALL_ROOM_BONUS
	ALL_EMAIL_RESP
	SAVE_ACCOUNT
	SAVE_EMAIL_PERSON
	SAVE_WATER_LINE
	SAVE_ROOM_BONUS
	GAME_CONNECT_HALL
	ROOM_INFO
	SERVERFEE_LOG
	NOTIFY_ALTER_DATE
	MONEYCHANGE
	PLAYER_DATA_REQ
	PLAYER_DATA_RES
	PLAYER_ENTER_ROOM
	PLAYER_LEAVE_ROOM
	ROOM_BONUS_REQ
	ROOM_BONUS_RES
	ROOM_BONUS_SAVE
*/
package inner

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protomsg "root/protomsg"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SERVERMSG int32

const (
	SERVERMSG_UNKNOW               SERVERMSG = 0
	SERVERMSG_HD_HELLO_DB          SERVERMSG = 100
	SERVERMSG_SS_TEST_NETWORK      SERVERMSG = 101
	SERVERMSG_SS_CLOSE_SERVER      SERVERMSG = 102
	SERVERMSG_SS_RELOAD_CONFIG     SERVERMSG = 103
	SERVERMSG_HD_ALL_DATA          SERVERMSG = 105
	SERVERMSG_DH_ALL_ACCOUNT_RESP  SERVERMSG = 106
	SERVERMSG_DH_ALL_EMAIL_RESP    SERVERMSG = 107
	SERVERMSG_DH_ALL_WATER_LINE    SERVERMSG = 108
	SERVERMSG_DH_ALL_ROOM_BONUS    SERVERMSG = 109
	SERVERMSG_DH_FINISH_DATA       SERVERMSG = 120
	SERVERMSG_HD_SQL_SYNTAX        SERVERMSG = 131
	SERVERMSG_HD_SAVE_ACCOUNT      SERVERMSG = 135
	SERVERMSG_HD_SAVE_EMAIL_PERSON SERVERMSG = 136
	SERVERMSG_HD_SAVE_WATER_LINE   SERVERMSG = 137
	SERVERMSG_HD_SAVE_ROOM_BONUS   SERVERMSG = 138
	SERVERMSG_HD_SAVE_ALL          SERVERMSG = 150
	SERVERMSG_GH_GAME_CONNECT_HALL SERVERMSG = 170
	SERVERMSG_GH_ROOM_INFO         SERVERMSG = 171
	SERVERMSG_HG_ROOM_WATER_PROFIT SERVERMSG = 172
	SERVERMSG_GH_SERVERFEE_LOG     SERVERMSG = 175
	SERVERMSG_HG_NOTIFY_ALTER_DATE SERVERMSG = 176
	SERVERMSG_GH_MONEYCHANGE       SERVERMSG = 177
	SERVERMSG_HG_PLAYER_DATA_REQ   SERVERMSG = 180
	SERVERMSG_GH_PLAYER_DATA_RES   SERVERMSG = 181
	SERVERMSG_GH_PLAYER_ENTER_ROOM SERVERMSG = 182
	SERVERMSG_GH_PLAYER_LEAVE_ROOM SERVERMSG = 183
	SERVERMSG_GH_ROOM_BONUS_REQ    SERVERMSG = 185
	SERVERMSG_HG_ROOM_BONUS_RES    SERVERMSG = 186
	SERVERMSG_GH_ROOM_BONUS_SAVE   SERVERMSG = 187
)

var SERVERMSG_name = map[int32]string{
	0:   "UNKNOW",
	100: "HD_HELLO_DB",
	101: "SS_TEST_NETWORK",
	102: "SS_CLOSE_SERVER",
	103: "SS_RELOAD_CONFIG",
	105: "HD_ALL_DATA",
	106: "DH_ALL_ACCOUNT_RESP",
	107: "DH_ALL_EMAIL_RESP",
	108: "DH_ALL_WATER_LINE",
	109: "DH_ALL_ROOM_BONUS",
	120: "DH_FINISH_DATA",
	131: "HD_SQL_SYNTAX",
	135: "HD_SAVE_ACCOUNT",
	136: "HD_SAVE_EMAIL_PERSON",
	137: "HD_SAVE_WATER_LINE",
	138: "HD_SAVE_ROOM_BONUS",
	150: "HD_SAVE_ALL",
	170: "GH_GAME_CONNECT_HALL",
	171: "GH_ROOM_INFO",
	172: "HG_ROOM_WATER_PROFIT",
	175: "GH_SERVERFEE_LOG",
	176: "HG_NOTIFY_ALTER_DATE",
	177: "GH_MONEYCHANGE",
	180: "HG_PLAYER_DATA_REQ",
	181: "GH_PLAYER_DATA_RES",
	182: "GH_PLAYER_ENTER_ROOM",
	183: "GH_PLAYER_LEAVE_ROOM",
	185: "GH_ROOM_BONUS_REQ",
	186: "HG_ROOM_BONUS_RES",
	187: "GH_ROOM_BONUS_SAVE",
}
var SERVERMSG_value = map[string]int32{
	"UNKNOW":               0,
	"HD_HELLO_DB":          100,
	"SS_TEST_NETWORK":      101,
	"SS_CLOSE_SERVER":      102,
	"SS_RELOAD_CONFIG":     103,
	"HD_ALL_DATA":          105,
	"DH_ALL_ACCOUNT_RESP":  106,
	"DH_ALL_EMAIL_RESP":    107,
	"DH_ALL_WATER_LINE":    108,
	"DH_ALL_ROOM_BONUS":    109,
	"DH_FINISH_DATA":       120,
	"HD_SQL_SYNTAX":        131,
	"HD_SAVE_ACCOUNT":      135,
	"HD_SAVE_EMAIL_PERSON": 136,
	"HD_SAVE_WATER_LINE":   137,
	"HD_SAVE_ROOM_BONUS":   138,
	"HD_SAVE_ALL":          150,
	"GH_GAME_CONNECT_HALL": 170,
	"GH_ROOM_INFO":         171,
	"HG_ROOM_WATER_PROFIT": 172,
	"GH_SERVERFEE_LOG":     175,
	"HG_NOTIFY_ALTER_DATE": 176,
	"GH_MONEYCHANGE":       177,
	"HG_PLAYER_DATA_REQ":   180,
	"GH_PLAYER_DATA_RES":   181,
	"GH_PLAYER_ENTER_ROOM": 182,
	"GH_PLAYER_LEAVE_ROOM": 183,
	"GH_ROOM_BONUS_REQ":    185,
	"HG_ROOM_BONUS_RES":    186,
	"GH_ROOM_BONUS_SAVE":   187,
}

func (x SERVERMSG) String() string {
	return proto.EnumName(SERVERMSG_name, int32(x))
}
func (SERVERMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 发送到db执行 sql syntax
type SQL_SYNTAX struct {
	DataBaseType uint32 `protobuf:"varint,1,opt,name=DataBaseType" json:"DataBaseType,omitempty"`
	SQLSyntax    string `protobuf:"bytes,2,opt,name=SQLSyntax" json:"SQLSyntax,omitempty"`
}

func (m *SQL_SYNTAX) Reset()                    { *m = SQL_SYNTAX{} }
func (m *SQL_SYNTAX) String() string            { return proto.CompactTextString(m) }
func (*SQL_SYNTAX) ProtoMessage()               {}
func (*SQL_SYNTAX) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SQL_SYNTAX) GetDataBaseType() uint32 {
	if m != nil {
		return m.DataBaseType
	}
	return 0
}

func (m *SQL_SYNTAX) GetSQLSyntax() string {
	if m != nil {
		return m.SQLSyntax
	}
	return ""
}

// 请求账号信息
type ALL_ACCOUNT_RESP struct {
	AllAccount []*protomsg.AccountStorageData `protobuf:"bytes,1,rep,name=AllAccount" json:"AllAccount,omitempty"`
}

func (m *ALL_ACCOUNT_RESP) Reset()                    { *m = ALL_ACCOUNT_RESP{} }
func (m *ALL_ACCOUNT_RESP) String() string            { return proto.CompactTextString(m) }
func (*ALL_ACCOUNT_RESP) ProtoMessage()               {}
func (*ALL_ACCOUNT_RESP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ALL_ACCOUNT_RESP) GetAllAccount() []*protomsg.AccountStorageData {
	if m != nil {
		return m.AllAccount
	}
	return nil
}

// db返回所有水位线
type ALL_WATER_LINE struct {
	Line []*SAVE_WATER_LINE `protobuf:"bytes,1,rep,name=Line" json:"Line,omitempty"`
}

func (m *ALL_WATER_LINE) Reset()                    { *m = ALL_WATER_LINE{} }
func (m *ALL_WATER_LINE) String() string            { return proto.CompactTextString(m) }
func (*ALL_WATER_LINE) ProtoMessage()               {}
func (*ALL_WATER_LINE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ALL_WATER_LINE) GetLine() []*SAVE_WATER_LINE {
	if m != nil {
		return m.Line
	}
	return nil
}

// db返回所有房间水池
type ALL_ROOM_BONUS struct {
	Bonus []*SAVE_ROOM_BONUS `protobuf:"bytes,1,rep,name=Bonus" json:"Bonus,omitempty"`
}

func (m *ALL_ROOM_BONUS) Reset()                    { *m = ALL_ROOM_BONUS{} }
func (m *ALL_ROOM_BONUS) String() string            { return proto.CompactTextString(m) }
func (*ALL_ROOM_BONUS) ProtoMessage()               {}
func (*ALL_ROOM_BONUS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ALL_ROOM_BONUS) GetBonus() []*SAVE_ROOM_BONUS {
	if m != nil {
		return m.Bonus
	}
	return nil
}

// 请求邮件信息
type ALL_EMAIL_RESP struct {
	AcccountMail []*SAVE_EMAIL_PERSON `protobuf:"bytes,1,rep,name=AcccountMail" json:"AcccountMail,omitempty"`
}

func (m *ALL_EMAIL_RESP) Reset()                    { *m = ALL_EMAIL_RESP{} }
func (m *ALL_EMAIL_RESP) String() string            { return proto.CompactTextString(m) }
func (*ALL_EMAIL_RESP) ProtoMessage()               {}
func (*ALL_EMAIL_RESP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ALL_EMAIL_RESP) GetAcccountMail() []*SAVE_EMAIL_PERSON {
	if m != nil {
		return m.AcccountMail
	}
	return nil
}

// 回存玩家
type SAVE_ACCOUNT struct {
	AccData *protomsg.AccountStorageData `protobuf:"bytes,1,opt,name=AccData" json:"AccData,omitempty"`
}

func (m *SAVE_ACCOUNT) Reset()                    { *m = SAVE_ACCOUNT{} }
func (m *SAVE_ACCOUNT) String() string            { return proto.CompactTextString(m) }
func (*SAVE_ACCOUNT) ProtoMessage()               {}
func (*SAVE_ACCOUNT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SAVE_ACCOUNT) GetAccData() *protomsg.AccountStorageData {
	if m != nil {
		return m.AccData
	}
	return nil
}

// 回存邮件
type SAVE_EMAIL_PERSON struct {
	AccountId uint32            `protobuf:"varint,1,opt,name=AccountId" json:"AccountId,omitempty"`
	Emails    []*protomsg.Email `protobuf:"bytes,2,rep,name=Emails" json:"Emails,omitempty"`
}

func (m *SAVE_EMAIL_PERSON) Reset()                    { *m = SAVE_EMAIL_PERSON{} }
func (m *SAVE_EMAIL_PERSON) String() string            { return proto.CompactTextString(m) }
func (*SAVE_EMAIL_PERSON) ProtoMessage()               {}
func (*SAVE_EMAIL_PERSON) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SAVE_EMAIL_PERSON) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *SAVE_EMAIL_PERSON) GetEmails() []*protomsg.Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

// 回存水位线
type SAVE_WATER_LINE struct {
	RoomID    uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	WaterLine string `protobuf:"bytes,2,opt,name=WaterLine" json:"WaterLine,omitempty"`
}

func (m *SAVE_WATER_LINE) Reset()                    { *m = SAVE_WATER_LINE{} }
func (m *SAVE_WATER_LINE) String() string            { return proto.CompactTextString(m) }
func (*SAVE_WATER_LINE) ProtoMessage()               {}
func (*SAVE_WATER_LINE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SAVE_WATER_LINE) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *SAVE_WATER_LINE) GetWaterLine() string {
	if m != nil {
		return m.WaterLine
	}
	return ""
}

// 水池
type SAVE_ROOM_BONUS struct {
	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *SAVE_ROOM_BONUS) Reset()                    { *m = SAVE_ROOM_BONUS{} }
func (m *SAVE_ROOM_BONUS) String() string            { return proto.CompactTextString(m) }
func (*SAVE_ROOM_BONUS) ProtoMessage()               {}
func (*SAVE_ROOM_BONUS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SAVE_ROOM_BONUS) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *SAVE_ROOM_BONUS) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// 游戏连接大厅 170
type GAME_CONNECT_HALL struct {
	ServerID uint32 `protobuf:"varint,1,opt,name=ServerID" json:"ServerID,omitempty"`
	GameType uint32 `protobuf:"varint,2,opt,name=GameType" json:"GameType,omitempty"`
}

func (m *GAME_CONNECT_HALL) Reset()                    { *m = GAME_CONNECT_HALL{} }
func (m *GAME_CONNECT_HALL) String() string            { return proto.CompactTextString(m) }
func (*GAME_CONNECT_HALL) ProtoMessage()               {}
func (*GAME_CONNECT_HALL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GAME_CONNECT_HALL) GetServerID() uint32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *GAME_CONNECT_HALL) GetGameType() uint32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

// 游戏上报房间信息给大厅 171
type ROOM_INFO struct {
	ServerID uint32   `protobuf:"varint,1,opt,name=ServerID" json:"ServerID,omitempty"`
	RoomsID  []uint32 `protobuf:"varint,2,rep,packed,name=RoomsID" json:"RoomsID,omitempty"`
}

func (m *ROOM_INFO) Reset()                    { *m = ROOM_INFO{} }
func (m *ROOM_INFO) String() string            { return proto.CompactTextString(m) }
func (*ROOM_INFO) ProtoMessage()               {}
func (*ROOM_INFO) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ROOM_INFO) GetServerID() uint32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *ROOM_INFO) GetRoomsID() []uint32 {
	if m != nil {
		return m.RoomsID
	}
	return nil
}

// 回存服务费 175
type SERVERFEE_LOG struct {
	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	ServerFee uint32 `protobuf:"varint,2,opt,name=ServerFee" json:"ServerFee,omitempty"`
	GameType  uint32 `protobuf:"varint,3,opt,name=GameType" json:"GameType,omitempty"`
	Time      string `protobuf:"bytes,4,opt,name=Time" json:"Time,omitempty"`
	RoomID    uint32 `protobuf:"varint,5,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *SERVERFEE_LOG) Reset()                    { *m = SERVERFEE_LOG{} }
func (m *SERVERFEE_LOG) String() string            { return proto.CompactTextString(m) }
func (*SERVERFEE_LOG) ProtoMessage()               {}
func (*SERVERFEE_LOG) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SERVERFEE_LOG) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *SERVERFEE_LOG) GetServerFee() uint32 {
	if m != nil {
		return m.ServerFee
	}
	return 0
}

func (m *SERVERFEE_LOG) GetGameType() uint32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *SERVERFEE_LOG) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *SERVERFEE_LOG) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 大厅通知游戏，修改玩家数据 176
type NOTIFY_ALTER_DATE struct {
	AccountID   uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	Type        int32  `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	AlterValue  int64  `protobuf:"varint,3,opt,name=AlterValue" json:"AlterValue,omitempty"`
	RoomID      uint32 `protobuf:"varint,4,opt,name=RoomID" json:"RoomID,omitempty"`
	OperateType int32  `protobuf:"varint,5,opt,name=operateType" json:"operateType,omitempty"`
}

func (m *NOTIFY_ALTER_DATE) Reset()                    { *m = NOTIFY_ALTER_DATE{} }
func (m *NOTIFY_ALTER_DATE) String() string            { return proto.CompactTextString(m) }
func (*NOTIFY_ALTER_DATE) ProtoMessage()               {}
func (*NOTIFY_ALTER_DATE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *NOTIFY_ALTER_DATE) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *NOTIFY_ALTER_DATE) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NOTIFY_ALTER_DATE) GetAlterValue() int64 {
	if m != nil {
		return m.AlterValue
	}
	return 0
}

func (m *NOTIFY_ALTER_DATE) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *NOTIFY_ALTER_DATE) GetOperateType() int32 {
	if m != nil {
		return m.OperateType
	}
	return 0
}

// 游戏改变金币，通知大厅 177
type MONEYCHANGE struct {
	AccountID   uint32 `protobuf:"varint,1,opt,name=AccountID" json:"AccountID,omitempty"`
	ChangeValue int64  `protobuf:"varint,2,opt,name=ChangeValue" json:"ChangeValue,omitempty"`
	Value       int64  `protobuf:"varint,3,opt,name=Value" json:"Value,omitempty"`
	Operate     uint32 `protobuf:"varint,4,opt,name=Operate" json:"Operate,omitempty"`
	Time        string `protobuf:"bytes,6,opt,name=Time" json:"Time,omitempty"`
	RoomID      uint32 `protobuf:"varint,7,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *MONEYCHANGE) Reset()                    { *m = MONEYCHANGE{} }
func (m *MONEYCHANGE) String() string            { return proto.CompactTextString(m) }
func (*MONEYCHANGE) ProtoMessage()               {}
func (*MONEYCHANGE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MONEYCHANGE) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *MONEYCHANGE) GetChangeValue() int64 {
	if m != nil {
		return m.ChangeValue
	}
	return 0
}

func (m *MONEYCHANGE) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MONEYCHANGE) GetOperate() uint32 {
	if m != nil {
		return m.Operate
	}
	return 0
}

func (m *MONEYCHANGE) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *MONEYCHANGE) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 大厅给游戏发送玩家数据
type PLAYER_DATA_REQ struct {
	Account     *protomsg.AccountStorageData `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	AccountData *protomsg.AccountGameData    `protobuf:"bytes,2,opt,name=AccountData" json:"AccountData,omitempty"`
	RoomID      uint32                       `protobuf:"varint,3,opt,name=RoomID" json:"RoomID,omitempty"`
	Reback      bool                         `protobuf:"varint,4,opt,name=reback" json:"reback,omitempty"`
}

func (m *PLAYER_DATA_REQ) Reset()                    { *m = PLAYER_DATA_REQ{} }
func (m *PLAYER_DATA_REQ) String() string            { return proto.CompactTextString(m) }
func (*PLAYER_DATA_REQ) ProtoMessage()               {}
func (*PLAYER_DATA_REQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PLAYER_DATA_REQ) GetAccount() *protomsg.AccountStorageData {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *PLAYER_DATA_REQ) GetAccountData() *protomsg.AccountGameData {
	if m != nil {
		return m.AccountData
	}
	return nil
}

func (m *PLAYER_DATA_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *PLAYER_DATA_REQ) GetReback() bool {
	if m != nil {
		return m.Reback
	}
	return false
}

// 游戏回复大厅，收到玩家数据，大厅通知玩家进入
type PLAYER_DATA_RES struct {
	Ret       uint32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	AccountID uint32 `protobuf:"varint,2,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,3,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *PLAYER_DATA_RES) Reset()                    { *m = PLAYER_DATA_RES{} }
func (m *PLAYER_DATA_RES) String() string            { return proto.CompactTextString(m) }
func (*PLAYER_DATA_RES) ProtoMessage()               {}
func (*PLAYER_DATA_RES) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PLAYER_DATA_RES) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *PLAYER_DATA_RES) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *PLAYER_DATA_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 游戏通知大厅，玩家进入房间
type PLAYER_ENTER_ROOM struct {
	AccountID uint32 `protobuf:"varint,2,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,3,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *PLAYER_ENTER_ROOM) Reset()                    { *m = PLAYER_ENTER_ROOM{} }
func (m *PLAYER_ENTER_ROOM) String() string            { return proto.CompactTextString(m) }
func (*PLAYER_ENTER_ROOM) ProtoMessage()               {}
func (*PLAYER_ENTER_ROOM) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PLAYER_ENTER_ROOM) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *PLAYER_ENTER_ROOM) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 游戏通知大厅，玩家退出房间
type PLAYER_LEAVE_ROOM struct {
	AccountID uint32 `protobuf:"varint,2,opt,name=AccountID" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,3,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *PLAYER_LEAVE_ROOM) Reset()                    { *m = PLAYER_LEAVE_ROOM{} }
func (m *PLAYER_LEAVE_ROOM) String() string            { return proto.CompactTextString(m) }
func (*PLAYER_LEAVE_ROOM) ProtoMessage()               {}
func (*PLAYER_LEAVE_ROOM) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PLAYER_LEAVE_ROOM) GetAccountID() uint32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *PLAYER_LEAVE_ROOM) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// 请求房间水池金额 185
type ROOM_BONUS_REQ struct {
	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
}

func (m *ROOM_BONUS_REQ) Reset()                    { *m = ROOM_BONUS_REQ{} }
func (m *ROOM_BONUS_REQ) String() string            { return proto.CompactTextString(m) }
func (*ROOM_BONUS_REQ) ProtoMessage()               {}
func (*ROOM_BONUS_REQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ROOM_BONUS_REQ) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type ROOM_BONUS_RES struct {
	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *ROOM_BONUS_RES) Reset()                    { *m = ROOM_BONUS_RES{} }
func (m *ROOM_BONUS_RES) String() string            { return proto.CompactTextString(m) }
func (*ROOM_BONUS_RES) ProtoMessage()               {}
func (*ROOM_BONUS_RES) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ROOM_BONUS_RES) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ROOM_BONUS_RES) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// 回存房间水池金额
type ROOM_BONUS_SAVE struct {
	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *ROOM_BONUS_SAVE) Reset()                    { *m = ROOM_BONUS_SAVE{} }
func (m *ROOM_BONUS_SAVE) String() string            { return proto.CompactTextString(m) }
func (*ROOM_BONUS_SAVE) ProtoMessage()               {}
func (*ROOM_BONUS_SAVE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ROOM_BONUS_SAVE) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ROOM_BONUS_SAVE) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*SQL_SYNTAX)(nil), "protomsg.SQL_SYNTAX")
	proto.RegisterType((*ALL_ACCOUNT_RESP)(nil), "protomsg.ALL_ACCOUNT_RESP")
	proto.RegisterType((*ALL_WATER_LINE)(nil), "protomsg.ALL_WATER_LINE")
	proto.RegisterType((*ALL_ROOM_BONUS)(nil), "protomsg.ALL_ROOM_BONUS")
	proto.RegisterType((*ALL_EMAIL_RESP)(nil), "protomsg.ALL_EMAIL_RESP")
	proto.RegisterType((*SAVE_ACCOUNT)(nil), "protomsg.SAVE_ACCOUNT")
	proto.RegisterType((*SAVE_EMAIL_PERSON)(nil), "protomsg.SAVE_EMAIL_PERSON")
	proto.RegisterType((*SAVE_WATER_LINE)(nil), "protomsg.SAVE_WATER_LINE")
	proto.RegisterType((*SAVE_ROOM_BONUS)(nil), "protomsg.SAVE_ROOM_BONUS")
	proto.RegisterType((*GAME_CONNECT_HALL)(nil), "protomsg.GAME_CONNECT_HALL")
	proto.RegisterType((*ROOM_INFO)(nil), "protomsg.ROOM_INFO")
	proto.RegisterType((*SERVERFEE_LOG)(nil), "protomsg.SERVERFEE_LOG")
	proto.RegisterType((*NOTIFY_ALTER_DATE)(nil), "protomsg.NOTIFY_ALTER_DATE")
	proto.RegisterType((*MONEYCHANGE)(nil), "protomsg.MONEYCHANGE")
	proto.RegisterType((*PLAYER_DATA_REQ)(nil), "protomsg.PLAYER_DATA_REQ")
	proto.RegisterType((*PLAYER_DATA_RES)(nil), "protomsg.PLAYER_DATA_RES")
	proto.RegisterType((*PLAYER_ENTER_ROOM)(nil), "protomsg.PLAYER_ENTER_ROOM")
	proto.RegisterType((*PLAYER_LEAVE_ROOM)(nil), "protomsg.PLAYER_LEAVE_ROOM")
	proto.RegisterType((*ROOM_BONUS_REQ)(nil), "protomsg.ROOM_BONUS_REQ")
	proto.RegisterType((*ROOM_BONUS_RES)(nil), "protomsg.ROOM_BONUS_RES")
	proto.RegisterType((*ROOM_BONUS_SAVE)(nil), "protomsg.ROOM_BONUS_SAVE")
	proto.RegisterEnum("protomsg.SERVERMSG", SERVERMSG_name, SERVERMSG_value)
}

func init() { proto.RegisterFile("protobuf/server/server_proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1072 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0x4d, 0x93, 0xb6, 0x27, 0x6d, 0x33, 0x99, 0x5e, 0x36, 0x5d, 0x56, 0xa8, 0xf2, 0x0b,
	0x15, 0x12, 0xad, 0x04, 0x12, 0x2f, 0x20, 0x2a, 0x37, 0x9e, 0xd8, 0x56, 0x1d, 0xbb, 0x1d, 0xbb,
	0x2d, 0xdd, 0x97, 0x91, 0x9b, 0x7a, 0x4b, 0xd8, 0x5c, 0xaa, 0xc4, 0x45, 0xbb, 0xcf, 0x3c, 0x70,
	0x79, 0x45, 0xe2, 0x95, 0x67, 0x2e, 0x12, 0x20, 0xb1, 0x8b, 0x80, 0x3f, 0x87, 0xe6, 0xe2, 0xf8,
	0x52, 0x4a, 0x59, 0x78, 0x69, 0x3c, 0xe7, 0x9c, 0xf9, 0xce, 0x37, 0xdf, 0x99, 0x73, 0xa6, 0xa0,
	0x5f, 0x4f, 0xc6, 0xc9, 0xf8, 0xe2, 0xe6, 0xc9, 0xde, 0x34, 0x9e, 0x7c, 0x1a, 0x4f, 0xd4, 0x0f,
	0x13, 0xe6, 0x5d, 0xf1, 0x17, 0x2f, 0x8a, 0x9f, 0xe1, 0xf4, 0xea, 0xe1, 0xda, 0x2c, 0xfa, 0x32,
	0x4a, 0x22, 0xe9, 0xd6, 0x3d, 0x80, 0xe0, 0xd8, 0x65, 0xc1, 0xb9, 0x17, 0x1a, 0x1f, 0x61, 0x1d,
	0x96, 0xcd, 0x28, 0x89, 0x0e, 0xa2, 0x69, 0x1c, 0x3e, 0xbf, 0x8e, 0x5b, 0xda, 0xb6, 0xb6, 0xb3,
	0x42, 0x0b, 0x36, 0xfc, 0x08, 0x96, 0x82, 0x63, 0x37, 0x78, 0x3e, 0x4a, 0xa2, 0x67, 0xad, 0xb9,
	0x6d, 0x6d, 0x67, 0x89, 0x66, 0x06, 0xfd, 0x08, 0x90, 0xe1, 0xba, 0xcc, 0x68, 0xb7, 0xfd, 0x13,
	0x2f, 0x64, 0x94, 0x04, 0x47, 0xf8, 0x03, 0x00, 0x63, 0x30, 0x30, 0x7a, 0xbd, 0xf1, 0xcd, 0x28,
	0x69, 0x69, 0xdb, 0x95, 0x9d, 0xfa, 0x3b, 0x8f, 0x76, 0x53, 0x5e, 0xbb, 0xca, 0x11, 0x24, 0xe3,
	0x49, 0x74, 0x15, 0xf3, 0x5c, 0x34, 0x17, 0xaf, 0xef, 0xc3, 0x2a, 0x47, 0x3c, 0x33, 0x42, 0x42,
	0x99, 0xeb, 0x78, 0x04, 0xbf, 0x0d, 0xf3, 0x6e, 0x7f, 0x14, 0x2b, 0xa4, 0xad, 0x0c, 0x29, 0x30,
	0x4e, 0x49, 0x2e, 0x90, 0x8a, 0x30, 0xdd, 0x90, 0x00, 0xd4, 0xf7, 0xbb, 0xec, 0xc0, 0xf7, 0x4e,
	0x02, 0xbc, 0x07, 0xd5, 0x83, 0xf1, 0xe8, 0x66, 0x7a, 0x07, 0x42, 0x16, 0x49, 0x65, 0x9c, 0x7e,
	0x2c, 0x21, 0x48, 0xd7, 0x70, 0x5c, 0x79, 0xa6, 0x7d, 0x58, 0x36, 0x7a, 0x92, 0x61, 0x37, 0xea,
	0x0f, 0x14, 0xd2, 0xeb, 0x25, 0x24, 0xb9, 0xe1, 0x88, 0xd0, 0xc0, 0xf7, 0x68, 0x61, 0x83, 0xde,
	0x81, 0x65, 0x11, 0xa2, 0x94, 0xc2, 0xef, 0xc1, 0x82, 0xd1, 0xeb, 0xf1, 0xd3, 0x0b, 0xd5, 0xef,
	0x53, 0x28, 0x0d, 0xd6, 0x1f, 0x43, 0xf3, 0x56, 0x2a, 0x5e, 0x23, 0xb5, 0xc7, 0xb9, 0x54, 0x45,
	0xcc, 0x0c, 0xf8, 0x4d, 0xa8, 0x91, 0x61, 0xd4, 0x1f, 0x4c, 0x5b, 0x73, 0x82, 0x75, 0x23, 0xcb,
	0x24, 0xec, 0x54, 0xb9, 0x75, 0x0b, 0x1a, 0x25, 0x49, 0xf1, 0x26, 0xd4, 0xe8, 0x78, 0x3c, 0x74,
	0x4c, 0x05, 0xab, 0x56, 0x3c, 0xe3, 0x59, 0x94, 0xc4, 0x13, 0x51, 0x18, 0x75, 0x2b, 0x66, 0x06,
	0x7d, 0x5f, 0x01, 0xe5, 0x6a, 0x70, 0x17, 0xd0, 0x3a, 0x54, 0x4f, 0xa3, 0xc1, 0x4d, 0x0a, 0x22,
	0x17, 0xfa, 0x21, 0x34, 0x2d, 0xa3, 0x4b, 0x58, 0xdb, 0xf7, 0x3c, 0xd2, 0x0e, 0x99, 0x6d, 0xb8,
	0x2e, 0x7e, 0x08, 0x8b, 0x81, 0xb8, 0xf0, 0x33, 0x90, 0xd9, 0x9a, 0xfb, 0xac, 0x68, 0x28, 0x6f,
	0xf1, 0x9c, 0xf4, 0xa5, 0x6b, 0xdd, 0x80, 0x25, 0x41, 0xc4, 0xf1, 0x3a, 0xfe, 0x3f, 0x82, 0xb4,
	0x60, 0x81, 0xb3, 0x9a, 0x3a, 0xa6, 0x50, 0x6a, 0x85, 0xa6, 0x4b, 0xfd, 0x6b, 0x0d, 0x56, 0x02,
	0x42, 0x4f, 0x09, 0xed, 0x10, 0xc2, 0x5c, 0xdf, 0xca, 0x4b, 0x6e, 0x96, 0x25, 0x17, 0xf2, 0x48,
	0xd4, 0x4e, 0x9c, 0xf2, 0xc9, 0x0c, 0x05, 0xb2, 0x95, 0x22, 0x59, 0x8c, 0x61, 0x3e, 0xec, 0x0f,
	0xe3, 0xd6, 0xbc, 0x90, 0x43, 0x7c, 0xe7, 0xb4, 0xab, 0xe6, 0xb5, 0xd3, 0xbf, 0xd5, 0xa0, 0xe9,
	0xf9, 0xa1, 0xd3, 0x39, 0x67, 0x86, 0xcb, 0x4b, 0x66, 0x1a, 0x21, 0xb9, 0x87, 0x19, 0xc7, 0x4f,
	0x45, 0xaa, 0x52, 0xf1, 0x8d, 0xdf, 0xe0, 0x0d, 0x9b, 0xc4, 0x13, 0x59, 0x08, 0xce, 0xa8, 0x42,
	0x73, 0x96, 0x5c, 0xfe, 0xf9, 0x42, 0xed, 0xb6, 0xa1, 0x3e, 0xbe, 0x8e, 0x27, 0x51, 0x22, 0x8f,
	0x52, 0x15, 0x90, 0x79, 0x93, 0xfe, 0x9d, 0x06, 0xf5, 0xae, 0xef, 0x91, 0xf3, 0xb6, 0x6d, 0x78,
	0xd6, 0x7d, 0xdc, 0xb6, 0xa1, 0xde, 0xfe, 0x38, 0x1a, 0x5d, 0xc5, 0xd9, 0x8d, 0xa8, 0xd0, 0xbc,
	0x29, 0xbb, 0x2d, 0x92, 0xa4, 0x5c, 0xf0, 0xba, 0xf9, 0x32, 0xa9, 0x22, 0x98, 0x2e, 0x67, 0x6a,
	0xd6, 0xfe, 0x56, 0xcd, 0x85, 0x82, 0x9a, 0x2f, 0x35, 0x68, 0x1c, 0xb9, 0xc6, 0xb9, 0xd4, 0xd1,
	0x60, 0x94, 0x1c, 0xab, 0x2e, 0x55, 0x73, 0xec, 0xdf, 0x75, 0x29, 0xb7, 0xe1, 0xf7, 0xa1, 0xae,
	0x3e, 0x45, 0x87, 0xcf, 0x89, 0xbd, 0x5b, 0xb7, 0xf6, 0xf2, 0xaa, 0x8b, 0x8d, 0xf9, 0xe8, 0x1c,
	0xc1, 0x4a, 0x41, 0xee, 0x4d, 0xa8, 0x4d, 0xe2, 0x8b, 0xa8, 0xf7, 0x54, 0x9c, 0x72, 0x91, 0xaa,
	0x95, 0x7e, 0x5e, 0xe6, 0x1d, 0x60, 0x04, 0x15, 0x1a, 0x27, 0x4a, 0x61, 0xfe, 0x59, 0x54, 0x7e,
	0xae, 0xac, 0xfc, 0x1d, 0x29, 0x75, 0x07, 0x9a, 0x0a, 0x9a, 0x78, 0xfc, 0x82, 0xf1, 0x3e, 0xfa,
	0xdf, 0x50, 0x2e, 0x49, 0x67, 0xc3, 0x7f, 0x84, 0xda, 0x81, 0xd5, 0x6c, 0xb2, 0x88, 0x3a, 0xdd,
	0x31, 0x5d, 0xf4, 0x0f, 0x4b, 0x91, 0xaf, 0x3a, 0x87, 0xf6, 0xa1, 0x91, 0xdb, 0xcf, 0x67, 0xda,
	0xab, 0x01, 0xbc, 0xf5, 0xa2, 0x0a, 0x4b, 0x72, 0x70, 0x74, 0x03, 0x0b, 0x03, 0xd4, 0x4e, 0xbc,
	0x43, 0xcf, 0x3f, 0x43, 0xaf, 0xe1, 0x06, 0xd4, 0x6d, 0x93, 0xd9, 0xc4, 0x75, 0x7d, 0x66, 0x1e,
	0xa0, 0x4b, 0xbc, 0x06, 0x8d, 0x20, 0x60, 0x21, 0x09, 0x42, 0xe6, 0x91, 0xf0, 0xcc, 0xa7, 0x87,
	0x28, 0x56, 0xc6, 0xb6, 0xeb, 0x07, 0x84, 0x49, 0x1c, 0xf4, 0x04, 0xaf, 0x03, 0x0a, 0xf8, 0x69,
	0x5c, 0xdf, 0x30, 0xf9, 0x88, 0xec, 0x38, 0x16, 0xba, 0x52, 0x80, 0xfc, 0xdd, 0xe2, 0xd7, 0x00,
	0xf5, 0xf1, 0x03, 0x58, 0x33, 0x6d, 0x56, 0x7e, 0x9e, 0xd1, 0x27, 0x78, 0x03, 0x9a, 0xca, 0x91,
	0xbd, 0x70, 0xe8, 0x69, 0xce, 0x9c, 0x3d, 0x00, 0x68, 0x90, 0x33, 0x67, 0x52, 0xa0, 0x21, 0xc6,
	0xb0, 0x6a, 0xda, 0xac, 0xe3, 0x78, 0x4e, 0x60, 0xcb, 0x8c, 0xcf, 0x30, 0x86, 0x15, 0xdb, 0x64,
	0xd9, 0x3f, 0x18, 0xe8, 0x33, 0x0d, 0xaf, 0x43, 0x83, 0xdb, 0x72, 0x6f, 0x1f, 0xfa, 0x5c, 0xc3,
	0x5b, 0xb0, 0x9e, 0x5a, 0xf3, 0x2f, 0x19, 0xfa, 0x42, 0xc3, 0x0f, 0x00, 0xa7, 0xae, 0x1c, 0x8f,
	0x2f, 0x0b, 0x8e, 0x1c, 0x93, 0xaf, 0x34, 0x8c, 0xc4, 0xc9, 0x65, 0x0a, 0xd7, 0x45, 0xdf, 0x08,
	0x78, 0xcb, 0x66, 0xb7, 0x9e, 0x10, 0xf4, 0xbd, 0x86, 0x9b, 0xb0, 0x6c, 0xd9, 0x6c, 0xf6, 0x20,
	0xa0, 0x1f, 0x24, 0x19, 0x4b, 0x9a, 0x64, 0xc6, 0x23, 0xea, 0x77, 0x9c, 0x10, 0xfd, 0xa8, 0xe1,
	0x0d, 0x40, 0x96, 0xcd, 0x0a, 0xa3, 0x1f, 0xfd, 0x94, 0xee, 0xb8, 0x35, 0x7b, 0xd1, 0xcf, 0x1a,
	0x5e, 0x83, 0x55, 0xcb, 0x66, 0xb9, 0xa1, 0x87, 0x7e, 0x91, 0xd4, 0x2d, 0x56, 0x9a, 0x2e, 0xe8,
	0x57, 0xe1, 0xb0, 0xec, 0x92, 0x23, 0x40, 0x2f, 0xd2, 0x13, 0xdc, 0x6a, 0x3e, 0xf4, 0xb2, 0xe4,
	0xca, 0x9a, 0x09, 0xfd, 0xa6, 0xe1, 0x4d, 0x68, 0xa6, 0x87, 0x9b, 0x35, 0x07, 0xfa, 0x5d, 0xd8,
	0xd3, 0x13, 0xce, 0x5a, 0x01, 0xfd, 0x91, 0xa6, 0x2f, 0x5d, 0x71, 0xf4, 0xa7, 0x76, 0xb0, 0xf1,
	0x78, 0x6d, 0x32, 0x1e, 0x27, 0x7b, 0xe9, 0xc4, 0xda, 0xeb, 0x8f, 0x46, 0xf1, 0xe4, 0xa2, 0x26,
	0xd6, 0xef, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x33, 0xdf, 0x59, 0x8a, 0x0a, 0x00, 0x00,
}
