// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protobuf/server/server_proto.proto

package inner

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	protomsg "root/protomsg"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SERVERMSG int32

const (
	SERVERMSG_SERVERMSG_UNKNOW     SERVERMSG = 0
	SERVERMSG_HD_HELLO_DB          SERVERMSG = 100 // 大厅向db建立链接
	SERVERMSG_SS_TEST_NETWORK      SERVERMSG = 101 // 网络测试
	SERVERMSG_SS_CLOSE_SERVER      SERVERMSG = 102 // 关闭服务器消息
	SERVERMSG_GH_CLOSE_SERVER_FIN  SERVERMSG = 103 // 游戏通知大厅，关闭完成
	SERVERMSG_SS_RELOAD_CONFIG     SERVERMSG = 104 // 更新配置
	SERVERMSG_HD_ALL_DATA          SERVERMSG = 105 // 开服获取所有数据
	SERVERMSG_DH_ALL_ACCOUNT_RESP  SERVERMSG = 106 // db返回所有 账号 给大厅
	SERVERMSG_DH_ALL_EMAIL_RESP    SERVERMSG = 107 // db返回所有 邮件 给大厅
	SERVERMSG_DH_ALL_WATER_LINE    SERVERMSG = 108 // db返回所有水位线
	SERVERMSG_DH_ALL_ROOM_BONUS    SERVERMSG = 109 // db返回所有房间水池
	SERVERMSG_DH_FINISH_DATA       SERVERMSG = 120 // db通知大厅,所有数据发送完成
	SERVERMSG_HD_SQL_SYNTAX        SERVERMSG = 131 // 大厅发送sql语句给db执行
	SERVERMSG_HD_SAVE_ACCOUNT      SERVERMSG = 135 // 大厅回存玩家数据
	SERVERMSG_HD_SAVE_EMAIL_PERSON SERVERMSG = 136 // 通知DB回存玩家邮件
	SERVERMSG_HD_SAVE_WATER_LINE   SERVERMSG = 137 // 回存水位线
	SERVERMSG_HD_SAVE_ROOM_BONUS   SERVERMSG = 138 // 回存房间水池
	SERVERMSG_HD_SAVE_ALL          SERVERMSG = 150 // 通知DB回存的所有数据发送完成
	SERVERMSG_GH_GAME_CONNECT_HALL SERVERMSG = 170 // 游戏连接大厅
	SERVERMSG_GH_ROOM_INFO         SERVERMSG = 171 // 游戏上报房间信息给大厅
	SERVERMSG_HG_ROOM_WATER_PROFIT SERVERMSG = 172 // 大厅给游戏发盈利
	SERVERMSG_GH_SERVERFEE_LOG     SERVERMSG = 175 // 回存服务费
	SERVERMSG_HG_NOTIFY_ALTER_DATE SERVERMSG = 176 // 大厅通知游戏，修改玩家数据
	SERVERMSG_GH_MONEYCHANGE       SERVERMSG = 177 // 游戏改变金币，通知大厅
	SERVERMSG_HG_PLAYER_DATA_REQ   SERVERMSG = 180 // 大厅给游戏发送玩家数据
	SERVERMSG_GH_PLAYER_DATA_RES   SERVERMSG = 181 // 游戏回复大厅，收到玩家数据，大厅通知玩家进入
	SERVERMSG_GH_PLAYER_ENTER_ROOM SERVERMSG = 182 // 游戏通知大厅，玩家进入房间
	SERVERMSG_GH_PLAYER_LEAVE_ROOM SERVERMSG = 183 // 游戏通知大厅，玩家退出房间
	SERVERMSG_GH_ROOM_BONUS_REQ    SERVERMSG = 185 // 请求房间水池金额
	SERVERMSG_HG_ROOM_BONUS_RES    SERVERMSG = 186 //
	SERVERMSG_GH_ROOM_BONUS_SAVE   SERVERMSG = 187 // 回存房间水池金额
	SERVERMSG_GH_ROOM_PROFIT_SAVE  SERVERMSG = 188 // 回存房间盈利金额
)

// Enum value maps for SERVERMSG.
var (
	SERVERMSG_name = map[int32]string{
		0:   "SERVERMSG_UNKNOW",
		100: "HD_HELLO_DB",
		101: "SS_TEST_NETWORK",
		102: "SS_CLOSE_SERVER",
		103: "GH_CLOSE_SERVER_FIN",
		104: "SS_RELOAD_CONFIG",
		105: "HD_ALL_DATA",
		106: "DH_ALL_ACCOUNT_RESP",
		107: "DH_ALL_EMAIL_RESP",
		108: "DH_ALL_WATER_LINE",
		109: "DH_ALL_ROOM_BONUS",
		120: "DH_FINISH_DATA",
		131: "HD_SQL_SYNTAX",
		135: "HD_SAVE_ACCOUNT",
		136: "HD_SAVE_EMAIL_PERSON",
		137: "HD_SAVE_WATER_LINE",
		138: "HD_SAVE_ROOM_BONUS",
		150: "HD_SAVE_ALL",
		170: "GH_GAME_CONNECT_HALL",
		171: "GH_ROOM_INFO",
		172: "HG_ROOM_WATER_PROFIT",
		175: "GH_SERVERFEE_LOG",
		176: "HG_NOTIFY_ALTER_DATE",
		177: "GH_MONEYCHANGE",
		180: "HG_PLAYER_DATA_REQ",
		181: "GH_PLAYER_DATA_RES",
		182: "GH_PLAYER_ENTER_ROOM",
		183: "GH_PLAYER_LEAVE_ROOM",
		185: "GH_ROOM_BONUS_REQ",
		186: "HG_ROOM_BONUS_RES",
		187: "GH_ROOM_BONUS_SAVE",
		188: "GH_ROOM_PROFIT_SAVE",
	}
	SERVERMSG_value = map[string]int32{
		"SERVERMSG_UNKNOW":     0,
		"HD_HELLO_DB":          100,
		"SS_TEST_NETWORK":      101,
		"SS_CLOSE_SERVER":      102,
		"GH_CLOSE_SERVER_FIN":  103,
		"SS_RELOAD_CONFIG":     104,
		"HD_ALL_DATA":          105,
		"DH_ALL_ACCOUNT_RESP":  106,
		"DH_ALL_EMAIL_RESP":    107,
		"DH_ALL_WATER_LINE":    108,
		"DH_ALL_ROOM_BONUS":    109,
		"DH_FINISH_DATA":       120,
		"HD_SQL_SYNTAX":        131,
		"HD_SAVE_ACCOUNT":      135,
		"HD_SAVE_EMAIL_PERSON": 136,
		"HD_SAVE_WATER_LINE":   137,
		"HD_SAVE_ROOM_BONUS":   138,
		"HD_SAVE_ALL":          150,
		"GH_GAME_CONNECT_HALL": 170,
		"GH_ROOM_INFO":         171,
		"HG_ROOM_WATER_PROFIT": 172,
		"GH_SERVERFEE_LOG":     175,
		"HG_NOTIFY_ALTER_DATE": 176,
		"GH_MONEYCHANGE":       177,
		"HG_PLAYER_DATA_REQ":   180,
		"GH_PLAYER_DATA_RES":   181,
		"GH_PLAYER_ENTER_ROOM": 182,
		"GH_PLAYER_LEAVE_ROOM": 183,
		"GH_ROOM_BONUS_REQ":    185,
		"HG_ROOM_BONUS_RES":    186,
		"GH_ROOM_BONUS_SAVE":   187,
		"GH_ROOM_PROFIT_SAVE":  188,
	}
)

func (x SERVERMSG) Enum() *SERVERMSG {
	p := new(SERVERMSG)
	*p = x
	return p
}

func (x SERVERMSG) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SERVERMSG) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_server_server_proto_proto_enumTypes[0].Descriptor()
}

func (SERVERMSG) Type() protoreflect.EnumType {
	return &file_protobuf_server_server_proto_proto_enumTypes[0]
}

func (x SERVERMSG) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SERVERMSG.Descriptor instead.
func (SERVERMSG) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{0}
}

// 发送到db执行 sql syntax
type SQL_SYNTAX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataBaseType uint32 `protobuf:"varint,1,opt,name=DataBaseType,proto3" json:"DataBaseType,omitempty"` // 0 inst 1 log
	SQLSyntax    string `protobuf:"bytes,2,opt,name=SQLSyntax,proto3" json:"SQLSyntax,omitempty"`        // sql语句
}

func (x *SQL_SYNTAX) Reset() {
	*x = SQL_SYNTAX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQL_SYNTAX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQL_SYNTAX) ProtoMessage() {}

func (x *SQL_SYNTAX) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQL_SYNTAX.ProtoReflect.Descriptor instead.
func (*SQL_SYNTAX) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{0}
}

func (x *SQL_SYNTAX) GetDataBaseType() uint32 {
	if x != nil {
		return x.DataBaseType
	}
	return 0
}

func (x *SQL_SYNTAX) GetSQLSyntax() string {
	if x != nil {
		return x.SQLSyntax
	}
	return ""
}

// 请求账号信息
type ALL_ACCOUNT_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllAccount []*protomsg.AccountStorageData `protobuf:"bytes,1,rep,name=AllAccount,proto3" json:"AllAccount,omitempty"`
}

func (x *ALL_ACCOUNT_RESP) Reset() {
	*x = ALL_ACCOUNT_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ALL_ACCOUNT_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALL_ACCOUNT_RESP) ProtoMessage() {}

func (x *ALL_ACCOUNT_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALL_ACCOUNT_RESP.ProtoReflect.Descriptor instead.
func (*ALL_ACCOUNT_RESP) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ALL_ACCOUNT_RESP) GetAllAccount() []*protomsg.AccountStorageData {
	if x != nil {
		return x.AllAccount
	}
	return nil
}

// db返回所有水位线
type ALL_WATER_LINE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line []*SAVE_WATER_LINE `protobuf:"bytes,1,rep,name=Line,proto3" json:"Line,omitempty"`
}

func (x *ALL_WATER_LINE) Reset() {
	*x = ALL_WATER_LINE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ALL_WATER_LINE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALL_WATER_LINE) ProtoMessage() {}

func (x *ALL_WATER_LINE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALL_WATER_LINE.ProtoReflect.Descriptor instead.
func (*ALL_WATER_LINE) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ALL_WATER_LINE) GetLine() []*SAVE_WATER_LINE {
	if x != nil {
		return x.Line
	}
	return nil
}

// db返回所有房间水池
type ALL_ROOM_BONUS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bonus []*SAVE_ROOM_BONUS `protobuf:"bytes,1,rep,name=Bonus,proto3" json:"Bonus,omitempty"`
}

func (x *ALL_ROOM_BONUS) Reset() {
	*x = ALL_ROOM_BONUS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ALL_ROOM_BONUS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALL_ROOM_BONUS) ProtoMessage() {}

func (x *ALL_ROOM_BONUS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALL_ROOM_BONUS.ProtoReflect.Descriptor instead.
func (*ALL_ROOM_BONUS) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ALL_ROOM_BONUS) GetBonus() []*SAVE_ROOM_BONUS {
	if x != nil {
		return x.Bonus
	}
	return nil
}

// 请求邮件信息
type ALL_EMAIL_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcccountMail []*SAVE_EMAIL_PERSON `protobuf:"bytes,1,rep,name=AcccountMail,proto3" json:"AcccountMail,omitempty"`
}

func (x *ALL_EMAIL_RESP) Reset() {
	*x = ALL_EMAIL_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ALL_EMAIL_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALL_EMAIL_RESP) ProtoMessage() {}

func (x *ALL_EMAIL_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALL_EMAIL_RESP.ProtoReflect.Descriptor instead.
func (*ALL_EMAIL_RESP) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ALL_EMAIL_RESP) GetAcccountMail() []*SAVE_EMAIL_PERSON {
	if x != nil {
		return x.AcccountMail
	}
	return nil
}

// 回存玩家
type SAVE_ACCOUNT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccData *protomsg.AccountStorageData `protobuf:"bytes,1,opt,name=AccData,proto3" json:"AccData,omitempty"`
}

func (x *SAVE_ACCOUNT) Reset() {
	*x = SAVE_ACCOUNT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAVE_ACCOUNT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAVE_ACCOUNT) ProtoMessage() {}

func (x *SAVE_ACCOUNT) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAVE_ACCOUNT.ProtoReflect.Descriptor instead.
func (*SAVE_ACCOUNT) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{5}
}

func (x *SAVE_ACCOUNT) GetAccData() *protomsg.AccountStorageData {
	if x != nil {
		return x.AccData
	}
	return nil
}

// 回存邮件
type SAVE_EMAIL_PERSON struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint32            `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Emails    []*protomsg.Email `protobuf:"bytes,2,rep,name=Emails,proto3" json:"Emails,omitempty"`
}

func (x *SAVE_EMAIL_PERSON) Reset() {
	*x = SAVE_EMAIL_PERSON{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAVE_EMAIL_PERSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAVE_EMAIL_PERSON) ProtoMessage() {}

func (x *SAVE_EMAIL_PERSON) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAVE_EMAIL_PERSON.ProtoReflect.Descriptor instead.
func (*SAVE_EMAIL_PERSON) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{6}
}

func (x *SAVE_EMAIL_PERSON) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SAVE_EMAIL_PERSON) GetEmails() []*protomsg.Email {
	if x != nil {
		return x.Emails
	}
	return nil
}

// 回存水位线
type SAVE_WATER_LINE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID    uint32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	WaterLine string `protobuf:"bytes,2,opt,name=WaterLine,proto3" json:"WaterLine,omitempty"`
}

func (x *SAVE_WATER_LINE) Reset() {
	*x = SAVE_WATER_LINE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAVE_WATER_LINE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAVE_WATER_LINE) ProtoMessage() {}

func (x *SAVE_WATER_LINE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAVE_WATER_LINE.ProtoReflect.Descriptor instead.
func (*SAVE_WATER_LINE) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{7}
}

func (x *SAVE_WATER_LINE) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *SAVE_WATER_LINE) GetWaterLine() string {
	if x != nil {
		return x.WaterLine
	}
	return ""
}

// 水池
type SAVE_ROOM_BONUS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *SAVE_ROOM_BONUS) Reset() {
	*x = SAVE_ROOM_BONUS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAVE_ROOM_BONUS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAVE_ROOM_BONUS) ProtoMessage() {}

func (x *SAVE_ROOM_BONUS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAVE_ROOM_BONUS.ProtoReflect.Descriptor instead.
func (*SAVE_ROOM_BONUS) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{8}
}

func (x *SAVE_ROOM_BONUS) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *SAVE_ROOM_BONUS) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 游戏连接大厅 170
type GAME_CONNECT_HALL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID uint32 `protobuf:"varint,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	GameType uint32 `protobuf:"varint,2,opt,name=GameType,proto3" json:"GameType,omitempty"`
}

func (x *GAME_CONNECT_HALL) Reset() {
	*x = GAME_CONNECT_HALL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GAME_CONNECT_HALL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GAME_CONNECT_HALL) ProtoMessage() {}

func (x *GAME_CONNECT_HALL) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GAME_CONNECT_HALL.ProtoReflect.Descriptor instead.
func (*GAME_CONNECT_HALL) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{9}
}

func (x *GAME_CONNECT_HALL) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *GAME_CONNECT_HALL) GetGameType() uint32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

// 游戏上报房间信息给大厅 171
type ROOM_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID uint32   `protobuf:"varint,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`      // 服务器id
	RoomsID  []uint32 `protobuf:"varint,2,rep,packed,name=RoomsID,proto3" json:"RoomsID,omitempty"` // 房间ID
}

func (x *ROOM_INFO) Reset() {
	*x = ROOM_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROOM_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROOM_INFO) ProtoMessage() {}

func (x *ROOM_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROOM_INFO.ProtoReflect.Descriptor instead.
func (*ROOM_INFO) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{10}
}

func (x *ROOM_INFO) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *ROOM_INFO) GetRoomsID() []uint32 {
	if x != nil {
		return x.RoomsID
	}
	return nil
}

// 回存服务费 175
type SERVERFEE_LOG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	ServerFee uint32 `protobuf:"varint,2,opt,name=ServerFee,proto3" json:"ServerFee,omitempty"`
	GameType  uint32 `protobuf:"varint,3,opt,name=GameType,proto3" json:"GameType,omitempty"`
	Time      string `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	RoomID    uint32 `protobuf:"varint,5,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *SERVERFEE_LOG) Reset() {
	*x = SERVERFEE_LOG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SERVERFEE_LOG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SERVERFEE_LOG) ProtoMessage() {}

func (x *SERVERFEE_LOG) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SERVERFEE_LOG.ProtoReflect.Descriptor instead.
func (*SERVERFEE_LOG) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{11}
}

func (x *SERVERFEE_LOG) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *SERVERFEE_LOG) GetServerFee() uint32 {
	if x != nil {
		return x.ServerFee
	}
	return 0
}

func (x *SERVERFEE_LOG) GetGameType() uint32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *SERVERFEE_LOG) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SERVERFEE_LOG) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

// 大厅通知游戏，修改玩家数据 176
type NOTIFY_ALTER_DATE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID   uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Type        int32  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`               // 1金币 2杀数
	AlterValue  int64  `protobuf:"varint,3,opt,name=AlterValue,proto3" json:"AlterValue,omitempty"`   // 改变值
	RoomID      uint32 `protobuf:"varint,4,opt,name=RoomID,proto3" json:"RoomID,omitempty"`           // 玩家所在房间
	OperateType int32  `protobuf:"varint,5,opt,name=operateType,proto3" json:"operateType,omitempty"` // 操作
}

func (x *NOTIFY_ALTER_DATE) Reset() {
	*x = NOTIFY_ALTER_DATE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NOTIFY_ALTER_DATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NOTIFY_ALTER_DATE) ProtoMessage() {}

func (x *NOTIFY_ALTER_DATE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NOTIFY_ALTER_DATE.ProtoReflect.Descriptor instead.
func (*NOTIFY_ALTER_DATE) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{12}
}

func (x *NOTIFY_ALTER_DATE) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *NOTIFY_ALTER_DATE) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NOTIFY_ALTER_DATE) GetAlterValue() int64 {
	if x != nil {
		return x.AlterValue
	}
	return 0
}

func (x *NOTIFY_ALTER_DATE) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *NOTIFY_ALTER_DATE) GetOperateType() int32 {
	if x != nil {
		return x.OperateType
	}
	return 0
}

// 游戏改变金币，通知大厅 177
type MONEYCHANGE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID   uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	ChangeValue int64  `protobuf:"varint,2,opt,name=ChangeValue,proto3" json:"ChangeValue,omitempty"`
	Value       int64  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Operate     uint32 `protobuf:"varint,4,opt,name=Operate,proto3" json:"Operate,omitempty"`
	Time        string `protobuf:"bytes,6,opt,name=Time,proto3" json:"Time,omitempty"`
	RoomID      uint32 `protobuf:"varint,7,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *MONEYCHANGE) Reset() {
	*x = MONEYCHANGE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MONEYCHANGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MONEYCHANGE) ProtoMessage() {}

func (x *MONEYCHANGE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MONEYCHANGE.ProtoReflect.Descriptor instead.
func (*MONEYCHANGE) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{13}
}

func (x *MONEYCHANGE) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *MONEYCHANGE) GetChangeValue() int64 {
	if x != nil {
		return x.ChangeValue
	}
	return 0
}

func (x *MONEYCHANGE) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MONEYCHANGE) GetOperate() uint32 {
	if x != nil {
		return x.Operate
	}
	return 0
}

func (x *MONEYCHANGE) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *MONEYCHANGE) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

// 大厅给游戏发送玩家数据
type PLAYER_DATA_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account     *protomsg.AccountStorageData `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`         // 玩家基础信息
	AccountData *protomsg.AccountGameData    `protobuf:"bytes,2,opt,name=AccountData,proto3" json:"AccountData,omitempty"` // 玩家游戏信息
	RoomID      uint32                       `protobuf:"varint,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Reback      bool                         `protobuf:"varint,4,opt,name=reback,proto3" json:"reback,omitempty"` // 是否需要返回
}

func (x *PLAYER_DATA_REQ) Reset() {
	*x = PLAYER_DATA_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLAYER_DATA_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLAYER_DATA_REQ) ProtoMessage() {}

func (x *PLAYER_DATA_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLAYER_DATA_REQ.ProtoReflect.Descriptor instead.
func (*PLAYER_DATA_REQ) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{14}
}

func (x *PLAYER_DATA_REQ) GetAccount() *protomsg.AccountStorageData {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *PLAYER_DATA_REQ) GetAccountData() *protomsg.AccountGameData {
	if x != nil {
		return x.AccountData
	}
	return nil
}

func (x *PLAYER_DATA_REQ) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *PLAYER_DATA_REQ) GetReback() bool {
	if x != nil {
		return x.Reback
	}
	return false
}

// 游戏回复大厅，收到玩家数据，大厅通知玩家进入
type PLAYER_DATA_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       uint32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //
	AccountID uint32 `protobuf:"varint,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	RoomID    uint32 `protobuf:"varint,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *PLAYER_DATA_RES) Reset() {
	*x = PLAYER_DATA_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLAYER_DATA_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLAYER_DATA_RES) ProtoMessage() {}

func (x *PLAYER_DATA_RES) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLAYER_DATA_RES.ProtoReflect.Descriptor instead.
func (*PLAYER_DATA_RES) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{15}
}

func (x *PLAYER_DATA_RES) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *PLAYER_DATA_RES) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *PLAYER_DATA_RES) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

// 游戏通知大厅，玩家进入房间
type PLAYER_ENTER_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID   uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	RoomID      uint32 `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	PlayerCount uint32 `protobuf:"varint,3,opt,name=PlayerCount,proto3" json:"PlayerCount,omitempty"`
	RobotCount  uint32 `protobuf:"varint,4,opt,name=RobotCount,proto3" json:"RobotCount,omitempty"`
}

func (x *PLAYER_ENTER_ROOM) Reset() {
	*x = PLAYER_ENTER_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLAYER_ENTER_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLAYER_ENTER_ROOM) ProtoMessage() {}

func (x *PLAYER_ENTER_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLAYER_ENTER_ROOM.ProtoReflect.Descriptor instead.
func (*PLAYER_ENTER_ROOM) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{16}
}

func (x *PLAYER_ENTER_ROOM) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *PLAYER_ENTER_ROOM) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *PLAYER_ENTER_ROOM) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *PLAYER_ENTER_ROOM) GetRobotCount() uint32 {
	if x != nil {
		return x.RobotCount
	}
	return 0
}

// 游戏通知大厅，玩家退出房间
type PLAYER_LEAVE_ROOM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID   uint32 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	RoomID      uint32 `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	PlayerCount uint32 `protobuf:"varint,3,opt,name=PlayerCount,proto3" json:"PlayerCount,omitempty"`
	RobotCount  uint32 `protobuf:"varint,4,opt,name=RobotCount,proto3" json:"RobotCount,omitempty"`
}

func (x *PLAYER_LEAVE_ROOM) Reset() {
	*x = PLAYER_LEAVE_ROOM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLAYER_LEAVE_ROOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLAYER_LEAVE_ROOM) ProtoMessage() {}

func (x *PLAYER_LEAVE_ROOM) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLAYER_LEAVE_ROOM.ProtoReflect.Descriptor instead.
func (*PLAYER_LEAVE_ROOM) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{17}
}

func (x *PLAYER_LEAVE_ROOM) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *PLAYER_LEAVE_ROOM) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *PLAYER_LEAVE_ROOM) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *PLAYER_LEAVE_ROOM) GetRobotCount() uint32 {
	if x != nil {
		return x.RobotCount
	}
	return 0
}

// 请求房间水池金额 185
type ROOM_BONUS_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *ROOM_BONUS_REQ) Reset() {
	*x = ROOM_BONUS_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROOM_BONUS_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROOM_BONUS_REQ) ProtoMessage() {}

func (x *ROOM_BONUS_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROOM_BONUS_REQ.ProtoReflect.Descriptor instead.
func (*ROOM_BONUS_REQ) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{18}
}

func (x *ROOM_BONUS_REQ) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ROOM_BONUS_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"` // 房间水池金额
}

func (x *ROOM_BONUS_RES) Reset() {
	*x = ROOM_BONUS_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROOM_BONUS_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROOM_BONUS_RES) ProtoMessage() {}

func (x *ROOM_BONUS_RES) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROOM_BONUS_RES.ProtoReflect.Descriptor instead.
func (*ROOM_BONUS_RES) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{19}
}

func (x *ROOM_BONUS_RES) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *ROOM_BONUS_RES) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 回存房间水池金额
type ROOM_BONUS_SAVE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"` // 房间水池金额
}

func (x *ROOM_BONUS_SAVE) Reset() {
	*x = ROOM_BONUS_SAVE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROOM_BONUS_SAVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROOM_BONUS_SAVE) ProtoMessage() {}

func (x *ROOM_BONUS_SAVE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROOM_BONUS_SAVE.ProtoReflect.Descriptor instead.
func (*ROOM_BONUS_SAVE) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{20}
}

func (x *ROOM_BONUS_SAVE) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *ROOM_BONUS_SAVE) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 回存房间水池金额
type ROOM_PROFIT_SAVE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint32 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"` // 房间水池金额
}

func (x *ROOM_PROFIT_SAVE) Reset() {
	*x = ROOM_PROFIT_SAVE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_server_proto_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROOM_PROFIT_SAVE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROOM_PROFIT_SAVE) ProtoMessage() {}

func (x *ROOM_PROFIT_SAVE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_server_proto_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROOM_PROFIT_SAVE.ProtoReflect.Descriptor instead.
func (*ROOM_PROFIT_SAVE) Descriptor() ([]byte, []int) {
	return file_protobuf_server_server_proto_proto_rawDescGZIP(), []int{21}
}

func (x *ROOM_PROFIT_SAVE) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *ROOM_PROFIT_SAVE) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protobuf_server_server_proto_proto protoreflect.FileDescriptor

var file_protobuf_server_server_proto_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x1a, 0x13,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a, 0x53, 0x51, 0x4c, 0x5f, 0x53, 0x59, 0x4e, 0x54, 0x41,
	0x58, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x51, 0x4c, 0x53, 0x79, 0x6e, 0x74,
	0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x51, 0x4c, 0x53, 0x79, 0x6e,
	0x74, 0x61, 0x78, 0x22, 0x50, 0x0a, 0x10, 0x41, 0x4c, 0x4c, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x3c, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0e, 0x41, 0x4c, 0x4c, 0x5f, 0x57, 0x41, 0x54,
	0x45, 0x52, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67,
	0x2e, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x57, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x4e, 0x45,
	0x52, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x41, 0x0a, 0x0e, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x4f,
	0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x12, 0x2f, 0x0a, 0x05, 0x42, 0x6f, 0x6e, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d,
	0x73, 0x67, 0x2e, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e,
	0x55, 0x53, 0x52, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x0e, 0x41, 0x4c, 0x4c,
	0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x3f, 0x0a, 0x0c, 0x41,
	0x63, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x41, 0x56,
	0x45, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x52, 0x0c,
	0x41, 0x63, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x46, 0x0a, 0x0c,
	0x53, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x12, 0x36, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x5a, 0x0a, 0x11, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x45, 0x4d, 0x41,
	0x49, 0x4c, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73,
	0x22, 0x47, 0x0a, 0x0f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x57, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x4c,
	0x49, 0x4e, 0x45, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x57,
	0x61, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x57, 0x61, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x41, 0x56,
	0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x41,
	0x4d, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x48, 0x41, 0x4c, 0x4c, 0x12,
	0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x47,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x47,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x41, 0x0a, 0x09, 0x52, 0x4f, 0x4f, 0x4d, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x49, 0x44, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x53,
	0x45, 0x52, 0x56, 0x45, 0x52, 0x46, 0x45, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x22, 0x9f, 0x01, 0x0a, 0x11, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x5f, 0x41, 0x4c, 0x54, 0x45,
	0x52, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x6c, 0x74, 0x65,
	0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x41, 0x6c,
	0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x0b, 0x4d, 0x4f, 0x4e, 0x45, 0x59, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0xb6,
	0x01, 0x0a, 0x0f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x52,
	0x45, 0x51, 0x12, 0x36, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x72, 0x65, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x59, 0x0a, 0x0f, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x45, 0x4e,
	0x54, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x20,
	0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x8b, 0x01, 0x0a, 0x11, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x41, 0x56,
	0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x28,
	0x0a, 0x0e, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x51,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x4f, 0x4f, 0x4d,
	0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x4f, 0x4f, 0x4d,
	0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x10, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x54, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0xf2, 0x05, 0x0a, 0x09,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x4d, 0x53, 0x47, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x4d, 0x53, 0x47, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x48, 0x44, 0x5f, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x5f, 0x44, 0x42, 0x10, 0x64,
	0x12, 0x13, 0x0a, 0x0f, 0x53, 0x53, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x10, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x53, 0x5f, 0x43, 0x4c, 0x4f, 0x53,
	0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x66, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x48,
	0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x46, 0x49,
	0x4e, 0x10, 0x67, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x4f, 0x41, 0x44,
	0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x68, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x44, 0x5f,
	0x41, 0x4c, 0x4c, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x69, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x48,
	0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x10, 0x6a, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x48, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x45, 0x4d,
	0x41, 0x49, 0x4c, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x6b, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x48,
	0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x57, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x10,
	0x6c, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x48, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x4f, 0x4f, 0x4d,
	0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x10, 0x6d, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x48, 0x5f, 0x46,
	0x49, 0x4e, 0x49, 0x53, 0x48, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x78, 0x12, 0x12, 0x0a, 0x0d,
	0x48, 0x44, 0x5f, 0x53, 0x51, 0x4c, 0x5f, 0x53, 0x59, 0x4e, 0x54, 0x41, 0x58, 0x10, 0x83, 0x01,
	0x12, 0x14, 0x0a, 0x0f, 0x48, 0x44, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f,
	0x55, 0x4e, 0x54, 0x10, 0x87, 0x01, 0x12, 0x19, 0x0a, 0x14, 0x48, 0x44, 0x5f, 0x53, 0x41, 0x56,
	0x45, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x10, 0x88,
	0x01, 0x12, 0x17, 0x0a, 0x12, 0x48, 0x44, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x57, 0x41, 0x54,
	0x45, 0x52, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x89, 0x01, 0x12, 0x17, 0x0a, 0x12, 0x48, 0x44,
	0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53,
	0x10, 0x8a, 0x01, 0x12, 0x10, 0x0a, 0x0b, 0x48, 0x44, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x41,
	0x4c, 0x4c, 0x10, 0x96, 0x01, 0x12, 0x19, 0x0a, 0x14, 0x47, 0x48, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x48, 0x41, 0x4c, 0x4c, 0x10, 0xaa, 0x01,
	0x12, 0x11, 0x0a, 0x0c, 0x47, 0x48, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x49, 0x4e, 0x46, 0x4f,
	0x10, 0xab, 0x01, 0x12, 0x19, 0x0a, 0x14, 0x48, 0x47, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x57,
	0x41, 0x54, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x54, 0x10, 0xac, 0x01, 0x12, 0x15,
	0x0a, 0x10, 0x47, 0x48, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x46, 0x45, 0x45, 0x5f, 0x4c,
	0x4f, 0x47, 0x10, 0xaf, 0x01, 0x12, 0x19, 0x0a, 0x14, 0x48, 0x47, 0x5f, 0x4e, 0x4f, 0x54, 0x49,
	0x46, 0x59, 0x5f, 0x41, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10, 0xb0, 0x01,
	0x12, 0x13, 0x0a, 0x0e, 0x47, 0x48, 0x5f, 0x4d, 0x4f, 0x4e, 0x45, 0x59, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x10, 0xb1, 0x01, 0x12, 0x17, 0x0a, 0x12, 0x48, 0x47, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x45, 0x52, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x52, 0x45, 0x51, 0x10, 0xb4, 0x01, 0x12, 0x17,
	0x0a, 0x12, 0x47, 0x48, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x44, 0x41, 0x54, 0x41,
	0x5f, 0x52, 0x45, 0x53, 0x10, 0xb5, 0x01, 0x12, 0x19, 0x0a, 0x14, 0x47, 0x48, 0x5f, 0x50, 0x4c,
	0x41, 0x59, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10,
	0xb6, 0x01, 0x12, 0x19, 0x0a, 0x14, 0x47, 0x48, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f,
	0x4c, 0x45, 0x41, 0x56, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0xb7, 0x01, 0x12, 0x16, 0x0a,
	0x11, 0x47, 0x48, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x5f, 0x52,
	0x45, 0x51, 0x10, 0xb9, 0x01, 0x12, 0x16, 0x0a, 0x11, 0x48, 0x47, 0x5f, 0x52, 0x4f, 0x4f, 0x4d,
	0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x10, 0xba, 0x01, 0x12, 0x17, 0x0a,
	0x12, 0x47, 0x48, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x5f, 0x53,
	0x41, 0x56, 0x45, 0x10, 0xbb, 0x01, 0x12, 0x18, 0x0a, 0x13, 0x47, 0x48, 0x5f, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x54, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x10, 0xbc, 0x01,
	0x42, 0x15, 0x5a, 0x13, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73,
	0x67, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_server_server_proto_proto_rawDescOnce sync.Once
	file_protobuf_server_server_proto_proto_rawDescData = file_protobuf_server_server_proto_proto_rawDesc
)

func file_protobuf_server_server_proto_proto_rawDescGZIP() []byte {
	file_protobuf_server_server_proto_proto_rawDescOnce.Do(func() {
		file_protobuf_server_server_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_server_server_proto_proto_rawDescData)
	})
	return file_protobuf_server_server_proto_proto_rawDescData
}

var file_protobuf_server_server_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_server_server_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_protobuf_server_server_proto_proto_goTypes = []interface{}{
	(SERVERMSG)(0),                      // 0: protomsg.SERVERMSG
	(*SQL_SYNTAX)(nil),                  // 1: protomsg.SQL_SYNTAX
	(*ALL_ACCOUNT_RESP)(nil),            // 2: protomsg.ALL_ACCOUNT_RESP
	(*ALL_WATER_LINE)(nil),              // 3: protomsg.ALL_WATER_LINE
	(*ALL_ROOM_BONUS)(nil),              // 4: protomsg.ALL_ROOM_BONUS
	(*ALL_EMAIL_RESP)(nil),              // 5: protomsg.ALL_EMAIL_RESP
	(*SAVE_ACCOUNT)(nil),                // 6: protomsg.SAVE_ACCOUNT
	(*SAVE_EMAIL_PERSON)(nil),           // 7: protomsg.SAVE_EMAIL_PERSON
	(*SAVE_WATER_LINE)(nil),             // 8: protomsg.SAVE_WATER_LINE
	(*SAVE_ROOM_BONUS)(nil),             // 9: protomsg.SAVE_ROOM_BONUS
	(*GAME_CONNECT_HALL)(nil),           // 10: protomsg.GAME_CONNECT_HALL
	(*ROOM_INFO)(nil),                   // 11: protomsg.ROOM_INFO
	(*SERVERFEE_LOG)(nil),               // 12: protomsg.SERVERFEE_LOG
	(*NOTIFY_ALTER_DATE)(nil),           // 13: protomsg.NOTIFY_ALTER_DATE
	(*MONEYCHANGE)(nil),                 // 14: protomsg.MONEYCHANGE
	(*PLAYER_DATA_REQ)(nil),             // 15: protomsg.PLAYER_DATA_REQ
	(*PLAYER_DATA_RES)(nil),             // 16: protomsg.PLAYER_DATA_RES
	(*PLAYER_ENTER_ROOM)(nil),           // 17: protomsg.PLAYER_ENTER_ROOM
	(*PLAYER_LEAVE_ROOM)(nil),           // 18: protomsg.PLAYER_LEAVE_ROOM
	(*ROOM_BONUS_REQ)(nil),              // 19: protomsg.ROOM_BONUS_REQ
	(*ROOM_BONUS_RES)(nil),              // 20: protomsg.ROOM_BONUS_RES
	(*ROOM_BONUS_SAVE)(nil),             // 21: protomsg.ROOM_BONUS_SAVE
	(*ROOM_PROFIT_SAVE)(nil),            // 22: protomsg.ROOM_PROFIT_SAVE
	(*protomsg.AccountStorageData)(nil), // 23: protomsg.AccountStorageData
	(*protomsg.Email)(nil),              // 24: protomsg.Email
	(*protomsg.AccountGameData)(nil),    // 25: protomsg.AccountGameData
}
var file_protobuf_server_server_proto_proto_depIdxs = []int32{
	23, // 0: protomsg.ALL_ACCOUNT_RESP.AllAccount:type_name -> protomsg.AccountStorageData
	8,  // 1: protomsg.ALL_WATER_LINE.Line:type_name -> protomsg.SAVE_WATER_LINE
	9,  // 2: protomsg.ALL_ROOM_BONUS.Bonus:type_name -> protomsg.SAVE_ROOM_BONUS
	7,  // 3: protomsg.ALL_EMAIL_RESP.AcccountMail:type_name -> protomsg.SAVE_EMAIL_PERSON
	23, // 4: protomsg.SAVE_ACCOUNT.AccData:type_name -> protomsg.AccountStorageData
	24, // 5: protomsg.SAVE_EMAIL_PERSON.Emails:type_name -> protomsg.Email
	23, // 6: protomsg.PLAYER_DATA_REQ.Account:type_name -> protomsg.AccountStorageData
	25, // 7: protomsg.PLAYER_DATA_REQ.AccountData:type_name -> protomsg.AccountGameData
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protobuf_server_server_proto_proto_init() }
func file_protobuf_server_server_proto_proto_init() {
	if File_protobuf_server_server_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_server_server_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQL_SYNTAX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ALL_ACCOUNT_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ALL_WATER_LINE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ALL_ROOM_BONUS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ALL_EMAIL_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAVE_ACCOUNT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAVE_EMAIL_PERSON); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAVE_WATER_LINE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAVE_ROOM_BONUS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GAME_CONNECT_HALL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROOM_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SERVERFEE_LOG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NOTIFY_ALTER_DATE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MONEYCHANGE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLAYER_DATA_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLAYER_DATA_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLAYER_ENTER_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLAYER_LEAVE_ROOM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROOM_BONUS_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROOM_BONUS_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROOM_BONUS_SAVE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_server_proto_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROOM_PROFIT_SAVE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_server_server_proto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_server_server_proto_proto_goTypes,
		DependencyIndexes: file_protobuf_server_server_proto_proto_depIdxs,
		EnumInfos:         file_protobuf_server_server_proto_proto_enumTypes,
		MessageInfos:      file_protobuf_server_server_proto_proto_msgTypes,
	}.Build()
	File_protobuf_server_server_proto_proto = out.File
	file_protobuf_server_server_proto_proto_rawDesc = nil
	file_protobuf_server_server_proto_proto_goTypes = nil
	file_protobuf_server_server_proto_proto_depIdxs = nil
}
